import type { Locale } from '../../_content/types';

/** Textos propios de las paginas /docs/extension-ui/<componente> (es/en). Las descripciones del esquema quedan en espanol. */
const S = {
    es: {
        docs: 'Documentación',
        kitTitle: 'Kit de componentes y UI',
        breadcrumb: 'Ruta de navegación',
        category: 'Categoría',
        acceptsChildren: 'Acepta hijos',
        noChildren: 'Sin hijos',
        propsTitle: 'Props',
        propsIntro: 'Tabla generada desde el esquema real (`ui-schema.ts`); si el esquema cambia, cambia esta tabla.',
        colProp: 'Prop',
        colType: 'Tipo',
        colRequired: 'Requerido',
        colValues: 'Valores permitidos',
        colDefault: 'Por defecto',
        colDesc: 'Descripción',
        yes: 'Sí',
        no: 'No',
        actionProp: 'acción',
        noProps: 'Este componente no tiene props propias.',
        commonProps: 'Props comunes a todos los componentes',
        nested: 'Estructuras anidadas',
        events: 'Eventos y acciones que acepta',
        eventsIntro: 'Props que ejecutan una acción (o cadena de acciones). Las variables disponibles en `${...}` dentro de la acción son las que recibe cada evento.',
        colEvent: 'Evento',
        colReceives: 'Recibe',
        noEvents: 'No tiene eventos propios (solo `onLoad`, común a todos).',
        stateTitle: 'Estado y contexto que usa',
        stateIntro: 'Cómo interactúa con `state` y `context` (expresiones `${...}`).',
        simulator: 'Simulador interactivo',
        simulatorIntro: 'Renderiza el JSON validado con el mismo renderer y el mismo kit que la app, con el tema actual de esta página. Nada sale a la red: CALL_BACKEND usa una respuesta simulada.',
        loadingSim: 'Cargando el simulador…',
        preview: 'Vista previa',
        previewRegion: 'Vista previa en vivo del componente',
        controls: 'Controles',
        preset: 'Preset',
        presetGroupLabel: 'Ejemplos y estados',
        reset: 'Restablecer',
        copyJson: 'Copiar JSON',
        copySnippet: 'Copiar manifest snippet',
        copied: 'Copiado',
        copyFailed: 'No se pudo copiar',
        tabForm: 'Props (formulario)',
        tabJson: 'JSON',
        formHint: 'Generado del esquema: cada control edita una prop del primer nivel. Vacío = quitar la prop.',
        jsonLabel: 'JSON del componente (se valida mientras escribes)',
        valid: 'JSON válido',
        invalid: 'JSON no válido: la vista previa conserva la última versión válida.',
        errors: 'Errores',
        warnings: 'Avisos',
        deprecations: 'Obsoleto',
        line: 'línea {line}, columna {col}',
        bytes: '{n} de {max} bytes',
        stateEditor: 'Estado inicial (`state`)',
        stateEditorHint: 'JSON. Se aplica al montar: cámbialo y la vista previa se reinicia. Úsalo con `${state.x}`, `bind`, `hidden`...',
        liveState: 'Estado actual',
        context: 'Contexto simulado',
        mountPoint: 'Punto de montaje',
        toolbarMode: 'Barra de acciones',
        toolbarOff: 'Normal',
        toolbarCompact: 'Compacta (iconos)',
        toolbarMenu: 'Menú "Extensiones"',
        toolbarOnlyBars: 'Solo aplica a EMAIL_TOOLBAR, COMPOSER_TOOLBAR, CALENDAR_TOOLBAR y CONTACTS_TOOLBAR.',
        contextJson: 'Contexto (`context`)',
        backend: 'Backend simulado (CALL_BACKEND)',
        backendIntro: 'Responde a cualquier función sin llamar a ningún servidor. Cambia entre éxito (`onSuccess`) y error (`onError`) para ver ambos caminos.',
        backendSuccess: 'Éxito (onSuccess)',
        backendError: 'Error (onError)',
        backendResult: 'Resultado (JSON)',
        backendErrorText: 'Mensaje de error',
        backendDelay: 'Retraso (ms)',
        eventLog: 'Registro de eventos y acciones',
        eventLogIntro: 'Cada interacción y cada acción que se ejecutaría, con los argumentos ya interpolados. Los avisos, la navegación, las URL y el portapapeles NO se ejecutan.',
        clearLog: 'Vaciar registro',
        logEmpty: 'Interactúa con la vista previa para ver qué acciones se dispararían.',
        toasts: 'Avisos simulados',
        kindInteraction: 'Interacción',
        kindAction: 'Acción',
        kindBackend: 'Backend',
        kindComposer: 'Composer',
        outcomeOk: 'correcto',
        outcomeError: 'error',
        related: 'Acciones relacionadas',
        relatedIntro: 'Acciones que este componente puede disparar desde sus props de acción (cualquiera de UI_ACTIONS) y las que lo controlan. Detalle de cada acción en la [sección de acciones](/docs/extension-ui#actions).',
        actionsUsedHere: 'Usadas en sus ejemplos y manifests',
        actionsReceived: 'Acciones que lo controlan',
        actionRequired: 'Obligatorios',
        actionFields: 'Campos',
        none: 'Ninguna.',
        manifestExample: 'Ejemplo en un manifest real',
        manifestFrom: 'Tomado de `{file}` ({extension}), en `{path}` (punto `{point}`).',
        manifestAlso: 'También se usa en: {files}.',
        manifestNone: 'Ningún manifest de `bloomx-extensions` usa todavía este componente. Este es el ejemplo del esquema (`ui-examples.ts`) dentro de un manifest mínimo.',
        manifestSnippetTitle: 'Manifest mínimo',
        onThisPage: 'En esta página',
        prev: 'Anterior',
        next: 'Siguiente',
        indexTitle: 'Todos los componentes',
        indexIntro: 'Una página por componente con su tabla de props, vista previa en vivo, simulador y ejemplo en un manifest real. Generadas desde el esquema.',
        indexCount: '{n} componentes',
        props: 'props',
        seeAllActions: 'Ver todas las acciones',
        tryIt: 'Probar en el simulador',
        simNode: 'Nodo',
        interaction: { click: 'clic', change: 'cambio', submit: 'envío' } as Record<string, string>,
    },
    en: {
        docs: 'Documentation',
        kitTitle: 'Component kit and UI',
        breadcrumb: 'Breadcrumb',
        category: 'Category',
        acceptsChildren: 'Accepts children',
        noChildren: 'No children',
        propsTitle: 'Props',
        propsIntro: 'Table generated from the real schema (`ui-schema.ts`); if the schema changes, this table changes.',
        colProp: 'Prop',
        colType: 'Type',
        colRequired: 'Required',
        colValues: 'Allowed values',
        colDefault: 'Default',
        colDesc: 'Description',
        yes: 'Yes',
        no: 'No',
        actionProp: 'action',
        noProps: 'This component has no props of its own.',
        commonProps: 'Props common to every component',
        nested: 'Nested structures',
        events: 'Events and actions it accepts',
        eventsIntro: 'Props that run an action (or a chain of actions). The variables available in `${...}` inside the action are the ones each event receives.',
        colEvent: 'Event',
        colReceives: 'Receives',
        noEvents: 'No events of its own (only `onLoad`, common to all).',
        stateTitle: 'State and context it uses',
        stateIntro: 'How it interacts with `state` and `context` (`${...}` expressions).',
        simulator: 'Interactive simulator',
        simulatorIntro: 'Renders the validated JSON with the same renderer and kit as the app, using the current theme of this page. Nothing goes over the network: CALL_BACKEND uses a simulated response.',
        loadingSim: 'Loading the simulator…',
        preview: 'Preview',
        previewRegion: 'Live preview of the component',
        controls: 'Controls',
        preset: 'Preset',
        presetGroupLabel: 'Examples and states',
        reset: 'Reset',
        copyJson: 'Copy JSON',
        copySnippet: 'Copy manifest snippet',
        copied: 'Copied',
        copyFailed: 'Could not copy',
        tabForm: 'Props (form)',
        tabJson: 'JSON',
        formHint: 'Generated from the schema: each control edits a first-level prop. Empty = remove the prop.',
        jsonLabel: 'Component JSON (validated as you type)',
        valid: 'Valid JSON',
        invalid: 'Invalid JSON: the preview keeps the last valid version.',
        errors: 'Errors',
        warnings: 'Warnings',
        deprecations: 'Deprecated',
        line: 'line {line}, column {col}',
        bytes: '{n} of {max} bytes',
        stateEditor: 'Initial state (`state`)',
        stateEditorHint: 'JSON. Applied on mount: change it and the preview restarts. Use it with `${state.x}`, `bind`, `hidden`...',
        liveState: 'Current state',
        context: 'Simulated context',
        mountPoint: 'Mount point',
        toolbarMode: 'Action bar',
        toolbarOff: 'Normal',
        toolbarCompact: 'Compact (icons)',
        toolbarMenu: '"Extensions" menu',
        toolbarOnlyBars: 'Only applies to EMAIL_TOOLBAR, COMPOSER_TOOLBAR, CALENDAR_TOOLBAR and CONTACTS_TOOLBAR.',
        contextJson: 'Context (`context`)',
        backend: 'Simulated backend (CALL_BACKEND)',
        backendIntro: 'Answers any function without calling a server. Switch between success (`onSuccess`) and error (`onError`) to see both paths.',
        backendSuccess: 'Success (onSuccess)',
        backendError: 'Error (onError)',
        backendResult: 'Result (JSON)',
        backendErrorText: 'Error message',
        backendDelay: 'Delay (ms)',
        eventLog: 'Event and action log',
        eventLogIntro: 'Every interaction and every action that would run, with arguments already interpolated. Toasts, navigation, URLs and the clipboard are NOT executed.',
        clearLog: 'Clear log',
        logEmpty: 'Interact with the preview to see which actions would fire.',
        toasts: 'Simulated toasts',
        kindInteraction: 'Interaction',
        kindAction: 'Action',
        kindBackend: 'Backend',
        kindComposer: 'Composer',
        outcomeOk: 'ok',
        outcomeError: 'error',
        related: 'Related actions',
        relatedIntro: 'Actions this component can fire from its action props (any of UI_ACTIONS) and the ones that control it. Details of each action in the [actions section](/docs/extension-ui#actions).',
        actionsUsedHere: 'Used in its examples and manifests',
        actionsReceived: 'Actions that control it',
        actionRequired: 'Required',
        actionFields: 'Fields',
        none: 'None.',
        manifestExample: 'Example in a real manifest',
        manifestFrom: 'Taken from `{file}` ({extension}), at `{path}` (point `{point}`).',
        manifestAlso: 'Also used in: {files}.',
        manifestNone: 'No manifest in `bloomx-extensions` uses this component yet. This is the schema example (`ui-examples.ts`) inside a minimal manifest.',
        manifestSnippetTitle: 'Minimal manifest',
        onThisPage: 'On this page',
        prev: 'Previous',
        next: 'Next',
        indexTitle: 'All components',
        indexIntro: 'One page per component with its props table, live preview, simulator and an example from a real manifest. Generated from the schema.',
        indexCount: '{n} components',
        props: 'props',
        seeAllActions: 'See all actions',
        tryIt: 'Try it in the simulator',
        simNode: 'Node',
        interaction: { click: 'click', change: 'change', submit: 'submit' } as Record<string, string>,
    },
} as const;

export type KitStrings = (typeof S)['es'];

export function kitStrings(locale: Locale): KitStrings {
    return (S[locale] ?? S.es) as KitStrings;
}

export const fill = (text: string, params: Record<string, string | number>): string => text.replace(/\{(\w+)\}/g, (w, k: string) => (k in params ? String(params[k]) : w));
