'use client';

/**
 * Textos de interfaz de las herramientas de extensiones (playground y galeria). Diccionario local es/en
 * (no usa src/lib/i18n/messages). El idioma sale de `useI18n().locale`; cualquier otro cae a espanol.
 * Los textos con `{x}` son plantillas (se sustituyen con .replace).
 */
import { useI18n } from '@/components/I18nProvider';

const ES = {
    // acceso
    checkingAccess: 'Comprobando acceso...',
    unavailableTitle: 'Pagina no disponible',
    unavailableBody: 'Esta herramienta solo esta disponible para administradores.',
    backHome: 'Volver al inicio',
    // comunes
    theme: 'Tema de la vista previa',
    themeGeneric: 'Temas genericos',
    themeDomain: 'Empresa del dominio',
    themeFixtures: 'Paletas de empresa de prueba',
    toolbar: 'Opciones',
    cursorPos: 'Ln {line}, Col {col}',
    // validacion
    errors: 'Errores',
    deprecations: 'Avisos de obsolescencia',
    otherWarnings: 'Otros avisos',
    countLabel: '{n} problemas',
    countedAsErrors: '(modo estricto: cuentan como errores)',
    sourceJson: 'JSON',
    sourceManifest: 'Manifest',
    sourceUi: 'Interfaz (UI)',
    emptyText: 'Escribe o pega un manifest o un nodo de UI para validarlo.',
    noIssues: 'Sin errores ni avisos.',
    summary: '{errors} errores, {deprecations} avisos de obsolescencia, {warnings} otros avisos.',
    strictBlocking: 'Estricto: {n} problemas bloquearian la publicacion.',
    // playground
    playgroundTitle: 'Playground de extensiones',
    playgroundIntro: 'Pega un manifest completo (con mounts/overlays/state) o un nodo de UI suelto. La vista previa usa un backend simulado: nunca se llama al real.',
    goToGallery: 'Galeria de componentes',
    examples: 'Ejemplos',
    chooseExample: 'Elegir un ejemplo...',
    groupManifest: 'Manifest completo',
    groupLegacy: 'Formato antiguo (se migra)',
    groupComponents: 'Componentes',
    viewport: 'Tamano',
    vpMobile: 'Movil 375',
    vpTablet: 'Tablet 768',
    vpDesktop: 'Escritorio',
    strict: 'Estricto',
    editorSection: 'Editor del manifest o del nodo de UI',
    editor: 'Editor',
    format: 'Formatear',
    migrate: 'Migrar a formato nuevo',
    migrateHint: 'Sustituye el texto por el JSON migrado (COLUMN a STACK, sin className...)',
    editorLabel: 'Manifest o nodo de UI (JSON)',
    jsonErrorAt: 'JSON no valido en Ln {line}, Col {col}',
    kindManifest: 'Detectado: manifest completo',
    kindNode: 'Detectado: nodo de UI suelto',
    kindUnknown: 'No se reconoce como manifest ni como nodo de UI',
    validation: 'Validacion',
    preview: 'Vista previa',
    mount: 'Mount',
    resetPreview: 'Reiniciar vista previa',
    showingLastValid: 'El texto actual no se puede previsualizar: se muestra la ultima version valida.',
    brokenMount: 'Este mount tiene errores: se muestra el mismo estado de error que veria el usuario.',
    previewRegion: 'Vista previa de la extension',
    nothingToPreview: 'No hay nada que previsualizar todavia.',
    contextTitle: 'Contexto simulado (JSON)',
    contextHelp: 'Lo que recibe el mount como `context` (correo abierto, composer...).',
    scriptTitle: 'Respuestas simuladas del backend (JSON)',
    scriptHelp: 'Por funcion: { "result": ..., "delayMs": 300 } o { "error": "texto", "times": 1 }.',
    eventsTitle: 'Eventos',
    clearEvents: 'Limpiar eventos',
    noEvents: 'Sin eventos: las llamadas al backend simulado y al composer aparecen aqui.',
    kindBackend: 'backend',
    kindComposer: 'composer',
    stateTitle: 'Estado',
    loadedFromGallery: 'Ejemplo cargado desde la galeria.',
    migrated: 'Texto migrado al formato nuevo.',
    // galeria
    galleryTitle: 'Galeria de componentes de extensiones',
    galleryIntro: 'Catalogo vivo generado desde el schema de UI. Las extensiones solo eligen props semanticas; el tema decide colores, radio y fuente.',
    goToPlayground: 'Abrir el playground',
    search: 'Buscar',
    searchPlaceholder: 'Nombre, prop o descripcion...',
    category: 'Categoria',
    allCategories: 'Todas',
    allThemes: 'Ver en todos los temas',
    sections: 'Secciones',
    resultsCount: '{n} componentes',
    noResults: 'Ningun componente coincide con la busqueda.',
    acceptsChildren: 'acepta children',
    props: 'Props',
    examplesTitle: 'Ejemplos',
    noProps: 'Sin props.',
    colProp: 'Prop',
    colType: 'Tipo / valores',
    colDefault: 'Defecto',
    colDoc: 'Descripcion',
    required: 'obligatoria',
    copyJson: 'Copiar JSON',
    copied: 'JSON copiado',
    copyFailed: 'No se pudo copiar',
    storageFailed: 'No se pudo guardar el ejemplo para el playground',
    openInPlayground: 'Abrir en el playground',
    showJson: 'Ver JSON',
    categories: {
        layout: 'Layout', typography: 'Tipografia', action: 'Acciones', input: 'Entradas', data: 'Datos', navigation: 'Navegacion',
        feedback: 'Feedback', overlay: 'Overlays', chart: 'Graficos', logic: 'Logica',
    } as Record<string, string>,
    rulesTitle: 'Reglas de tematizacion',
    rulesIntro: 'Las extensiones no eligen colores ni estilos: declaran intencion (tone, variant, size...) y el kit la traduce a los tokens del tema activo (claro, oscuro o de empresa), con contraste garantizado.',
    rulesAllowed: 'Props semanticas permitidas',
    rulesRejected: 'Se rechaza',
    rulesRejectedKeys: 'Claves de estilo o internas, rechazadas por validateUi (y eliminadas con aviso al migrar):',
    rulesHtml: 'HTML en textos (script, style, iframe, img, form...): usa MARKDOWN o componentes.',
    rulesCssFn: 'Funciones CSS en valores (url(), var(), calc(), expression()) y javascript: en URLs.',
    rulesHex: 'Colores hexadecimales o con nombre para estilizar la interfaz. Solo COLOR_PICKER guarda un color, y es un dato del usuario.',
    rulesLimits: 'Limites: {nodes} nodos, {depth} niveles de profundidad, {kb} KB por UI.',
    rulesMigrate: 'El formato antiguo (COLUMN, className, variant "primary"...) se migra solo al cargar y genera avisos de obsolescencia.',
    actionsTitle: 'Acciones y expresiones',
    colAction: 'Accion',
    colRequired: 'Obligatorios',
    colFields: 'Campos',
    commonProps: 'Props de cualquier componente',
    expressionsTitle: 'Expresiones',
    expressionsIntro: 'Cualquier texto puede llevar expresiones con la sintaxis dollar + llaves. Son seguras: sin eval ni llamadas a funciones. Filtros con "valor | filtro:arg".',
    filters: 'Filtros disponibles',
    variables: 'Variables',
    varLoading: 'true mientras corre el CALL_BACKEND de esa clave (se pone solo).',
    varError: 'mensaje de error del ultimo CALL_BACKEND de esa clave (o null).',
    varRoots: 'datos del mount (correo, composer...) y estado local de la extension.',
    varAliases: 'alias segun el contexto: valor del control, resultado de la accion, fila, elemento de FOR_EACH/LIST, datos del FORM.',
};

export type ToolStrings = typeof ES;

const EN: ToolStrings = {
    checkingAccess: 'Checking access...',
    unavailableTitle: 'Page not available',
    unavailableBody: 'This tool is only available to administrators.',
    backHome: 'Back to home',
    theme: 'Preview theme',
    themeGeneric: 'Generic themes',
    themeDomain: 'Domain company',
    themeFixtures: 'Test company palettes',
    toolbar: 'Options',
    cursorPos: 'Ln {line}, Col {col}',
    errors: 'Errors',
    deprecations: 'Deprecation warnings',
    otherWarnings: 'Other warnings',
    countLabel: '{n} issues',
    countedAsErrors: '(strict mode: counted as errors)',
    sourceJson: 'JSON',
    sourceManifest: 'Manifest',
    sourceUi: 'Interface (UI)',
    emptyText: 'Type or paste a manifest or a UI node to validate it.',
    noIssues: 'No errors or warnings.',
    summary: '{errors} errors, {deprecations} deprecation warnings, {warnings} other warnings.',
    strictBlocking: 'Strict: {n} issues would block publishing.',
    playgroundTitle: 'Extensions playground',
    playgroundIntro: 'Paste a full manifest (with mounts/overlays/state) or a single UI node. The preview uses a simulated backend: the real one is never called.',
    goToGallery: 'Component gallery',
    examples: 'Examples',
    chooseExample: 'Choose an example...',
    groupManifest: 'Full manifest',
    groupLegacy: 'Legacy format (migrated)',
    groupComponents: 'Components',
    viewport: 'Size',
    vpMobile: 'Mobile 375',
    vpTablet: 'Tablet 768',
    vpDesktop: 'Desktop',
    strict: 'Strict',
    editorSection: 'Manifest or UI node editor',
    editor: 'Editor',
    format: 'Format',
    migrate: 'Migrate to new format',
    migrateHint: 'Replaces the text with the migrated JSON (COLUMN to STACK, no className...)',
    editorLabel: 'Manifest or UI node (JSON)',
    jsonErrorAt: 'Invalid JSON at Ln {line}, Col {col}',
    kindManifest: 'Detected: full manifest',
    kindNode: 'Detected: single UI node',
    kindUnknown: 'Not recognized as a manifest or a UI node',
    validation: 'Validation',
    preview: 'Preview',
    mount: 'Mount',
    resetPreview: 'Reset preview',
    showingLastValid: 'The current text cannot be previewed: showing the last valid version.',
    brokenMount: 'This mount has errors: the same error state the user would see is shown.',
    previewRegion: 'Extension preview',
    nothingToPreview: 'Nothing to preview yet.',
    contextTitle: 'Simulated context (JSON)',
    contextHelp: 'What the mount receives as `context` (open email, composer...).',
    scriptTitle: 'Simulated backend responses (JSON)',
    scriptHelp: 'Per function: { "result": ..., "delayMs": 300 } or { "error": "text", "times": 1 }.',
    eventsTitle: 'Events',
    clearEvents: 'Clear events',
    noEvents: 'No events: calls to the simulated backend and composer show up here.',
    kindBackend: 'backend',
    kindComposer: 'composer',
    stateTitle: 'State',
    loadedFromGallery: 'Example loaded from the gallery.',
    migrated: 'Text migrated to the new format.',
    galleryTitle: 'Extension component gallery',
    galleryIntro: 'Live catalog generated from the UI schema. Extensions only pick semantic props; the theme decides colors, radius and font.',
    goToPlayground: 'Open the playground',
    search: 'Search',
    searchPlaceholder: 'Name, prop or description...',
    category: 'Category',
    allCategories: 'All',
    allThemes: 'Show in all themes',
    sections: 'Sections',
    resultsCount: '{n} components',
    noResults: 'No component matches the search.',
    acceptsChildren: 'accepts children',
    props: 'Props',
    examplesTitle: 'Examples',
    noProps: 'No props.',
    colProp: 'Prop',
    colType: 'Type / values',
    colDefault: 'Default',
    colDoc: 'Description',
    required: 'required',
    copyJson: 'Copy JSON',
    copied: 'JSON copied',
    copyFailed: 'Could not copy',
    storageFailed: 'Could not save the example for the playground',
    openInPlayground: 'Open in playground',
    showJson: 'Show JSON',
    categories: {
        layout: 'Layout', typography: 'Typography', action: 'Actions', input: 'Inputs', data: 'Data', navigation: 'Navigation',
        feedback: 'Feedback', overlay: 'Overlays', chart: 'Charts', logic: 'Logic',
    },
    rulesTitle: 'Theming rules',
    rulesIntro: 'Extensions never pick colors or styles: they declare intent (tone, variant, size...) and the kit maps it to the active theme tokens (light, dark or company), with guaranteed contrast.',
    rulesAllowed: 'Allowed semantic props',
    rulesRejected: 'Rejected',
    rulesRejectedKeys: 'Style or internal keys, rejected by validateUi (and removed with a warning when migrating):',
    rulesHtml: 'HTML in texts (script, style, iframe, img, form...): use MARKDOWN or components.',
    rulesCssFn: 'CSS functions in values (url(), var(), calc(), expression()) and javascript: in URLs.',
    rulesHex: 'Hexadecimal or named colors to style the interface. Only COLOR_PICKER stores a color, and it is user data.',
    rulesLimits: 'Limits: {nodes} nodes, {depth} levels deep, {kb} KB per UI.',
    rulesMigrate: 'The legacy format (COLUMN, className, variant "primary"...) is migrated on load and produces deprecation warnings.',
    actionsTitle: 'Actions and expressions',
    colAction: 'Action',
    colRequired: 'Required',
    colFields: 'Fields',
    commonProps: 'Props of any component',
    expressionsTitle: 'Expressions',
    expressionsIntro: 'Any text can contain expressions using the dollar + braces syntax. They are safe: no eval or function calls. Filters use "value | filter:arg".',
    filters: 'Available filters',
    variables: 'Variables',
    varLoading: 'true while that key\'s CALL_BACKEND runs (set automatically).',
    varError: 'error message of that key\'s last CALL_BACKEND (or null).',
    varRoots: 'mount data (email, composer...) and the extension local state.',
    varAliases: 'aliases depending on context: control value, action result, row, FOR_EACH/LIST item, FORM data.',
};

export function getToolStrings(locale: string | undefined): ToolStrings {
    return locale === 'en' ? EN : ES;
}

export function useToolStrings(): ToolStrings {
    const { locale } = useI18n();
    return getToolStrings(locale);
}
