import type { DocPageContent } from '../types';

const page: DocPageContent = {
    es: [
        { t: 'p', text: 'La **consola de administración** (`/admin`) concentra en un solo lugar el control de usuarios, cuentas vinculadas, correo, marca, extensiones, seguridad, auditoría y retención de **tu** instancia. La antigua URL `/admin/dashboard` redirige a `/admin`.' },
        { t: 'h2', id: 'access', text: 'Quién puede entrar' },
        { t: 'ul', items: [
            '**Gestor del dominio**: el manager del backend que es *dueño* del dominio de esta instancia (`TOP_DOMAIN`). Entra por `/admin/login`. Un manager ajeno (el alta de managers es abierta) recibe 403.',
            '**Usuario administrador**: un usuario de la app con su correo en `ADMIN_EMAILS` **y** sesión con MFA (salvo `MFA_ENFORCE_ADMIN=false`).',
            'Sin sesión se responde 401; con sesión pero sin rol, propiedad o MFA, 403. Todas las rutas `/api/admin/**` pasan por el mismo guardia (`requireAdmin`), limitan la tasa de peticiones y auditan las acciones sensibles.',
        ] },
        { t: 'callout', kind: 'note', title: 'El rol de administrador no se edita desde la consola', text: 'Ser administrador depende de la variable `ADMIN_EMAILS` (entorno del servidor), a propósito: así nadie puede escalar privilegios desde la interfaz o la base de datos. La ficha de usuario muestra el rol en solo lectura; para cambiarlo edita la variable y redespliega.' },
        { t: 'h2', id: 'layout', text: 'Navegación' },
        { t: 'ul', items: [
            '**Barra lateral** por secciones (en móvil, un cajón) y **migas de pan**.',
            '**Búsqueda global**: pulsa `/` (o Ctrl/Cmd+K) y escribe para saltar a un usuario, una extensión o un ajuste (contraseña, MFA, clave de firma, lista de supresión, DNS...). Flechas para moverte, Intro para abrir, Esc para cerrar.',
            '**Cabecera**: dominio activo, estado del sistema (base de datos, backend compartido, límite de peticiones) y menú del perfil (idioma, volver al correo, cerrar sesión).',
            'Las pantallas con cambios sin guardar piden confirmación antes de salir.',
        ] },
        { t: 'h2', id: 'sections', text: 'Secciones' },
        { t: 'table', head: ['Sección', 'Ruta', 'Qué hace'], rows: [
            ['Resumen', '`/admin`', 'Usuarios activos y altas, correo enviado/recibido en 24 h, rebotes y quejas, cola de Elixir, almacenamiento de adjuntos, extensiones con errores, MFA de administradores y aviso de modo heredado'],
            ['Usuarios', '`/admin/users`', 'Tabla con búsqueda, filtros (estado, rol, MFA, cuenta Google), orden, paginación y selección masiva; ficha con sesiones activas (revocar una o todas), restablecer MFA, deshabilitar/habilitar, contraseña temporal o cambio forzado, alta de usuarios y exportación CSV'],
            ['Cuentas vinculadas', '`/admin/accounts`', 'Cuentas OAuth por usuario con estado del token (sin mostrarlo), integraciones que la usan, desvincular y pedir reconexión'],
            ['Correo', '`/admin/mail`', 'Métricas agregadas (nunca contenido), cuotas por hora, lista de supresión (ver/quitar), cola de programados, estado de los webhooks y salud DNS (SPF, DKIM, DMARC)'],
            ['Dominio y marca', '`/admin/domain`', 'Editor de tema y landing'],
            ['Extensiones', '`/admin/extensions`', 'Catálogo, instalar/desinstalar, activar/desactivar, versión, permisos, credenciales, estado y último error'],
            ['Seguridad', '`/admin/security`', 'Comprobaciones de MFA, sesión, configuración presente y eventos de seguridad recientes'],
            ['Auditoría', '`/admin/audit`', 'Visor de eventos con filtros, paginación y exportación CSV; valores enmascarados'],
            ['Retención y almacenamiento', '`/admin/retention`', 'Políticas editables (spam, papelera, raw, auditoría), simular o ejecutar ahora y uso de almacenamiento'],
            ['Spam y remitentes', '`/admin/spam`', 'Nivel de filtrado (presets, umbral, acción por banda, pesos por familia, vista previa), listas de bloqueados y permitidos con CSV, correos externos (política y whitelist), registro de decisiones sin contenido, probador de señales y estadísticas. Detalle en [Filtro de spam y remitentes](/docs/spam)'],
            ['Mi perfil', '`/admin/profile`', 'Contraseña (12+), MFA y códigos de recuperación, sesiones propias, clave de firma del dominio y preferencias (idioma, tema, densidad)'],
        ] },
        { t: 'h2', id: 'users', text: 'Usuarios: cómo se modela el estado' },
        { t: 'p', text: 'La tabla `User` no cambia. El estado administrativo vive en tablas aditivas que crea `npm run db:ensure`: `UserAdminState` (deshabilitado, cambio de contraseña pendiente, último acceso), `UserSession` (registro de sesiones emitidas, para poder listarlas) y `AdminSetting` (políticas editables). Un usuario **deshabilitado** no puede iniciar sesión y sus sesiones vigentes dejan de valer (se sube `tokenVersion`).' },
        { t: 'ul', items: [
            '**Restablecer MFA**: exige escribir el correo del usuario; cierra sus sesiones y queda auditado. Si es administrador deberá enrolar MFA de nuevo en su próximo acceso.',
            '**Contraseña**: no se muestra ninguna contraseña existente. "Contraseña temporal" genera una, la muestra **una sola vez**, marca el cambio obligatorio y cierra sesiones. "Forzar cambio" solo marca el cambio: el login redirige a `/security?force=1`.',
            '**Límite**: no hay correo de recuperación de contraseña en el sistema, por eso no existe el enlace de un solo uso.',
        ] },
        { t: 'h2', id: 'privacy', text: 'Privacidad' },
        { t: 'p', text: 'La consola nunca muestra asuntos, cuerpos ni adjuntos. Correo solo expone conteos y metadatos; la única lista con direcciones es la de supresión (hace falta para poder quitarlas). Las credenciales de extensiones, los tokens OAuth y los hashes nunca salen del servidor.' },
        { t: 'h2', id: 'api', text: 'API de la consola' },
        { t: 'table', head: ['Ruta', 'Uso'], rows: [
            ['`GET /api/admin/me` · `system` · `search` · `overview`', 'Armazón: quién eres, estado del sistema, búsqueda de usuarios, tarjetas del resumen'],
            ['`/api/admin/users` (+ `[id]`, `bulk`, `export`)', 'Listar/crear, detalle, deshabilitar, MFA, sesiones, contraseña, acciones masivas y CSV'],
            ['`/api/admin/accounts`', 'Cuentas vinculadas'],
            ['`/api/admin/mail/*`', 'Métricas, supresión, webhooks, DNS'],
            ['`/api/admin/extensions/*`', 'Catálogo, instaladas, activar, orden, estado, prueba, credenciales'],
            ['`/api/admin/audit` (+ `export`) · `security/status`', 'Auditoría y seguridad'],
            ['`/api/admin/retention/*`', 'Políticas, ejecución y almacenamiento (`/api/admin/retention` sigue sirviendo al cron con `CRON_SECRET`)'],
            ['`/api/admin/profile/*` · `domain-key`', 'Perfil del administrador y clave de firma'],
        ] },
        { t: 'p', text: 'Todas devuelven `Cache-Control: no-store`, validan con zod, acotan la paginación (máx. 100 por página) y usan SQL parametrizado tolerante a tablas ausentes. Detalles de la firma de dominio en [API del backend y firma](/docs/api-backend).' },
        { t: 'h2', id: 'limits', text: 'Límites conocidos' },
        { t: 'ul', items: [
            'El estado del token de una cuenta vinculada se **deriva** de las fechas y de la presencia de tokens; no se pregunta al proveedor (no se sabe si Google lo revocó hasta usarlo).',
            'Las sesiones solo se listan desde que se despliega el registro `UserSession`: las anteriores siguen válidas pero no aparecen.',
            'El cambio de contraseña forzado se aplica en el redirect del login, no con un bloqueo de servidor en cada ruta.',
            'Sin clave de firma registrada la instancia funciona en **modo heredado** (soportado, con privilegios reducidos en el backend); regístrala en Mi perfil para pasar a peticiones firmadas.',
        ] },
    ],
    en: [
        { t: 'p', text: 'The **administration console** (`/admin`) brings user, linked-account, mail, brand, extension, security, audit and retention control for **your** instance into one place. The old `/admin/dashboard` URL redirects to `/admin`.' },
        { t: 'h2', id: 'access', text: 'Who can sign in' },
        { t: 'ul', items: [
            '**Domain manager**: the backend manager who *owns* this instance\'s domain (`TOP_DOMAIN`). Sign in at `/admin/login`. A foreign manager (manager sign-up is open) gets 403.',
            '**Admin user**: an app user whose email is in `ADMIN_EMAILS` **and** whose session has MFA (unless `MFA_ENFORCE_ADMIN=false`).',
            'No session returns 401; a session without role, ownership or MFA returns 403. Every `/api/admin/**` route goes through the same guard (`requireAdmin`), is rate limited and audits sensitive actions.',
        ] },
        { t: 'callout', kind: 'note', title: 'The admin role is not editable from the console', text: 'Being an administrator depends on the `ADMIN_EMAILS` variable (server environment) on purpose: nobody can escalate privileges from the UI or the database. The user sheet shows the role read-only; to change it edit the variable and redeploy.' },
        { t: 'h2', id: 'layout', text: 'Navigation' },
        { t: 'ul', items: [
            '**Sidebar** by section (a drawer on mobile) and **breadcrumbs**.',
            '**Global search**: press `/` (or Ctrl/Cmd+K) and type to jump to a user, an extension or a setting (password, MFA, signing key, suppression list, DNS...). Arrows to move, Enter to open, Esc to close.',
            '**Header**: active domain, system status (database, shared backend, rate limiting) and the profile menu (language, back to mail, sign out).',
            'Screens with unsaved changes ask for confirmation before leaving.',
        ] },
        { t: 'h2', id: 'sections', text: 'Sections' },
        { t: 'table', head: ['Section', 'Route', 'What it does'], rows: [
            ['Overview', '`/admin`', 'Active users and sign-ups, mail sent/received in 24 h, bounces and complaints, Elixir queue, attachment storage, extensions with errors, admin MFA and the legacy-mode notice'],
            ['Users', '`/admin/users`', 'Table with search, filters (status, role, MFA, Google account), sorting, pagination and bulk selection; sheet with active sessions (revoke one or all), reset MFA, disable/enable, temporary password or forced change, user creation and CSV export'],
            ['Linked accounts', '`/admin/accounts`', 'OAuth accounts per user with token status (never shown), the integrations that use it, unlink and request reconnection'],
            ['Mail', '`/admin/mail`', 'Aggregate metrics (never content), hourly quotas, suppression list (view/remove), scheduled queue, webhook status and DNS health (SPF, DKIM, DMARC)'],
            ['Domain and brand', '`/admin/domain`', 'Theme and landing editor'],
            ['Extensions', '`/admin/extensions`', 'Catalog, install/uninstall, enable/disable, version, permissions, credentials, status and last error'],
            ['Security', '`/admin/security`', 'MFA, session and configuration checks, and recent security events'],
            ['Audit log', '`/admin/audit`', 'Event viewer with filters, pagination and CSV export; values masked'],
            ['Retention and storage', '`/admin/retention`', 'Editable policies (spam, trash, raw, audit), dry run or run now, and storage usage'],
            ['Spam and senders', '`/admin/spam`', 'Filtering level (presets, threshold, action per band, per-family weights, preview), block and allow lists with CSV, external mail (policy and whitelist), content-free decision log, signal tester and statistics. See [Spam filter and senders](/docs/spam)'],
            ['My profile', '`/admin/profile`', 'Password (12+), MFA and recovery codes, own sessions, domain signing key and preferences (language, theme, density)'],
        ] },
        { t: 'h2', id: 'users', text: 'Users: how state is modelled' },
        { t: 'p', text: 'The `User` table does not change. Administrative state lives in additive tables created by `npm run db:ensure`: `UserAdminState` (disabled, pending password change, last sign-in), `UserSession` (registry of issued sessions, so they can be listed) and `AdminSetting` (editable policies). A **disabled** user cannot sign in and their current sessions stop working (`tokenVersion` is bumped).' },
        { t: 'ul', items: [
            '**Reset MFA**: requires typing the user\'s email; closes their sessions and is audited. If they are an administrator they must enrol MFA again at their next sign-in.',
            '**Password**: no existing password is ever shown. "Temporary password" generates one, shows it **once**, marks the change as mandatory and closes sessions. "Force change" only marks the change: login redirects to `/security?force=1`.',
            '**Limit**: the system has no password-recovery email, so there is no one-time link.',
        ] },
        { t: 'h2', id: 'privacy', text: 'Privacy' },
        { t: 'p', text: 'The console never shows subjects, bodies or attachments. Mail only exposes counts and metadata; the only list with addresses is the suppression list (needed to remove them). Extension credentials, OAuth tokens and hashes never leave the server.' },
        { t: 'h2', id: 'api', text: 'Console API' },
        { t: 'table', head: ['Route', 'Use'], rows: [
            ['`GET /api/admin/me` · `system` · `search` · `overview`', 'Shell: who you are, system status, user search, overview cards'],
            ['`/api/admin/users` (+ `[id]`, `bulk`, `export`)', 'List/create, detail, disable, MFA, sessions, password, bulk actions and CSV'],
            ['`/api/admin/accounts`', 'Linked accounts'],
            ['`/api/admin/mail/*`', 'Metrics, suppression, webhooks, DNS'],
            ['`/api/admin/extensions/*`', 'Catalog, installed, toggle, order, status, test, credentials'],
            ['`/api/admin/audit` (+ `export`) · `security/status`', 'Audit and security'],
            ['`/api/admin/retention/*`', 'Policies, run and storage (`/api/admin/retention` keeps serving the cron with `CRON_SECRET`)'],
            ['`/api/admin/profile/*` · `domain-key`', 'Admin profile and signing key'],
        ] },
        { t: 'p', text: 'All of them return `Cache-Control: no-store`, validate with zod, bound pagination (max 100 per page) and use parameterised SQL tolerant of missing tables. Domain-signing details are in [Backend API and signing](/docs/api-backend).' },
        { t: 'h2', id: 'limits', text: 'Known limits' },
        { t: 'ul', items: [
            'A linked account\'s token status is **derived** from dates and token presence; the provider is not asked (you cannot know Google revoked it until it is used).',
            'Sessions are only listed from the moment the `UserSession` registry is deployed: earlier ones stay valid but do not appear.',
            'The forced password change is applied in the login redirect, not with a server-side block on every route.',
            'Without a registered signing key the instance works in **legacy mode** (supported, with reduced privileges in the backend); register one in My profile to move to signed requests.',
        ] },
    ],
};

export default page;
