import type { DocPageContent } from '../types';

const page: DocPageContent = {
    es: [
        { t: 'p', text: 'BloomX se compone de **N frontends** (una app Next.js por empresa o dominio) y **un backend compartido** multi-tenant. Cada frontend es dueño de sus usuarios, correos y base de datos; el backend compartido aporta el registro de dominios, la configuración de marca, el catálogo y la ejecución de extensiones, y los pagos.' },
        { t: 'h2', id: 'overview', text: 'Visión general' },
        { t: 'diagram', id: 'architecture', caption: 'N frontends firman sus peticiones con su clave Ed25519; un solo backend las verifica con la clave pública registrada de cada dominio.' },
        { t: 'ul', items: [
            '**Frontend** (`bloomx`): interfaz, API propia (`/api/*`), base de datos PostgreSQL propia (`DATABASE_URL`), almacenamiento de adjuntos y el envío/recepción por Resend.',
            '**Backend compartido** (`bloomx-backend`): `GET /api/config` (marca y extensiones del dominio), registro (`/api/auth/register`, `register-domain`, `verify-domain`), instalación de extensiones, ejecución sandboxed de extensiones (`/api/extension/execute`, `/api/extension/hooks`), pagos y el almacén público de logos.',
            '**Servicios externos**: PostgreSQL (por ejemplo Neon), S3/B2/R2, Resend, Upstash Redis (opcional para rate limit distribuido) y, si los activas, Google/Zoom/Slack/Notion/HubSpot/Trello por OAuth.',
        ] },
        { t: 'h2', id: 'multi-tenant', text: 'Backend compartido y multi-tenant' },
        { t: 'ul', items: [
            '**Alta abierta**: cualquiera puede registrar un manager (`POST /api/auth/register`) o un dominio (`POST /api/auth/register-domain` + `POST /api/auth/verify-domain` con un OTP de 6 dígitos enviado por correo; con límites de intentos). Para un despliegue privado desactiva el alta con `ALLOW_OPEN_REGISTRATION=false` en el backend.',
            '**CORS `*` intencional**: el backend responde siempre `Access-Control-Allow-Origin: *` y **sin credenciales**. No es un agujero: la autenticación no usa cookies del navegador sino firmas por dominio (las cookies de manager de Lucia solo las usa el panel de gestión de dominio). No existe variable para restringirlo.',
            '**Un dominio = un tenant**: el tenant se identifica por la cabecera `X-BloomX-Domain`. Cada tenant tiene su marca (`Domain.theme`), sus extensiones instaladas, sus credenciales de extensión cifradas y, opcionalmente, su clave pública Ed25519.',
        ] },
        { t: 'h2', id: 'trust', text: 'Confianza sin secretos globales' },
        { t: 'p', text: 'Frontend y backend **no comparten ningún secreto**. Esto permite que cualquier empresa levante su frontend sin coordinar claves con el operador del backend:' },
        { t: 'table', head: ['Necesidad', 'Mecanismo', 'Detalle'], rows: [
            ['Sesión de usuario', '`NEXTAUTH_SECRET` **propio** de cada frontend', 'No se comparte con el backend; el backend ya no valida JWT del frontend.'],
            ['Autenticación interna servidor-a-servidor del frontend (webhook → process-attachments, cron)', 'Clave **derivada por HKDF-SHA256** de `NEXTAUTH_SECRET`', 'info `bloomx-internal-v1`, cabecera `x-internal-secret`. Solo vale dentro de esa instancia. `INTERNAL_SECRET` solo se acepta si lo defines (compat).'],
            ['Frontend → backend', 'Firma **Ed25519 por dominio**', '`BLOOMX_DOMAIN_PRIVATE_KEY` en el frontend; la clave pública se registra en el backend (`Domain.signingPublicKey`). Ver [protocolo de firma](/docs/api-backend#signing).'],
            ['Backend → frontend (puente `services.mail`, Organizer)', '`executionGrant` firmada por la **instancia**', 'El backend no firma nada: reenvía la concesión (120 s, extensión + versión + usuario + permisos) que la instancia firmó con su `BLOOMX_DOMAIN_PRIVATE_KEY` y esta la verifica con su propia clave. Legado deprecado: firma del backend (`BACKEND_SIGNING_PRIVATE_KEY`), apagable con `BLOOMX_ACCEPT_BACKEND_SIGNATURE=false`.'],
            ['Dominio que aún no tiene clave', '**Modo legado**', 'Cabeceras `x-bloomx-domain`, `x-user-id`, `x-user-email` sin firma, con rate limit y **sin services privilegiados** (`services.mail`, `EMAIL_RECEIVED`, `CRON`); las extensiones siguen recibiendo sus credenciales (dominio, heredadas o del servidor) y cada ejecución con credenciales se audita; el backend responde `X-BloomX-Auth: legacy`.'],
        ] },
        { t: 'callout', kind: 'note', title: 'Qué ya no hace falta configurar', text: '`INTERNAL_SECRET`, `EXTENSION_HOOKS_SECRET` y `FRONTEND_INTERNAL_URL` ya no se usan entre frontend y backend. Tampoco hay `NEXTAUTH_SECRET` en el backend. Si los ves en instrucciones antiguas, ignóralos.' },
        { t: 'h3', id: 'signed-vs-legacy', text: 'Modo firmado frente a modo legado' },
        { t: 'table', head: ['', 'Firmado (dominio con clave)', 'Legado (sin clave)'], rows: [
            ['Autenticación', 'Firma Ed25519 obligatoria (401 si falta o es inválida)', 'Cabeceras sin firma'],
            ['`execute` de extensiones instaladas', 'Sí', 'Sí (con las mismas credenciales; auditado)'],
            ['`EMAIL_PRE_SEND`', 'Sí', 'Sí'],
            ['`EMAIL_RECEIVED` y `CRON`', 'Sí (los de su dominio)', 'No (403)'],
            ['Credenciales de extensiones', 'Sí', 'Sí (mismo orden: dominio, heredadas, servidor)'],
            ['`services.mail` (puente firmado)', 'Sí', 'No'],
            ['Rate limit', 'Por endpoint', '60/min por IP y dominio; 240/min por dominio'],
        ] },
        { t: 'h2', id: 'mail-flow', text: 'Flujo del correo' },
        { t: 'diagram', id: 'mail-flow', caption: 'Entrada por webhook de Resend, salida por la API de Resend. BloomX no habla IMAP/SMTP.' },
        { t: 'ul', items: [
            '**Entrante**: Resend recibe (registro MX de tu dominio) y llama a `POST /api/webhooks/resend`. Si defines `WEBHOOK_SECRET` se exige firma Svix válida; sin él se acepta sin firma (cada organizador decide). El frontend guarda el correo en PostgreSQL y los adjuntos en el almacenamiento, procesa adjuntos en segundo plano y notifica a la interfaz por SSE.',
            '**Saliente**: la interfaz llama a `POST /api/emails`, que valida propiedad del remitente, límites y adjuntos, ejecuta el hook `EMAIL_PRE_SEND` (DLP) contra el backend y envía por Resend con `Idempotency-Key`.',
            '**Eventos**: rebotes y quejas llegan a `POST /api/webhooks/resend-events` (con `RESEND_WEBHOOK_SECRET` opcional) y alimentan la lista de supresión.',
            'Gmail/Outlook/IMAP **no** están soportados como buzones: el correo entra por Resend. Sí existe sincronización de calendario y contactos de Google.',
        ] },
        { t: 'h2', id: 'data', text: 'Datos y estado' },
        { t: 'ul', items: [
            '**Frontend**: PostgreSQL vía Prisma más SQL crudo. El esquema se garantiza con `npm run db:ensure` (aditivo, con advisory locks). Ver [Operación](/docs/operations#migrations).',
            '**Backend**: PostgreSQL propio (dominios, managers, extensiones, instalaciones, transacciones). Su esquema se aplica con `npm run prisma:push`.',
            '**Adjuntos y activos**: S3-compatible; en el frontend `S3_*`, en el backend `B2_*`. Se sirven mediante URLs firmadas. Ver [Almacenamiento](/docs/storage).',
            '**Estado efímero**: nonces anti-replay y rate limit en memoria por instancia (el rate limit del frontend puede ser global con Upstash).',
        ] },
        { t: 'h2', id: 'security-boundaries', text: 'Fronteras de seguridad' },
        { t: 'ul', items: [
            'El navegador solo habla con **su** frontend; el frontend firma cuando habla con el backend.',
            'Las extensiones corren en el backend, dentro de un sandbox `worker_threads`, con red filtrada (`safe-fetch`). No es una frontera fuerte: ver [Extensiones](/docs/expansions#sandbox).',
            'Los secretos de terceros (claves de Resend por dominio, credenciales de extensiones) se cifran en el backend con `DATA_ENCRYPTION_KEY` y nunca vuelven al navegador.',
            'Detalle completo en [Seguridad](/docs/security).',
        ] },
    ],
    en: [
        { t: 'p', text: 'BloomX is made of **N frontends** (one Next.js app per company or domain) and **one shared multi-tenant backend**. Each frontend owns its users, mail and database; the shared backend provides domain registration, brand configuration, the extension catalogue and execution, and payments.' },
        { t: 'h2', id: 'overview', text: 'Overview' },
        { t: 'diagram', id: 'architecture', caption: 'N frontends sign their requests with their own Ed25519 key; a single backend verifies them with each domain\'s registered public key.' },
        { t: 'ul', items: [
            '**Frontend** (`bloomx`): UI, its own API (`/api/*`), its own PostgreSQL database (`DATABASE_URL`), attachment storage and Resend send/receive.',
            '**Shared backend** (`bloomx-backend`): `GET /api/config` (domain brand and extensions), sign-up (`/api/auth/register`, `register-domain`, `verify-domain`), extension installation, sandboxed extension execution (`/api/extension/execute`, `/api/extension/hooks`), payments and the public logo store.',
            '**External services**: PostgreSQL (for example Neon), S3/B2/R2, Resend, Upstash Redis (optional, for distributed rate limiting) and, if you enable them, Google/Zoom/Slack/Notion/HubSpot/Trello through OAuth.',
        ] },
        { t: 'h2', id: 'multi-tenant', text: 'Shared, multi-tenant backend' },
        { t: 'ul', items: [
            '**Open sign-up**: anyone can register a manager (`POST /api/auth/register`) or a domain (`POST /api/auth/register-domain` + `POST /api/auth/verify-domain` with a 6-digit OTP sent by email; attempts are rate-limited). For a private deployment turn sign-up off with `ALLOW_OPEN_REGISTRATION=false` on the backend.',
            '**Intentional CORS `*`**: the backend always answers `Access-Control-Allow-Origin: *` and **without credentials**. This is not a hole: authentication does not use browser cookies but per-domain signatures (the Lucia manager cookies are only used by the domain-management panel). There is no variable to restrict it.',
            '**One domain = one tenant**: the tenant is identified by the `X-BloomX-Domain` header. Each tenant has its brand (`Domain.theme`), its installed extensions, its encrypted extension credentials and, optionally, its Ed25519 public key.',
        ] },
        { t: 'h2', id: 'trust', text: 'Trust without global secrets' },
        { t: 'p', text: 'Frontend and backend **share no secret**. Any company can stand up its frontend without coordinating keys with the backend operator:' },
        { t: 'table', head: ['Need', 'Mechanism', 'Detail'], rows: [
            ['User session', 'Each frontend\'s **own** `NEXTAUTH_SECRET`', 'Not shared with the backend; the backend no longer validates frontend JWTs.'],
            ['Frontend-internal server-to-server auth (webhook → process-attachments, cron)', 'Key **derived by HKDF-SHA256** from `NEXTAUTH_SECRET`', 'info `bloomx-internal-v1`, header `x-internal-secret`. Only valid inside that instance. `INTERNAL_SECRET` is only accepted if you define it (compat).'],
            ['Frontend → backend', '**Per-domain Ed25519** signature', '`BLOOMX_DOMAIN_PRIVATE_KEY` on the frontend; the public key is registered on the backend (`Domain.signingPublicKey`). See the [signing protocol](/docs/api-backend#signing).'],
            ['Backend → frontend (`services.mail` bridge, Organizer)', '`executionGrant` signed by the **instance**', 'The backend signs nothing: it forwards the grant (120 s, extension + version + user + permissions) the instance signed with its `BLOOMX_DOMAIN_PRIVATE_KEY`, and the instance verifies it with its own key. Deprecated legacy: backend signature (`BACKEND_SIGNING_PRIVATE_KEY`), switch off with `BLOOMX_ACCEPT_BACKEND_SIGNATURE=false`.'],
            ['Domain without a key yet', '**Legacy mode**', 'Headers `x-bloomx-domain`, `x-user-id`, `x-user-email` without signature, rate-limited and with **no privileged services** (`services.mail`, `EMAIL_RECEIVED`, `CRON`); extensions still receive their credentials (domain, legacy or server) and every run with credentials is audited; the backend answers `X-BloomX-Auth: legacy`.'],
        ] },
        { t: 'callout', kind: 'note', title: 'What you no longer configure', text: '`INTERNAL_SECRET`, `EXTENSION_HOOKS_SECRET` and `FRONTEND_INTERNAL_URL` are no longer used between frontend and backend, and there is no `NEXTAUTH_SECRET` on the backend. Ignore them if you see them in old instructions.' },
        { t: 'h3', id: 'signed-vs-legacy', text: 'Signed mode versus legacy mode' },
        { t: 'table', head: ['', 'Signed (domain with key)', 'Legacy (no key)'], rows: [
            ['Authentication', 'Ed25519 signature required (401 if missing or invalid)', 'Unsigned headers'],
            ['`execute` of installed extensions', 'Yes', 'Yes (same credentials; audited)'],
            ['`EMAIL_PRE_SEND`', 'Yes', 'Yes'],
            ['`EMAIL_RECEIVED` and `CRON`', 'Yes (their own domain)', 'No (403)'],
            ['Extension credentials', 'Yes', 'Yes (same order: domain, legacy, server)'],
            ['`services.mail` (signed bridge)', 'Yes', 'No'],
            ['Rate limit', 'Per endpoint', '60/min per IP and domain; 240/min per domain'],
        ] },
        { t: 'h2', id: 'mail-flow', text: 'Mail flow' },
        { t: 'diagram', id: 'mail-flow', caption: 'Inbound through the Resend webhook, outbound through the Resend API. BloomX does not speak IMAP/SMTP.' },
        { t: 'ul', items: [
            '**Inbound**: Resend receives (your domain\'s MX record) and calls `POST /api/webhooks/resend`. If you set `WEBHOOK_SECRET` a valid Svix signature is required; without it the request is accepted unsigned (each organiser decides). The frontend stores the message in PostgreSQL and attachments in storage, processes attachments in the background and notifies the UI over SSE.',
            '**Outbound**: the UI calls `POST /api/emails`, which validates sender ownership, limits and attachments, runs the `EMAIL_PRE_SEND` hook (DLP) against the backend and sends through Resend with an `Idempotency-Key`.',
            '**Events**: bounces and complaints arrive at `POST /api/webhooks/resend-events` (optional `RESEND_WEBHOOK_SECRET`) and feed the suppression list.',
            'Gmail/Outlook/IMAP are **not** supported as mailboxes: mail enters through Resend. Google calendar and contacts sync does exist.',
        ] },
        { t: 'h2', id: 'data', text: 'Data and state' },
        { t: 'ul', items: [
            '**Frontend**: PostgreSQL through Prisma plus raw SQL. The schema is guaranteed by `npm run db:ensure` (additive, with advisory locks). See [Operations](/docs/operations#migrations).',
            '**Backend**: its own PostgreSQL (domains, managers, extensions, installations, transactions). Its schema is applied with `npm run prisma:push`.',
            '**Attachments and assets**: S3-compatible; `S3_*` on the frontend, `B2_*` on the backend. Served through signed URLs. See [Storage](/docs/storage).',
            '**Ephemeral state**: anti-replay nonces and rate limits in per-instance memory (the frontend rate limit can be global with Upstash).',
        ] },
        { t: 'h2', id: 'security-boundaries', text: 'Security boundaries' },
        { t: 'ul', items: [
            'The browser only talks to **its** frontend; the frontend signs when it talks to the backend.',
            'Extensions run on the backend inside a `worker_threads` sandbox with filtered network (`safe-fetch`). It is not a strong boundary: see [Extensions](/docs/expansions#sandbox).',
            'Third-party secrets (per-domain Resend keys, extension credentials) are encrypted on the backend with `DATA_ENCRYPTION_KEY` and never returned to the browser.',
            'Full detail in [Security](/docs/security).',
        ] },
    ],
};

export default page;
