import type { DocPageContent } from '../types';

const ruleEx = `POST /api/rules
{
  "name": "Facturas a Finanzas",
  "enabled": true,
  "priority": 0,
  "conditions": {
    "match": "any",
    "items": [
      { "field": "from", "op": "contains", "value": "facturacion@" },
      { "field": "subject", "op": "regex", "value": "factura|invoice" },
      { "field": "hasAttachment", "value": true }
    ]
  },
  "actions": [ { "type": "addLabel", "labelId": "<id-de-etiqueta>" }, { "type": "markRead" } ],
  "stopProcessing": false
}`;

const ruleExEn = ruleEx.replace('Facturas a Finanzas', 'Invoices to Finance').replace('<id-de-etiqueta>', '<label-id>');

const ruleV2Ex = `POST /api/rules
{
  "name": "Facturas de proveedores",
  "labelId": "<id-de-la-etiqueta-carpeta-Facturas>",
  "conditions": {
    "v": 2,
    "root": { "type": "group", "op": "and", "children": [
      { "field": "fromDomain", "op": "in", "values": ["empresa.com", "proveedor.es"], "subdomains": true },
      { "field": "subject", "op": "containsAny", "values": ["factura", "invoice"], "wholeWord": true },
      { "field": "attachmentType", "op": "equals", "value": "pdf" },
      { "type": "group", "op": "not", "children": [
        { "field": "header", "name": "auto-submitted", "op": "exists" }
      ] }
    ] }
  },
  "actions": [ { "type": "markRead" } ],
  "stopProcessing": false
}`;

const ruleV2ExEn = ruleV2Ex.replace('Facturas de proveedores', 'Supplier invoices').replace('<id-de-la-etiqueta-carpeta-Facturas>', '<id-of-the-Invoices-folder-label>');

const searchEx = `from:ana subject:"informe mensual" has:attachment is:unread label:"Mis facturas" contrato`;

const page: DocPageContent = {
    es: [
        { t: 'p', text: 'Referencia de lo que el correo hace **hoy**. Donde una función no existe o solo existe a medias, se dice expresamente.' },
        { t: 'h2', id: 'rules', text: 'Reglas de correo' },
        { t: 'ul', items: [
            'Una regla tiene `name` (1–80), `enabled`, `priority` (entero −1000..1000; **menor número = se evalúa antes**), `conditions` (esquema **v2**, ver "Motor de condiciones v2"; el formato v1 `{match, items}` o un arreglo simple se sigue leyendo y se guarda como v2), entre 1 y **30 condiciones** en grupos de hasta **4 niveles**, entre 1 y 12 acciones, `stopProcessing` y, opcionalmente, `labelId` (regla de "Asignar automáticamente" de una etiqueta). Máximo **100 reglas** por usuario.',
            '**Condiciones**: árbol de grupos `and` / `or` / `not` (*ninguna* de las hijas) con hojas tipadas; ver "Motor de condiciones v2". Una regla sin condiciones nunca coincide.',
            '**Acciones**: `addLabel`, `removeLabel`, `moveToLabelFolder {labelId}`, `markRead`, `star`, `archive` (saltar Entrada), `moveToFolder {folder}` (`inbox|archive|trash|spam`), `delete` (a la papelera: **borrar definitivamente no existe como acción**), `markSpam`, `snooze {hours}` (1–8760), `forwardTo {address}` (desactivado por defecto: requiere `RULES_FORWARD_ENABLED=true`, solo a direcciones verificadas del propio usuario, máx. 30 por hora y sin reenviar correos automáticos) y `stopProcessing`. Sobre una misma etiqueta gana la última acción en orden de prioridad.',
            'Cada regla se evalúa una vez contra el estado inicial del correo: las acciones no disparan otras reglas (sin cadenas ni bucles). Si varias reglas fijan carpeta, gana la de mayor prioridad. `stopProcessing: true` corta el procesamiento.',
            '**Regex de usuario**: máx. 200 caracteres; se rechazan referencias hacia atrás, lookahead/lookbehind, cuantificadores anidados y alternancias dentro de grupos cuantificados (protección contra ReDoS).',
            '**Cuándo se aplican**: al recibir un correo (con cabeceras, adjuntos y contactos reales); con "Aplicar a correos existentes" (páginas de 200 con progreso, vista previa del número de coincidencias y **Deshacer** por lote; solo `inbox` y `archive`, nunca reenvía); y en el cron (catch-up de los últimos 2 días, lotes de 200). El cuerpo completo se lee del almacenamiento solo si la regla usa `body`/`bodyHtml`. Una regla no saca de `spam` un correo que ya llegó como spam por cabeceras.',
            'Si las tablas `Rule`/`RuleRun` no existen, la lectura devuelve `[]` y la escritura responde 503 (ejecuta `npm run db:ensure`).',
            'Se gestionan en Ajustes → Reglas (arrastra o usa los botones para cambiar la prioridad) y, por etiqueta, en Ajustes → Etiquetas → "Asignar automáticamente". Es el mismo motor y la misma tabla.',
        ] },
        { t: 'code', lang: 'json', title: 'Ejemplo de regla', code: ruleEx },
        { t: 'h2', id: 'labels', text: 'Etiquetas (labels)' },
        { t: 'ul', items: [
            'CRUD completo (`/api/labels`, `/api/labels/reorder`, `/api/labels/{id}/move-emails`). Hasta **500** por usuario; `name` es el **segmento** (máx. 50, sin `/`, comas ni caracteres de control), único entre hermanas (409 si se repite). Color `#RGB`/`#RRGGBB` (por defecto `#6366f1`). Crear con `name: "Trabajo/Proyecto A"` crea la jerarquía.',
            '`aliasSuffix` y `filterRegex` (campos antiguos) se **migran solos** a una regla equivalente vinculada (`Rule.labelId`: condición `toAlias` y regex de asunto/cuerpo) y se vacían; mientras no se migren siguen funcionando.',
            'Importar y exportar: las etiquetas de Gmail con `/` (`X-Gmail-Labels`) crean jerarquía; las carpetas de Outlook, Thunderbird, Maildir y ZIP se importan como etiquetas de comportamiento `folder` con su jerarquía; el export escribe la ruta completa en `X-Gmail-Labels` y los correos de una etiqueta-carpeta van a su subdirectorio en el ZIP.',
            'Ver "Carpetas y etiquetas" para la jerarquía y el comportamiento `tag` / `folder`.',
            'El [Organizer](/docs/sealer#organizer) puede proponer o aplicar etiquetas con IA.',
        ] },
        { t: 'h2', id: 'folders-labels', text: 'Carpetas y etiquetas' },
        { t: 'p', text: 'Modelo híbrido Gmail + Outlook. Las carpetas del sistema (`inbox`, `sent`, `drafts`, `scheduled`, `archive`, `trash`, `spam`) son fijas; las etiquetas se **anidan** (hasta 5 niveles, `Trabajo/Proyecto A`) y cada una tiene un **comportamiento**:' },
        { t: 'ul', items: [
            '`tag` (por defecto, estilo Gmail): el correo conserva su carpeta (sigue en Entrada) y gana la etiqueta.',
            '`folder` (estilo Outlook/Hotmail): al asignarla el correo **sale de Entrada** (`folder=archive`, `previousFolder=inbox`) y su ubicación visible es la etiqueta; no aparece en Archivados. Al quitarla, o al volver a Entrada a mano, regresa a Entrada. "Mover a…" y arrastrar a una etiqueta-carpeta hacen exactamente eso (y dejan las otras etiquetas-carpeta: un correo vive en una sola).',
            'Filtrar por una etiqueta padre **incluye a sus subetiquetas** (`?label=trabajo`; `&subs=0` para excluirlas). Los contadores de los padres acumulan hilos distintos de sus descendientes.',
            'Borrar una etiqueta nunca borra correos: las subetiquetas suben un nivel (o se borran con `?children=delete`) y los correos que solo estaban en una carpeta vuelven a Entrada.',
            'Columnas aditivas de `Label`: `parentId`, `behavior`, `sortOrder`, `icon`, `showInSidebar`, `showUnread`, `fullPath` (ruta calculada). Unicidad `(userId, parentId, name)` con el índice `Label_user_parent_name_key`. Correos: `Email.hdrs` (cabeceras de la lista blanca, ≤ 4 KB). Reglas: `Rule.labelId`, `matchedCount`, `lastMatchedAt`; tablas `RuleBatch` / `RuleBatchItem` (lotes con deshacer).',
            'UI: árbol `role="tree"` en la barra lateral y en Ajustes; arrastrar y soltar con alternativa de teclado (flechas, Alt+flechas para reordenar y anidar, F2 renombrar, Supr eliminar, menú contextual).',
        ] },
        { t: 'p', text: '**Carpetas vs etiquetas** (barra lateral). Dentro de la sección "Etiquetas y carpetas" hay dos grupos colapsables, con su contador de elementos: *Carpetas* (comportamiento `folder`) y *Etiquetas* (comportamiento `tag`). Son el **mismo objeto** con otro comportamiento, por eso comparten jerarquía, reglas y arrastrar y soltar.' },
        { t: 'ul', items: [
            '**Carpeta**: el correo vive en un solo lugar y sale de Entrada. **Etiqueta**: marca adicional; un correo puede tener varias y sigue en Entrada. Ejemplo: "Facturas" como carpeta aparta los recibos de Entrada; "Urgente" como etiqueta solo los destaca.',
            '**Regla de agrupación**: cada elemento raíz se muestra en el grupo de su propio comportamiento y sus subetiquetas **heredan el grupo de su raíz** (una carpeta dentro de una etiqueta se ve dentro de esa etiqueta, con icono de carpeta), de modo que el árbol nunca se rompe.',
            'El botón "+" abre un menú con "Nueva etiqueta" y "Nueva carpeta"; el icono "?" explica la diferencia. Desde el menú "…" de cada elemento, "Convertir en carpeta" / "Convertir en etiqueta" cambia el comportamiento (`PATCH /api/labels/{id}` con `behavior`; los correos ya etiquetados no se mueven salvo `moveExisting: true`, disponible en Ajustes → Etiquetas).',
            'Contadores: el número resaltado son los **no leídos** y, al pasar el cursor, aparece el total (`236/265`); el lector de pantalla anuncia "236 sin leer de 265".',
        ] },
        { t: 'h2', id: 'rules-v2', text: 'Motor de condiciones v2' },
        { t: 'p', text: 'Las condiciones se guardan como `{ "v": 2, "root": Group }`. Un grupo es `{ "type": "group", "op": "and"|"or"|"not", "children": [...] }` (`not` = ninguna de las hijas coincide); una hoja es `{ "field", "op", "value"|"values", ... }`. Máx. 4 niveles y 30 condiciones, valores de hasta 500 caracteres y listas de hasta 100. La validación es estricta (zod) y las regex pasan las mismas defensas anti-ReDoS (200 caracteres, sin referencias hacia atrás ni lookarounds, sin cuantificadores anidados).' },
        { t: 'p', text: 'Lógica de tres valores: si falta un dato (por ejemplo las cabeceras de un correo anterior a esta función) la condición es *desconocida* y **no coincide**, tampoco dentro de un `not`. Cada regla tiene un presupuesto de 75 ms por correo.' },
        { t: 'table', head: ["Campo","Operadores / valor"], rows: [["`from` `fromName` `fromDomain` `replyTo`","Texto: `contains` `notContains` `equals` `notEquals` `startsWith` `endsWith` `regex` `notRegex` `in` `notIn` `wildcard` `notWildcard`. `fromDomain` admite `subdomains: true`"],["`to` `toDomain` `cc` `bcc` `toAlias`","Igual; se comprueba cada dirección de la lista. `toAlias` = sufijo de `usuario+sufijo@`"],["`subject` `body` `bodyHtml` `language`","Texto (+ `containsAny`). Opciones `caseSensitive` y `wholeWord`. El texto se acota a 20 KB. `language`: es/en/pt/fr/de/it por heurística de palabras frecuentes"],["`hasAttachment` `attachmentName` `attachmentType` `attachmentCount` `attachmentsSize`","Booleano / texto (extensión o MIME, p. ej. `pdf`, `image/*`) / numérico (bytes)"],["`size` `spamScore`","Numérico: `lt` `lte` `eq` `gte` `gt` (`size` = adjuntos + cuerpo, aproximado)"],["`date` `hour` `dayOfWeek`","`before` `after` `between` (ISO); hora 0–23 y día 0 (domingo)–6 con `tz` opcional (IANA)"],["`isReply` `isForward` `isThread` `isCalendarInvite` `senderInContacts` `senderIsMe` `isRead` `isStarred`","Booleano (`value`)"],["`hasLabel` `inFolder`","Etiqueta por id, nombre o ruta (un padre incluye a sus descendientes) / carpeta del sistema"],["`header` `auth`","`header`: `name` de la lista blanca (`list-id`, `list-unsubscribe`, `precedence`, `auto-submitted`, `x-mailer`, `reply-to`, `authentication-results`…) + `exists` `notExists` o un operador de texto. `auth`: `mech` spf/dkim/dmarc con `pass` `fail` `none`"]] },
        { t: 'code', lang: 'json', title: 'Regla v2 de una etiqueta-carpeta', code: ruleV2Ex },
        { t: 'ul', items: [
            '**Probar**: `POST /api/rules/preview` evalúa unas condiciones contra tus últimos 50 o 200 correos (o, con `mode: "count"`, por páginas sobre todo el correo) sin efectos; limitado por ritmo.',
            '**Aplicar a existentes**: `POST /api/rules/apply` con `ruleId` o `labelId` (páginas con `cursor`, `dryRun`, `batchId`); cada lote guarda el estado previo y `POST /api/rules/batches/{id}/undo` lo deshace una sola vez sin pisar cambios posteriores.',
            '**Plantillas**: todo de un dominio, boletines (`List-Unsubscribe`), facturas con PDF, de mis contactos y notificaciones automáticas. Cada regla se describe en lenguaje natural ("Si el dominio del remitente es \"empresa.com\" y el asunto contiene \"factura\" → etiquetar \"Facturas\"").',
        ] },
        { t: 'h2', id: 'search', text: 'Búsqueda con operadores' },
        { t: 'p', text: 'La barra de búsqueda admite operadores y texto libre, todo combinado con AND. Máximo 300 caracteres y 30 términos; los valores admiten comillas.' },
        { t: 'table', head: ['Operador', 'Significado'], rows: [
            ['`label:x`', 'Etiqueta con ese nombre (sin distinguir mayúsculas)'],
            ['`from:x`', 'El remitente contiene `x`'],
            ['`to:x`', 'Destinatarios (`to`) contienen `x`'],
            ['`subject:x`', 'El asunto contiene `x`'],
            ['`has:attachment`', 'Tiene adjuntos (único valor válido de `has:`)'],
            ['`is:unread`, `is:read`, `is:starred`', 'Estado. Pedir `unread` y `read` a la vez las anula'],
        ] },
        { t: 'code', lang: 'text', title: 'Ejemplo', code: searchEx },
        { t: 'ul', items: [
            'El texto libre usa **búsqueda de texto completo de PostgreSQL** (`websearch_to_tsquery`, configuración `simple`) sobre asunto, remitente y **extracto** (no sobre el cuerpo completo); si falla o no encuentra nada, cae a `ILIKE`.',
            'Con búsqueda, el alcance es global (todas las carpetas salvo papelera y spam). Resultados de 20 en 20.',
            '**No existen** los operadores `before:`, `after:`, `in:`, `filename:`, `cc:` ni `bcc:`. Cualquier otro `clave:valor` se trata como texto libre. Los rangos de fecha, remitente y "con adjuntos" están en el filtro avanzado de la interfaz (`since`, `until`, `from`, `hasAttachment`).',
        ] },
        { t: 'h2', id: 'compose', text: 'Redactar y enviar' },
        { t: 'ul', items: [
            '**Borradores**: autoguardado con retardo de 2 s, guardado al ocultar la pestaña o cerrar (`keepalive`), y solo se guardan adjuntos ya subidos. Indicador "Guardando… / Borrador guardado".',
            '**Límites de envío**: hasta 100 destinatarios (To+Cc+Bcc), asunto ≤ 998 caracteres, `MAX_SENDS_PER_HOUR` (200 por defecto) enviados por hora y usuario (429). El hook `EMAIL_PRE_SEND` puede bloquear (422) o modificar el contenido.',
            '**Adjuntos**: hasta 25 por correo; inline (base64) hasta 35 MB en total (413); por subida previa (`/api/upload`) hasta 200 MB por archivo. Extensiones peligrosas rechazadas y tipo real validado; antivirus opcional ([Seguridad](/docs/security#attachments)).',
            '**Reply/Reply-all/Forward**: responder a todos incluye Cc originales (con parsing correcto de nombres con comas y comillas) y reenviar copia los adjuntos con verificación de propiedad en el servidor.',
            '**Programar envío**: `scheduledAt` se pasa a Resend y el correo queda en la carpeta "Scheduled". No hay código que lo mueva a "Sent" al llegar la hora (no verificado). Cancelar un envío programado existe solo como API (`POST /api/emails/[id]/cancel`) **sin interfaz**.',
            '**Snooze**: solo existe la API (`POST /api/emails/[id]/snooze`), **sin interfaz**. La reactivación es perezosa al listar el correo.',
            '**Deshacer envío** con retardo: **no existe**.',
            '**Idempotencia**: `POST /api/emails` acepta `Idempotency-Key` (8–128 caracteres): un reintento devuelve `{duplicate:true}` y una petición concurrente responde 425. La interfaz de redacción no lo envía; sí la cola offline y Elixir.',
            '**Sellado**: envío con cifrado de extremo a extremo, ver [Sealer](/docs/sealer).',
        ] },
        { t: 'h2', id: 'threads', text: 'Hilos de conversación y compatibilidad con otros clientes' },
        { t: 'p', text: 'Lo que enviamos se agrupa y se ve bien en Gmail, Outlook/Hotmail, Apple Mail, Thunderbird, Titan, Zoho y Yahoo; y lo que recibimos de ellos se agrupa y se pliega aquí. Está construido sobre los estándares (RFC 5322 §3.6.4 para `Message-ID`/`In-Reply-To`/`References`, RFC 2369 para `List-*`, RFC 3676 para la firma `-- `) y sobre los patrones documentados de cada cliente; no se ha probado contra los servicios reales, solo contra fixtures sintéticos reproducibles (`src/lib/__tests__/helpers/thread-fixtures.ts`, una conversación mixta de 13 correos de 12 clientes).' },
        { t: 'ul', items: [
            '**Modelo** (columnas aditivas de `Email`, creadas por `npm run db:ensure`): `rfcMessageId` (Message-ID sin `<>`, dominio en minúsculas), `inReplyTo`, `refs` (References normalizadas: la raíz + las 50 más recientes; las pistas de Outlook se guardan al final con el prefijo `~`) y `threadKey` (raíz canónica del hilo: `m:<Message-ID>`, `e:<id>` o `h:<clave heredada>`). Índices `(userId, threadKey)`, `(userId, rfcMessageId)` y parcial `(userId, inReplyTo)`. Si faltan las columnas todo sigue funcionando con la heurística heredada.',
            '**Algoritmo** (`src/lib/threading.ts`, una sola definición para la lista, el SQL de conteos/orden/filtros/multi-buzón, el lector, la ingesta y la importación): JWZ simplificado con union-find sobre Message-ID/In-Reply-To/References. Ignora ids basura o gigantes (`<>`, `null`, > 255 caracteres…), es inmune a ciclos, y ningún hilo pasa de 500 mensajes (una unión que lo superaría se ignora). La clave es función del **conjunto** de mensajes: llegue en el orden que llegue, el mismo hilo da la misma clave, y el mensaje que une dos hilos fusiona sus claves con un `UPDATE` en lote. El asunto puede cambiar a mitad de la conversación sin partir el hilo, y dos conversaciones con el mismo asunto no se juntan.',
            '**Respaldo sin cabeceras útiles**: asunto normalizado + intersección de participantes (sin contarte a ti) en una ventana de 45 días. Solo se aplica a mensajes sin Message-ID ni cabeceras de respuesta (importados de orígenes pobres) y a respuestas cuyo padre no conocemos (p. ej. el proveedor de envío sustituyó nuestro Message-ID). Un mensaje nuevo con su propio Message-ID y sin In-Reply-To es una conversación nueva. Las listas (`List-Id`), autorespuestas (`Auto-Submitted`) y `Precedence: bulk` nunca se unen por asunto. `Thread-Index` de Outlook/Exchange se usa como pista secundaria.',
            '**Asuntos multilingües**: se ignoran Re, Res, RV, AW, SV, VS, Antw, R, ENC, Fwd, FW, WG, TR, I, Rif, Odp, VB, PD, VL, FS, YNT, 回复, 答复, 回覆, 转发, `Re[2]:` y los dos puntos de ancho completo, además de las marcas de invitación de calendario. El mismo texto de regex se usa en JavaScript y en PostgreSQL (un test compara ambos con 220 correos aleatorios, con y sin `threadKey`).',
            '**Ingesta**: el webhook de Resend guarda el `message_id` y las cabeceras que vengan en el payload; si el asunto parece una respuesta y faltan `In-Reply-To`/`References`, pide el correo completo a Resend. `process-attachments` vuelve a calcular el hilo con el MIME crudo (`raw.eml`) y la importación (`mail-transfer`) usa las cabeceras del archivo. Nunca hace fallar la entrega.',
            '**Correos antiguos**: un relleno perezoso (`backfillThreadHeaders`) lee `raw.eml`, `raw.json` o `rawMimeUrl` (descarga con las salvaguardas de `raw-mime.ts`) en lotes desde el cron (`/api/cron/run`) o a mano con `POST /api/mail/threads/backfill` (repetir hasta `remaining: 0`). Lo que no tiene cabeceras sigue agrupándose por asunto + destinatarios.',
            '**Envío** (`POST /api/emails`): el cliente solo manda `inReplyToEmailId` (y `replyMode`: `reply`, `replyAll` o `forward`); el servidor comprueba que el correo original es tuyo (404 si no) y emite `In-Reply-To: <id del original>`, `References: <cadena hasta el original, máx. raíz + 50>` y un `Message-ID` propio. Un correo nuevo lleva `Message-ID` y `X-Entity-Ref-ID` (para que Gmail no lo una por asunto a otros envíos parecidos). Los reenvíos no llevan In-Reply-To/References (como Gmail, Apple Mail y Thunderbird) pero se agrupan con el original en tu bandeja. Los envíos de Elixir/campañas no llevan cabeceras de hilo.',
            '**Asunto saliente**: un solo prefijo, en el idioma del original si es conocido (`Re`, `Res`, `AW`, `SV`, `VS`, `Antw`, `Odp`, `YNT`; `Fwd`, `FW`, `WG`, `TR`, `RV`, `ENC`…) o `Re:`/`Fwd:`; nunca `Re: Re:` ni idiomas mezclados. Si quitas el prefijo a propósito, se respeta.',
            '**Qué se puede garantizar con Resend**: `In-Reply-To` y `References` viajan en `headers` (el SDK envía el objeto tal cual a la API) y el payload se verifica con el Resend simulado. El `Message-ID` propio también se envía en `headers`; si el proveedor lo rechaza se reintenta una vez sin él, y si lo sustituye por otro, las respuestas que citen el id real se agrupan por el respaldo (asunto + participantes, 45 días). El SDK instalado no expone el Message-ID final de un envío saliente (no verificado contra el servicio real), así que no hay tarea que lo recupere.',
            '**Cita al responder** (`src/lib/reply-builder.ts`): `div.gmail_quote > div.gmail_attr` + `blockquote.gmail_quote` con el estilo de Gmail (los pliegan Gmail, Apple Mail, Thunderbird, Titan, Zoho y Yahoo), atribución en tu idioma con fecha larga y zona, nombre escapado, original saneado (sin scripts, estilos externos, controles ni píxeles de seguimiento), tope de 100 KB con marcador `[...]`, y versión texto con `> ` por nivel. Al reenviar: bloque estilo Gmail o estilo Outlook (`De/Enviado el/Para/Asunto`) y `Reenviar como adjunto (.eml)`. Las imágenes incrustadas (`data:`) salen como partes inline con `Content-ID`, porque Gmail y Outlook no muestran `data:`.',
            '**Historial recibido** (`quoted-html.ts`, `quoted-text.ts`): pliega Gmail, Outlook.com/Hotmail (`#divRplyFwdMsg`, `#appendonsend`), Outlook de escritorio (bloque `De:/Enviado el:/Para:/Asunto:` y traducciones), Apple Mail/iCloud, Thunderbird, Yahoo, Proton, Zoho, Titan/Flock (detección genérica atribución + cita final), Samsung, separadores `-----Original Message-----`, y texto plano con `>` anidado y atribuciones en unos 17 idiomas. Nunca deja un mensaje sin contenido visible. En la conversación cada mensaje muestra solo lo nuevo; "ocultar duplicados" (activado por defecto) pliega el historial que ya está en el hilo sin perder nada.',
            '**Límites reales**: las clases de Spark, Superhuman, Front y HubSpot no se han podido verificar sin correos reales (se cubren con la detección genérica); un borrador de respuesta reabierto pierde el vínculo con el original (`inReplyToEmailId` no se guarda en `Draft`) y se apoya en el respaldo; el Message-ID de un envío lo fija Resend/SES y puede diferir del que enviamos.',
        ] },
        { t: 'h2', id: 'contacts', text: 'Contactos' },
        { t: 'ul', items: [
            'Página `/contacts` con búsqueda en el servidor, "cargar más" y edición/borrado. Origen `local` o `google` (la sincronización con Google trae contactos con `source=google`; los locales conservan sus datos).',
            'API `/api/contacts` (límite 1000, `q` ≤ 100; cabeceras `X-Total-Count` y `X-Has-More`). Crear un contacto existente da **409** `CONTACT_EXISTS`.',
            'Sugerencias (`/api/contacts/suggestions?q=`, máx. 8): mezcla contactos y direcciones de los últimos 250 correos; las usan los campos Para/Cc/Cco.',
            'Importar/exportar CSV o vCard **no existe** en la interfaz.',
        ] },
        { t: 'h2', id: 'calendar', text: 'Calendario y citas' },
        { t: 'ul', items: [
            '**Calendario** (`/calendar`): vistas mes, semana y día; calendarios por defecto (el propio, "invitaciones compartidas" y festivos de solo lectura); eventos con asistentes que reciben invitación por correo (`.ics`) y aviso `.ics` de cancelación al borrar. No hay recurrencia (RRULE) al crear eventos.',
            '**RSVP** a invitaciones recibidas (aceptar / provisional / rechazar) responde con `.ics`. Disponibilidad de compañeros del **mismo dominio** de correo (`/api/calendar/domain-availability`).',
            '**Recordatorios** push de eventos que empiezan en los próximos 15 min (cron, cada 5 min como máximo; se desactivan con `calendarNotificationsEnabled=false`).',
            '**Google**: `POST /api/google/sync` es **unidireccional** (Google → local): calendarios, eventos (−30 a +180 días; los cancelados se borran) y contactos, con límites de páginas y una sola sincronización a la vez (409 `SYNC_IN_PROGRESS`). Meet en eventos vía la API de Meet con el token del usuario.',
            '**Citas** (`/appointments`, reserva pública `/book/<id>`): agendas con duración (15–120 min en la UI), zona horaria, disponibilidad semanal (por defecto lun–vie 09:00–17:00) y videollamada Meet o Zoom. Los huecos respetan la zona horaria y descartan lo ocupado (eventos y reservas). Reserva con límites (10/h por IP y 3/h por correo), bloqueo transaccional anti doble reserva (409) y correo de confirmación con `.ics`. Cancelación con enlace firmado que caduca al empezar la cita.',
        ] },
        { t: 'h2', id: 'offline', text: 'Offline y PWA' },
        { t: 'ul', items: [
            '**Service worker** (`sw.js`): cachea solo recursos estáticos (`/_next/static/*`, iconos y `/offline.html`; máx. 80 entradas). **Nunca** cachea `/api/*`, peticiones con `Authorization` ni páginas HTML. Sin red, las navegaciones muestran `/offline.html`.',
            '**Cola offline**: acciones por lote de la lista (`/api/emails/batch` y `/api/drafts/batch`) se guardan (máx. 200, hasta 8 intentos con backoff 2 s–5 min) y se reenvían con `Idempotency-Key` y el token de la cuenta que las originó. **Enviar un correo sin red no se encola.**',
            '**Caché de lectura**: IndexedDB por usuario. **Tiempo real**: `/api/sse` (máx. 3 conexiones por usuario, vida 50 s con reconexión por `Last-Event-ID`).',
            '**PWA**: `manifest` dinámico con nombre, logo y colores del dominio (`display: standalone`); avisos de instalación y de notificaciones una sola vez.',
            '**Push web** (VAPID): con `NEXT_PUBLIC_VAPID_PUBLIC_KEY` y `VAPID_PRIVATE_KEY`, o pares generados y guardados en la tabla `push_vapid_config`. Se notifica al recibir correo y en recordatorios.',
        ] },
        { t: 'h2', id: 'shortcuts', text: 'Atajos de teclado' },
        { t: 'p', text: 'Un único listener global, activo en la lista de correo. Se ignora si hay Ctrl/Meta/Alt, si el foco está en un campo de texto, si hay un diálogo abierto o durante una composición IME.' },
        { t: 'table', head: ['Tecla', 'Acción'], rows: [
            ['`c`', 'Redactar'],
            ['`/`', 'Enfocar el buscador (también en /docs)'],
            ['`j` / `k`', 'Siguiente / anterior'],
            ['`Enter` / `o`', 'Abrir el correo enfocado'],
            ['`r`', 'Responder'],
            ['`x`', 'Alternar selección'],
            ['`e`', 'Archivar'],
            ['`#`, `Delete`, `Backspace`', 'Mover a la papelera'],
            ['`Escape`', 'Cierra selector de etiquetas, luego limpia selección, luego cierra el correo, luego quita el foco'],
            ['`Ctrl/Cmd+Enter`', 'Enviar (en el editor de redacción)'],
        ] },
        { t: 'p', text: 'No existen secuencias tipo `g i`, ni `u`, `s`, `l`, `?`, ni ayuda de atajos, ni atajos de calendario o contactos.' },
        { t: 'h2', id: 'i18n', text: 'Idiomas (i18n)' },
        { t: 'ul', items: [
            'Idiomas: español (por defecto) e inglés. Resolución: cookie `bloomx-lang` → cabecera `Accept-Language` → español. `<html lang>` se actualiza sin recargar; el usuario cambia el idioma en Ajustes → Apariencia (y en el encabezado de /docs).',
            'Cliente: `const { t } = useI18n()`. Servidor: `getServerTranslator()`. Claves `t("seccion.clave", {param})`; si falta, se busca en español, luego inglés y, por último, se muestra la clave.',
            '**Añadir una clave**: en `src/lib/i18n/messages/es.ts` (define el tipo) y `en.ts` (tipado: exige las mismas claves). Un test comprueba las claves usadas en las pantallas migradas.',
            '**Añadir un idioma**: ampliar `LOCALES` y `LOCALE_LABELS` en `core.ts`, crear `messages/<xx>.ts` y registrarlo en `index.ts`; para la landing, ampliar además `LANDING_LOCALES` (espejo idéntico en el backend) y `landing-messages.ts`.',
            'La landing de cada empresa tiene sus textos por idioma ([Landing y login](/docs/landing#i18n)).',
        ] },
    ],
    en: [
        { t: 'p', text: 'Reference of what mail does **today**. Where a feature does not exist or only half exists, it says so explicitly.' },
        { t: 'h2', id: 'rules', text: 'Mail rules' },
        { t: 'ul', items: [
            'A rule has `name` (1–80), `enabled`, `priority` (integer −1000..1000; **lower number = evaluated first**), `conditions` (**v2** schema, see "Condition engine v2"; the v1 format `{match, items}` or a plain array is still read and saved as v2), 1 to **30 conditions** in groups nested up to **4 levels**, 1 to 12 actions, `stopProcessing` and, optionally, `labelId` (a label\'s "Assign automatically" rule). At most **100 rules** per user.',
            '**Conditions**: a tree of `and` / `or` / `not` groups (*none* of the children) with typed leaves; see "Condition engine v2". A rule without conditions never matches.',
            '**Actions**: `addLabel`, `removeLabel`, `moveToLabelFolder {labelId}`, `markRead`, `star`, `archive` (skip the Inbox), `moveToFolder {folder}` (`inbox|archive|trash|spam`), `delete` (to trash: **permanent deletion does not exist as an action**), `markSpam`, `snooze {hours}` (1–8760), `forwardTo {address}` (off by default: needs `RULES_FORWARD_ENABLED=true`, only to verified addresses of the user themselves, max 30 per hour, never auto-generated mail) and `stopProcessing`. For one label, the last action in priority order wins.',
            'Each rule is evaluated once against the message\'s initial state: actions do not trigger other rules (no chains or loops). If several rules set the folder, the highest priority wins. `stopProcessing: true` cuts processing short.',
            '**User regex**: max 200 characters; back-references, lookahead/lookbehind, nested quantifiers and alternation inside quantified groups are rejected (ReDoS protection).',
            '**When applied**: on receiving a message (with real headers, attachments and contacts); with "Apply to existing mail" (pages of 200 with progress, a preview of the number of matches and a per-batch **Undo**; only `inbox` and `archive`, never forwards); and in the cron (catch-up over the last 2 days, batches of 200). The full body is read from storage only if the rule uses `body`/`bodyHtml`. A rule does not pull a message out of `spam` if it already arrived as spam from headers.',
            'If the `Rule`/`RuleRun` tables do not exist, reads return `[]` and writes answer 503 (run `npm run db:ensure`).',
            'Managed in Settings → Rules (drag or use the buttons to change priority) and, per label, in Settings → Labels → "Assign automatically". Same engine, same table.',
        ] },
        { t: 'code', lang: 'json', title: 'Example rule', code: ruleExEn },
        { t: 'h2', id: 'labels', text: 'Labels' },
        { t: 'ul', items: [
            'Full CRUD (`/api/labels`, `/api/labels/reorder`, `/api/labels/{id}/move-emails`). Up to **500** per user; `name` is the **segment** (max 50, no `/`, commas or control characters), unique among siblings (409 if repeated). Colour `#RGB`/`#RRGGBB` (default `#6366f1`). Creating with `name: "Work/Project A"` creates the hierarchy.',
            '`aliasSuffix` and `filterRegex` (old fields) **migrate themselves** to an equivalent linked rule (`Rule.labelId`: a `toAlias` condition and a subject/body regex) and are cleared; until migrated they keep working.',
            'Import and export: Gmail labels with `/` (`X-Gmail-Labels`) create a hierarchy; Outlook, Thunderbird, Maildir and ZIP folders are imported as `folder`-behaviour labels with their hierarchy; export writes the full path in `X-Gmail-Labels` and mail in a folder label goes to its sub-directory in the ZIP.',
            'See "Folders and labels" for the hierarchy and the `tag` / `folder` behaviour.',
            'The [Organizer](/docs/sealer#organizer) can propose or apply labels with AI.',
        ] },
        { t: 'h2', id: 'folders-labels', text: 'Folders and labels' },
        { t: 'p', text: 'A hybrid Gmail + Outlook model. System folders (`inbox`, `sent`, `drafts`, `scheduled`, `archive`, `trash`, `spam`) are fixed; labels **nest** (up to 5 levels, `Work/Project A`) and each has a **behaviour**:' },
        { t: 'ul', items: [
            '`tag` (default, Gmail style): the message keeps its folder (stays in the Inbox) and gains the label.',
            '`folder` (Outlook/Hotmail style): when assigned the message **leaves the Inbox** (`folder=archive`, `previousFolder=inbox`) and its visible location is the label; it does not show in Archive. Removing it, or moving the message back to the Inbox by hand, returns it to the Inbox. "Move to…" and dragging onto a folder label do exactly that (and drop other folder labels: a message lives in one).',
            'Filtering by a parent label **includes its sub-labels** (`?label=work`; `&subs=0` to exclude them). Parent counters accumulate distinct threads of their descendants.',
            'Deleting a label never deletes mail: sub-labels move up one level (or are deleted with `?children=delete`) and mail that was only in a folder returns to the Inbox.',
            'Additive `Label` columns: `parentId`, `behavior`, `sortOrder`, `icon`, `showInSidebar`, `showUnread`, `fullPath` (computed path). Uniqueness `(userId, parentId, name)` via the `Label_user_parent_name_key` index. Mail: `Email.hdrs` (whitelisted headers, ≤ 4 KB). Rules: `Rule.labelId`, `matchedCount`, `lastMatchedAt`; `RuleBatch` / `RuleBatchItem` tables (batches with undo).',
            'UI: a `role="tree"` in the sidebar and in Settings; drag and drop with a keyboard alternative (arrows, Alt+arrows to reorder and nest, F2 rename, Delete remove, context menu).',
        ] },
        { t: 'p', text: '**Folders vs labels** (sidebar). Inside the "Labels and folders" section there are two collapsible groups, each with an item counter: *Folders* (`folder` behavior) and *Labels* (`tag` behavior). They are the **same object** with a different behavior, so they share hierarchy, rules and drag and drop.' },
        { t: 'ul', items: [
            '**Folder**: a message lives in one place and leaves the Inbox. **Label**: an extra mark; a message can have several and stays in the Inbox. Example: "Invoices" as a folder keeps receipts out of the Inbox; "Urgent" as a label only highlights them.',
            '**Grouping rule**: each root item is shown in the group of its own behavior and its sub-items **inherit the group of their root** (a folder inside a label is shown inside that label, with a folder icon), so the tree never breaks.',
            'The "+" button opens a menu with "New label" and "New folder"; the "?" icon explains the difference. From the "…" menu of each item, "Convert to folder" / "Convert to label" changes the behavior (`PATCH /api/labels/{id}` with `behavior`; already-labeled mail is not moved unless `moveExisting: true`, available in Settings → Labels).',
            'Counters: the highlighted number is **unread** and the total appears on hover (`236/265`); screen readers announce "236 unread of 265".',
        ] },
        { t: 'h2', id: 'rules-v2', text: 'Condition engine v2' },
        { t: 'p', text: 'Conditions are stored as `{ "v": 2, "root": Group }`. A group is `{ "type": "group", "op": "and"|"or"|"not", "children": [...] }` (`not` = none of the children match); a leaf is `{ "field", "op", "value"|"values", ... }`. Max 4 levels and 30 conditions, values up to 500 characters and lists up to 100. Validation is strict (zod) and regexes go through the same anti-ReDoS defences (200 characters, no back-references or lookarounds, no nested quantifiers).' },
        { t: 'p', text: 'Three-valued logic: when data is missing (for example the headers of a message that predates this feature) the condition is *unknown* and **does not match**, not even inside a `not`. Each rule has a 75 ms budget per message.' },
        { t: 'table', head: ["Field","Operators / value"], rows: [["`from` `fromName` `fromDomain` `replyTo`","Text: `contains` `notContains` `equals` `notEquals` `startsWith` `endsWith` `regex` `notRegex` `in` `notIn` `wildcard` `notWildcard`. `fromDomain` accepts `subdomains: true`"],["`to` `toDomain` `cc` `bcc` `toAlias`","Same; every address of the list is checked. `toAlias` = the `user+suffix@` suffix"],["`subject` `body` `bodyHtml` `language`","Text (+ `containsAny`). Options `caseSensitive` and `wholeWord`. Text is capped at 20 KB. `language`: es/en/pt/fr/de/it by a frequent-words heuristic"],["`hasAttachment` `attachmentName` `attachmentType` `attachmentCount` `attachmentsSize`","Boolean / text (extension or MIME, e.g. `pdf`, `image/*`) / numeric (bytes)"],["`size` `spamScore`","Numeric: `lt` `lte` `eq` `gte` `gt` (`size` = attachments + body, approximate)"],["`date` `hour` `dayOfWeek`","`before` `after` `between` (ISO); hour 0–23 and day 0 (Sunday)–6 with optional `tz` (IANA)"],["`isReply` `isForward` `isThread` `isCalendarInvite` `senderInContacts` `senderIsMe` `isRead` `isStarred`","Boolean (`value`)"],["`hasLabel` `inFolder`","Label by id, name or path (a parent includes its descendants) / system folder"],["`header` `auth`","`header`: a whitelisted `name` (`list-id`, `list-unsubscribe`, `precedence`, `auto-submitted`, `x-mailer`, `reply-to`, `authentication-results`…) + `exists` `notExists` or a text operator. `auth`: `mech` spf/dkim/dmarc with `pass` `fail` `none`"]] },
        { t: 'code', lang: 'json', title: 'A v2 rule for a folder label', code: ruleV2ExEn },
        { t: 'ul', items: [
            '**Test**: `POST /api/rules/preview` evaluates conditions against your latest 50 or 200 messages (or, with `mode: "count"`, page by page over all mail) with no side effects; rate-limited.',
            '**Apply to existing**: `POST /api/rules/apply` with `ruleId` or `labelId` (pages with `cursor`, `dryRun`, `batchId`); each batch stores the previous state and `POST /api/rules/batches/{id}/undo` reverts it once without overwriting later changes.',
            '**Templates**: everything from a domain, newsletters (`List-Unsubscribe`), invoices with PDF, from my contacts and automated notifications. Every rule is described in plain language ("If the sender domain is \"company.com\" and the subject contains \"invoice\" → label \"Invoices\"").',
        ] },
        { t: 'h2', id: 'search', text: 'Search with operators' },
        { t: 'p', text: 'The search bar accepts operators and free text, all combined with AND. Max 300 characters and 30 terms; values accept quotes.' },
        { t: 'table', head: ['Operator', 'Meaning'], rows: [
            ['`label:x`', 'Label with that name (case-insensitive)'],
            ['`from:x`', 'The sender contains `x`'],
            ['`to:x`', 'Recipients (`to`) contain `x`'],
            ['`subject:x`', 'The subject contains `x`'],
            ['`has:attachment`', 'Has attachments (the only valid `has:` value)'],
            ['`is:unread`, `is:read`, `is:starred`', 'State. Asking for `unread` and `read` together cancels them'],
        ] },
        { t: 'code', lang: 'text', title: 'Example', code: searchEx },
        { t: 'ul', items: [
            'Free text uses **PostgreSQL full-text search** (`websearch_to_tsquery`, `simple` configuration) over subject, sender and **snippet** (not the full body); if it fails or finds nothing, it falls back to `ILIKE`.',
            'With a search, the scope is global (all folders except trash and spam). Results 20 at a time.',
            'The operators `before:`, `after:`, `in:`, `filename:`, `cc:` and `bcc:` **do not exist**. Any other `key:value` is treated as free text. Date ranges, sender and "with attachments" live in the UI\'s advanced filter (`since`, `until`, `from`, `hasAttachment`).',
        ] },
        { t: 'h2', id: 'compose', text: 'Composing and sending' },
        { t: 'ul', items: [
            '**Drafts**: autosave with a 2 s delay, saved on tab hide or close (`keepalive`), and only already-uploaded attachments are saved. "Saving… / Draft saved" indicator.',
            '**Send limits**: up to 100 recipients (To+Cc+Bcc), subject ≤ 998 characters, `MAX_SENDS_PER_HOUR` (200 by default) sends per hour per user (429). The `EMAIL_PRE_SEND` hook can block (422) or modify the content.',
            '**Attachments**: up to 25 per message; inline (base64) up to 35 MB in total (413); via prior upload (`/api/upload`) up to 200 MB per file. Dangerous extensions rejected and real type validated; optional antivirus ([Security](/docs/security#attachments)).',
            '**Reply/Reply-all/Forward**: reply-all includes original Cc (with correct parsing of names with commas and quotes) and forward copies attachments with server-side ownership checks.',
            '**Scheduled send**: `scheduledAt` is passed to Resend and the message sits in the "Scheduled" folder. No code moves it to "Sent" when the time comes (not verified). Cancelling a scheduled send exists only as an API (`POST /api/emails/[id]/cancel`) **without UI**.',
            '**Snooze**: only the API exists (`POST /api/emails/[id]/snooze`), **without UI**. Wake-up is lazy when listing mail.',
            '**Undo send** with a delay: **does not exist**.',
            '**Idempotency**: `POST /api/emails` accepts `Idempotency-Key` (8–128 characters): a retry returns `{duplicate:true}` and a concurrent request answers 425. The compose UI does not send it; the offline queue and Elixir do.',
            '**Sealed**: end-to-end encrypted sending, see [Sealer](/docs/sealer).',
        ] },
        { t: 'h2', id: 'threads', text: 'Conversation threads and compatibility with other clients' },
        { t: 'p', text: 'What we send is grouped and rendered well in Gmail, Outlook/Hotmail, Apple Mail, Thunderbird, Titan, Zoho and Yahoo; and what we receive from them is grouped and folded here. It follows the standards (RFC 5322 §3.6.4 for `Message-ID`/`In-Reply-To`/`References`, RFC 2369 for `List-*`, RFC 3676 for the `-- ` signature) and each client\'s documented patterns; it was not tested against the real services, only against reproducible synthetic fixtures (`src/lib/__tests__/helpers/thread-fixtures.ts`, a mixed conversation of 13 messages from 12 clients).' },
        { t: 'ul', items: [
            '**Model** (additive `Email` columns created by `npm run db:ensure`): `rfcMessageId` (Message-ID without `<>`, lower-cased domain), `inReplyTo`, `refs` (normalised References: the root + the 50 most recent; Outlook hints are stored at the end with a `~` prefix) and `threadKey` (canonical thread root: `m:<Message-ID>`, `e:<id>` or `h:<legacy key>`). Indexes `(userId, threadKey)`, `(userId, rfcMessageId)` and partial `(userId, inReplyTo)`. If the columns are missing everything keeps working with the legacy heuristic.',
            '**Algorithm** (`src/lib/threading.ts`, one definition shared by the list, the SQL for counts/order/filters/multi-mailbox, the reader, ingestion and import): simplified JWZ with union-find over Message-ID/In-Reply-To/References. It ignores junk or huge ids (`<>`, `null`, > 255 chars…), is immune to cycles, and no thread exceeds 500 messages (a union that would exceed it is ignored). The key is a function of the **set** of messages: whatever the arrival order, the same thread gets the same key, and the message that joins two threads merges their keys with one batched `UPDATE`. The subject may change mid-conversation without splitting the thread, and two conversations with the same subject are not merged.',
            '**Fallback without useful headers**: normalised subject + intersection of participants (excluding you) within a 45-day window. Only applied to messages with no Message-ID and no reply headers (imported from poor sources) and to replies whose parent we do not know (e.g. the sending provider replaced our Message-ID). A new message with its own Message-ID and no In-Reply-To starts a new conversation. Mailing lists (`List-Id`), auto-replies (`Auto-Submitted`) and `Precedence: bulk` are never merged by subject. Outlook/Exchange `Thread-Index` is used as a secondary hint.',
            '**Multilingual subjects**: Re, Res, RV, AW, SV, VS, Antw, R, ENC, Fwd, FW, WG, TR, I, Rif, Odp, VB, PD, VL, FS, YNT, 回复, 答复, 回覆, 转发, `Re[2]:` and full-width colons are ignored, plus calendar invitation markers. The same regex text runs in JavaScript and PostgreSQL (a test compares both on 220 random emails, with and without `threadKey`).',
            '**Ingestion**: the Resend webhook stores `message_id` and any headers in the payload; if the subject looks like a reply and `In-Reply-To`/`References` are missing it asks Resend for the full message. `process-attachments` recomputes the thread from the raw MIME (`raw.eml`) and import (`mail-transfer`) uses the file\'s headers. It never fails delivery.',
            '**Old mail**: a lazy backfill (`backfillThreadHeaders`) reads `raw.eml`, `raw.json` or `rawMimeUrl` (download with the `raw-mime.ts` safeguards) in batches from the cron (`/api/cron/run`) or manually with `POST /api/mail/threads/backfill` (repeat until `remaining: 0`). Mail without headers keeps grouping by subject + recipients.',
            '**Sending** (`POST /api/emails`): the client only sends `inReplyToEmailId` (and `replyMode`: `reply`, `replyAll` or `forward`); the server checks the original is yours (404 otherwise) and emits `In-Reply-To: <original id>`, `References: <chain up to the original, max root + 50>` and its own `Message-ID`. A new message carries `Message-ID` and `X-Entity-Ref-ID` (so Gmail does not merge it by subject with similar sends). Forwards carry no In-Reply-To/References (like Gmail, Apple Mail and Thunderbird) but are grouped with the original in your mailbox. Elixir/campaign sends carry no thread headers.',
            '**Outgoing subject**: a single prefix, in the original\'s language when known (`Re`, `Res`, `AW`, `SV`, `VS`, `Antw`, `Odp`, `YNT`; `Fwd`, `FW`, `WG`, `TR`, `RV`, `ENC`…) or `Re:`/`Fwd:`; never `Re: Re:` nor mixed languages. If you remove the prefix on purpose it is respected.',
            '**What can be guaranteed with Resend**: `In-Reply-To` and `References` travel in `headers` (the SDK sends the object as is to the API) and the payload is verified against the simulated Resend. The own `Message-ID` is also sent in `headers`; if the provider rejects it we retry once without it, and if it replaces it, replies quoting the real id are grouped by the fallback (subject + participants, 45 days). The installed SDK does not expose the final Message-ID of an outgoing message (not verified against the real service), so no job recovers it.',
            '**Quote when replying** (`src/lib/reply-builder.ts`): `div.gmail_quote > div.gmail_attr` + `blockquote.gmail_quote` with Gmail\'s style (folded by Gmail, Apple Mail, Thunderbird, Titan, Zoho and Yahoo), attribution in your language with long date and time zone, escaped name, sanitised original (no scripts, external styles, controls or tracking pixels), 100 KB cap with a `[...]` marker, and a text version with `> ` per level. Forwards: Gmail or Outlook style block (`From/Sent/To/Subject`) and `Forward as attachment (.eml)`. Embedded images (`data:`) leave as inline parts with `Content-ID`, because Gmail and Outlook do not show `data:`.',
            '**Received history** (`quoted-html.ts`, `quoted-text.ts`): folds Gmail, Outlook.com/Hotmail (`#divRplyFwdMsg`, `#appendonsend`), Outlook desktop (`From:/Sent:/To:/Subject:` block and translations), Apple Mail/iCloud, Thunderbird, Yahoo, Proton, Zoho, Titan/Flock (generic attribution + trailing quote), Samsung, `-----Original Message-----` separators, and plain text with nested `>` and attributions in about 17 languages. It never leaves a message without visible content. In the conversation each message shows only what is new; "hide duplicates" (on by default) folds history already present in the thread without losing anything.',
            '**Real limits**: Spark, Superhuman, Front and HubSpot class names could not be verified without real mail (covered by the generic detection); a reopened reply draft loses its link to the original (`inReplyToEmailId` is not stored in `Draft`) and relies on the fallback; the Message-ID of a sent message is set by Resend/SES and may differ from the one we sent.',
        ] },
        { t: 'h2', id: 'contacts', text: 'Contacts' },
        { t: 'ul', items: [
            '`/contacts` page with server-side search, "load more" and edit/delete. Source `local` or `google` (Google sync brings contacts with `source=google`; local ones keep their data).',
            '`/api/contacts` API (limit 1000, `q` ≤ 100; `X-Total-Count` and `X-Has-More` headers). Creating an existing contact gives **409** `CONTACT_EXISTS`.',
            'Suggestions (`/api/contacts/suggestions?q=`, max 8): mixes contacts and addresses from the last 250 messages; used by the To/Cc/Bcc fields.',
            'Importing/exporting CSV or vCard **does not exist** in the UI.',
        ] },
        { t: 'h2', id: 'calendar', text: 'Calendar and appointments' },
        { t: 'ul', items: [
            '**Calendar** (`/calendar`): month, week and day views; default calendars (your own, "shared invites" and read-only holidays); events with attendees who receive an email invitation (`.ics`) and a cancellation `.ics` on delete. No recurrence (RRULE) when creating events.',
            '**RSVP** to received invitations (accept / tentative / decline) answers with `.ics`. Availability of colleagues from the **same mail domain** (`/api/calendar/domain-availability`).',
            'Push **reminders** for events starting within 15 min (cron, at most every 5 min; disable with `calendarNotificationsEnabled=false`).',
            '**Google**: `POST /api/google/sync` is **one-way** (Google → local): calendars, events (−30 to +180 days; cancelled ones are removed) and contacts, with page limits and one sync at a time (409 `SYNC_IN_PROGRESS`). Meet on events through the Meet API with the user\'s token.',
            '**Appointments** (`/appointments`, public booking `/book/<id>`): schedules with duration (15–120 min in the UI), time zone, weekly availability (default Mon–Fri 09:00–17:00) and Meet or Zoom video call. Slots respect the time zone and discard what is busy (events and bookings). Booking with limits (10/h per IP and 3/h per email), transactional anti-double-booking lock (409) and a confirmation email with `.ics`. Cancellation through a signed link that expires when the appointment starts.',
        ] },
        { t: 'h2', id: 'offline', text: 'Offline and PWA' },
        { t: 'ul', items: [
            '**Service worker** (`sw.js`): caches only static resources (`/_next/static/*`, icons and `/offline.html`; max 80 entries). It **never** caches `/api/*`, requests with `Authorization` or HTML pages. Offline, navigations show `/offline.html`.',
            '**Offline queue**: list batch actions (`/api/emails/batch` and `/api/drafts/batch`) are stored (max 200, up to 8 attempts with 2 s–5 min backoff) and resent with `Idempotency-Key` and the token of the account that originated them. **Sending an email offline is not queued.**',
            '**Read cache**: per-user IndexedDB. **Real time**: `/api/sse` (max 3 connections per user, 50 s lifetime with reconnect through `Last-Event-ID`).',
            '**PWA**: dynamic `manifest` with the domain\'s name, logo and colours (`display: standalone`); install and notification prompts shown only once.',
            '**Web push** (VAPID): with `NEXT_PUBLIC_VAPID_PUBLIC_KEY` and `VAPID_PRIVATE_KEY`, or pairs generated and stored in the `push_vapid_config` table. Notifies on incoming mail and reminders.',
        ] },
        { t: 'h2', id: 'shortcuts', text: 'Keyboard shortcuts' },
        { t: 'p', text: 'A single global listener, active in the mail list. It is ignored with Ctrl/Meta/Alt, when focus is in a text field, when a dialog is open or during IME composition.' },
        { t: 'table', head: ['Key', 'Action'], rows: [
            ['`c`', 'Compose'],
            ['`/`', 'Focus the search box (also in /docs)'],
            ['`j` / `k`', 'Next / previous'],
            ['`Enter` / `o`', 'Open the focused message'],
            ['`r`', 'Reply'],
            ['`x`', 'Toggle selection'],
            ['`e`', 'Archive'],
            ['`#`, `Delete`, `Backspace`', 'Move to trash'],
            ['`Escape`', 'Closes label picker, then clears selection, then closes the message, then removes focus'],
            ['`Ctrl/Cmd+Enter`', 'Send (in the compose editor)'],
        ] },
        { t: 'p', text: 'There are no `g i`-style sequences, no `u`, `s`, `l`, `?`, no shortcut help and no calendar or contacts shortcuts.' },
        { t: 'h2', id: 'i18n', text: 'Languages (i18n)' },
        { t: 'ul', items: [
            'Languages: Spanish (default) and English. Resolution: `bloomx-lang` cookie → `Accept-Language` header → Spanish. `<html lang>` updates without reload; users change language in Settings → Appearance (and in the /docs header).',
            'Client: `const { t } = useI18n()`. Server: `getServerTranslator()`. Keys `t("section.key", {param})`; if missing, Spanish is tried, then English and, finally, the key itself is shown.',
            '**Adding a key**: in `src/lib/i18n/messages/es.ts` (defines the type) and `en.ts` (typed: requires the same keys). A test checks the keys used in migrated screens.',
            '**Adding a language**: extend `LOCALES` and `LOCALE_LABELS` in `core.ts`, create `messages/<xx>.ts` and register it in `index.ts`; for the landing, also extend `LANDING_LOCALES` (identical mirror on the backend) and `landing-messages.ts`.',
            'Each company\'s landing has its own per-language texts ([Landing and login](/docs/landing#i18n)).',
        ] },
    ],
};

export default page;
