import type { DocPageContent } from '../types';

const ruleEx = `POST /api/rules
{
  "name": "Facturas a Finanzas",
  "enabled": true,
  "priority": 0,
  "conditions": {
    "match": "any",
    "items": [
      { "field": "from", "op": "contains", "value": "facturacion@" },
      { "field": "subject", "op": "regex", "value": "factura|invoice" },
      { "field": "hasAttachment", "value": true }
    ]
  },
  "actions": [ { "type": "addLabel", "labelId": "<id-de-etiqueta>" }, { "type": "markRead" } ],
  "stopProcessing": false
}`;

const ruleExEn = ruleEx.replace('Facturas a Finanzas', 'Invoices to Finance').replace('<id-de-etiqueta>', '<label-id>');

const searchEx = `from:ana subject:"informe mensual" has:attachment is:unread label:"Mis facturas" contrato`;

const page: DocPageContent = {
    es: [
        { t: 'p', text: 'Referencia de lo que el correo hace **hoy**. Donde una función no existe o solo existe a medias, se dice expresamente.' },
        { t: 'h2', id: 'rules', text: 'Reglas de correo' },
        { t: 'ul', items: [
            'Una regla tiene `name` (1–80), `enabled`, `priority` (entero −1000..1000; **menor número = se evalúa antes**), `conditions` como `{match: "all"|"any", items: [...]}` (por defecto `all`; también se acepta un arreglo simple), entre 1 y 20 condiciones y entre 1 y 10 acciones, y `stopProcessing`. Máximo **100 reglas** por usuario.',
            '**Condiciones**: `{field: from|to|subject|body, op: contains|regex|equals, value}` (valor de 1 a 500 caracteres, sin distinguir mayúsculas), `{field: "hasAttachment", value: boolean}` y `{field: "label", value}` (por id o nombre de etiqueta). Una regla sin condiciones nunca coincide.',
            '**Acciones**: `addLabel {labelId}`, `markRead`, `star`, `archive`, `delete` (mueve a la papelera, nunca borra de forma definitiva) y `moveToFolder {folder}` con `inbox|archive|trash|spam`.',
            'Cada regla se evalúa una vez contra el estado inicial del correo: las acciones no disparan otras reglas (sin cadenas ni bucles). Si varias reglas fijan carpeta, gana la de mayor prioridad. `stopProcessing: true` corta el procesamiento.',
            '**Regex de usuario**: máx. 200 caracteres; se rechazan referencias hacia atrás, lookahead/lookbehind, cuantificadores anidados y alternancias dentro de grupos cuantificados (protección contra ReDoS).',
            '**Cuándo se aplican**: al recibir un correo (después de las etiquetas por alias y regex); con "Aplicar ahora" (`POST /api/rules/apply`: últimos 500 correos de `inbox` y `archive`; ojo, aquí `body` se compara con el extracto, no con el cuerpo completo); y en el cron (catch-up de los últimos 2 días, lotes de 200). Una regla no saca de `spam` un correo que ya llegó como spam por cabeceras.',
            'Si las tablas `Rule`/`RuleRun` no existen, la lectura devuelve `[]` y la escritura responde 503 (ejecuta `npm run db:ensure`).',
            'Se gestionan en Ajustes → Reglas.',
        ] },
        { t: 'code', lang: 'json', title: 'Ejemplo de regla', code: ruleEx },
        { t: 'h2', id: 'labels', text: 'Etiquetas (labels)' },
        { t: 'ul', items: [
            'CRUD completo (`/api/labels`). Hasta **500** por usuario; nombre único por usuario (409 si se repite), máx. 50 caracteres, sin comas ni caracteres de control. Color `#RGB`/`#RRGGBB` (por defecto `#6366f1`).',
            '`aliasSuffix` (`^[a-z0-9][a-z0-9._-]{0,39}$`, único por usuario): etiqueta automáticamente lo enviado a `usuario+sufijo@dominio` (se ignoran los puntos y la parte `+` al comparar).',
            '`filterRegex`: si coincide con el asunto o el cuerpo, se añade la etiqueta (mismas validaciones que las reglas).',
            'Son **planas**: no hay etiquetas anidadas.',
            'El [Organizer](/docs/sealer#organizer) puede proponer o aplicar etiquetas con IA.',
        ] },
        { t: 'h2', id: 'search', text: 'Búsqueda con operadores' },
        { t: 'p', text: 'La barra de búsqueda admite operadores y texto libre, todo combinado con AND. Máximo 300 caracteres y 30 términos; los valores admiten comillas.' },
        { t: 'table', head: ['Operador', 'Significado'], rows: [
            ['`label:x`', 'Etiqueta con ese nombre (sin distinguir mayúsculas)'],
            ['`from:x`', 'El remitente contiene `x`'],
            ['`to:x`', 'Destinatarios (`to`) contienen `x`'],
            ['`subject:x`', 'El asunto contiene `x`'],
            ['`has:attachment`', 'Tiene adjuntos (único valor válido de `has:`)'],
            ['`is:unread`, `is:read`, `is:starred`', 'Estado. Pedir `unread` y `read` a la vez las anula'],
        ] },
        { t: 'code', lang: 'text', title: 'Ejemplo', code: searchEx },
        { t: 'ul', items: [
            'El texto libre usa **búsqueda de texto completo de PostgreSQL** (`websearch_to_tsquery`, configuración `simple`) sobre asunto, remitente y **extracto** (no sobre el cuerpo completo); si falla o no encuentra nada, cae a `ILIKE`.',
            'Con búsqueda, el alcance es global (todas las carpetas salvo papelera y spam). Resultados de 20 en 20.',
            '**No existen** los operadores `before:`, `after:`, `in:`, `filename:`, `cc:` ni `bcc:`. Cualquier otro `clave:valor` se trata como texto libre. Los rangos de fecha, remitente y "con adjuntos" están en el filtro avanzado de la interfaz (`since`, `until`, `from`, `hasAttachment`).',
        ] },
        { t: 'h2', id: 'compose', text: 'Redactar y enviar' },
        { t: 'ul', items: [
            '**Borradores**: autoguardado con retardo de 2 s, guardado al ocultar la pestaña o cerrar (`keepalive`), y solo se guardan adjuntos ya subidos. Indicador "Guardando… / Borrador guardado".',
            '**Límites de envío**: hasta 100 destinatarios (To+Cc+Bcc), asunto ≤ 998 caracteres, `MAX_SENDS_PER_HOUR` (200 por defecto) enviados por hora y usuario (429). El hook `EMAIL_PRE_SEND` puede bloquear (422) o modificar el contenido.',
            '**Adjuntos**: hasta 25 por correo; inline (base64) hasta 35 MB en total (413); por subida previa (`/api/upload`) hasta 200 MB por archivo. Extensiones peligrosas rechazadas y tipo real validado; antivirus opcional ([Seguridad](/docs/security#attachments)).',
            '**Reply/Reply-all/Forward**: responder a todos incluye Cc originales (con parsing correcto de nombres con comas y comillas) y reenviar copia los adjuntos con verificación de propiedad en el servidor.',
            '**Programar envío**: `scheduledAt` se pasa a Resend y el correo queda en la carpeta "Scheduled". No hay código que lo mueva a "Sent" al llegar la hora (no verificado). Cancelar un envío programado existe solo como API (`POST /api/emails/[id]/cancel`) **sin interfaz**.',
            '**Snooze**: solo existe la API (`POST /api/emails/[id]/snooze`), **sin interfaz**. La reactivación es perezosa al listar el correo.',
            '**Deshacer envío** con retardo: **no existe**.',
            '**Idempotencia**: `POST /api/emails` acepta `Idempotency-Key` (8–128 caracteres): un reintento devuelve `{duplicate:true}` y una petición concurrente responde 425. La interfaz de redacción no lo envía; sí la cola offline y Elixir.',
            '**Sellado**: envío con cifrado de extremo a extremo, ver [Sealer](/docs/sealer).',
        ] },
        { t: 'h2', id: 'contacts', text: 'Contactos' },
        { t: 'ul', items: [
            'Página `/contacts` con búsqueda en el servidor, "cargar más" y edición/borrado. Origen `local` o `google` (la sincronización con Google trae contactos con `source=google`; los locales conservan sus datos).',
            'API `/api/contacts` (límite 1000, `q` ≤ 100; cabeceras `X-Total-Count` y `X-Has-More`). Crear un contacto existente da **409** `CONTACT_EXISTS`.',
            'Sugerencias (`/api/contacts/suggestions?q=`, máx. 8): mezcla contactos y direcciones de los últimos 250 correos; las usan los campos Para/Cc/Cco.',
            'Importar/exportar CSV o vCard **no existe** en la interfaz.',
        ] },
        { t: 'h2', id: 'calendar', text: 'Calendario y citas' },
        { t: 'ul', items: [
            '**Calendario** (`/calendar`): vistas mes, semana y día; calendarios por defecto (el propio, "invitaciones compartidas" y festivos de solo lectura); eventos con asistentes que reciben invitación por correo (`.ics`) y aviso `.ics` de cancelación al borrar. No hay recurrencia (RRULE) al crear eventos.',
            '**RSVP** a invitaciones recibidas (aceptar / provisional / rechazar) responde con `.ics`. Disponibilidad de compañeros del **mismo dominio** de correo (`/api/calendar/domain-availability`).',
            '**Recordatorios** push de eventos que empiezan en los próximos 15 min (cron, cada 5 min como máximo; se desactivan con `calendarNotificationsEnabled=false`).',
            '**Google**: `POST /api/google/sync` es **unidireccional** (Google → local): calendarios, eventos (−30 a +180 días; los cancelados se borran) y contactos, con límites de páginas y una sola sincronización a la vez (409 `SYNC_IN_PROGRESS`). Meet en eventos vía la API de Meet con el token del usuario.',
            '**Citas** (`/appointments`, reserva pública `/book/<id>`): agendas con duración (15–120 min en la UI), zona horaria, disponibilidad semanal (por defecto lun–vie 09:00–17:00) y videollamada Meet o Zoom. Los huecos respetan la zona horaria y descartan lo ocupado (eventos y reservas). Reserva con límites (10/h por IP y 3/h por correo), bloqueo transaccional anti doble reserva (409) y correo de confirmación con `.ics`. Cancelación con enlace firmado que caduca al empezar la cita.',
        ] },
        { t: 'h2', id: 'offline', text: 'Offline y PWA' },
        { t: 'ul', items: [
            '**Service worker** (`sw.js`): cachea solo recursos estáticos (`/_next/static/*`, iconos y `/offline.html`; máx. 80 entradas). **Nunca** cachea `/api/*`, peticiones con `Authorization` ni páginas HTML. Sin red, las navegaciones muestran `/offline.html`.',
            '**Cola offline**: acciones por lote de la lista (`/api/emails/batch` y `/api/drafts/batch`) se guardan (máx. 200, hasta 8 intentos con backoff 2 s–5 min) y se reenvían con `Idempotency-Key` y el token de la cuenta que las originó. **Enviar un correo sin red no se encola.**',
            '**Caché de lectura**: IndexedDB por usuario. **Tiempo real**: `/api/sse` (máx. 3 conexiones por usuario, vida 50 s con reconexión por `Last-Event-ID`).',
            '**PWA**: `manifest` dinámico con nombre, logo y colores del dominio (`display: standalone`); avisos de instalación y de notificaciones una sola vez.',
            '**Push web** (VAPID): con `NEXT_PUBLIC_VAPID_PUBLIC_KEY` y `VAPID_PRIVATE_KEY`, o pares generados y guardados en la tabla `push_vapid_config`. Se notifica al recibir correo y en recordatorios.',
        ] },
        { t: 'h2', id: 'shortcuts', text: 'Atajos de teclado' },
        { t: 'p', text: 'Un único listener global, activo en la lista de correo. Se ignora si hay Ctrl/Meta/Alt, si el foco está en un campo de texto, si hay un diálogo abierto o durante una composición IME.' },
        { t: 'table', head: ['Tecla', 'Acción'], rows: [
            ['`c`', 'Redactar'],
            ['`/`', 'Enfocar el buscador (también en /docs)'],
            ['`j` / `k`', 'Siguiente / anterior'],
            ['`Enter` / `o`', 'Abrir el correo enfocado'],
            ['`r`', 'Responder'],
            ['`x`', 'Alternar selección'],
            ['`e`', 'Archivar'],
            ['`#`, `Delete`, `Backspace`', 'Mover a la papelera'],
            ['`Escape`', 'Cierra selector de etiquetas, luego limpia selección, luego cierra el correo, luego quita el foco'],
            ['`Ctrl/Cmd+Enter`', 'Enviar (en el editor de redacción)'],
        ] },
        { t: 'p', text: 'No existen secuencias tipo `g i`, ni `u`, `s`, `l`, `?`, ni ayuda de atajos, ni atajos de calendario o contactos.' },
        { t: 'h2', id: 'i18n', text: 'Idiomas (i18n)' },
        { t: 'ul', items: [
            'Idiomas: español (por defecto) e inglés. Resolución: cookie `bloomx-lang` → cabecera `Accept-Language` → español. `<html lang>` se actualiza sin recargar; el usuario cambia el idioma en Ajustes → Apariencia (y en el encabezado de /docs).',
            'Cliente: `const { t } = useI18n()`. Servidor: `getServerTranslator()`. Claves `t("seccion.clave", {param})`; si falta, se busca en español, luego inglés y, por último, se muestra la clave.',
            '**Añadir una clave**: en `src/lib/i18n/messages/es.ts` (define el tipo) y `en.ts` (tipado: exige las mismas claves). Un test comprueba las claves usadas en las pantallas migradas.',
            '**Añadir un idioma**: ampliar `LOCALES` y `LOCALE_LABELS` en `core.ts`, crear `messages/<xx>.ts` y registrarlo en `index.ts`; para la landing, ampliar además `LANDING_LOCALES` (espejo idéntico en el backend) y `landing-messages.ts`.',
            'La landing de cada empresa tiene sus textos por idioma ([Landing y login](/docs/landing#i18n)).',
        ] },
    ],
    en: [
        { t: 'p', text: 'Reference of what mail does **today**. Where a feature does not exist or only half exists, it says so explicitly.' },
        { t: 'h2', id: 'rules', text: 'Mail rules' },
        { t: 'ul', items: [
            'A rule has `name` (1–80), `enabled`, `priority` (integer −1000..1000; **lower number = evaluated first**), `conditions` as `{match: "all"|"any", items: [...]}` (default `all`; a plain array is also accepted), 1 to 20 conditions and 1 to 10 actions, and `stopProcessing`. At most **100 rules** per user.',
            '**Conditions**: `{field: from|to|subject|body, op: contains|regex|equals, value}` (value 1 to 500 characters, case-insensitive), `{field: "hasAttachment", value: boolean}` and `{field: "label", value}` (by label id or name). A rule without conditions never matches.',
            '**Actions**: `addLabel {labelId}`, `markRead`, `star`, `archive`, `delete` (moves to trash, never permanently deletes) and `moveToFolder {folder}` with `inbox|archive|trash|spam`.',
            'Each rule is evaluated once against the message\'s initial state: actions do not trigger other rules (no chains or loops). If several rules set the folder, the highest priority wins. `stopProcessing: true` cuts processing short.',
            '**User regex**: max 200 characters; back-references, lookahead/lookbehind, nested quantifiers and alternation inside quantified groups are rejected (ReDoS protection).',
            '**When applied**: on receiving a message (after alias and regex labels); with "Apply now" (`POST /api/rules/apply`: the last 500 messages of `inbox` and `archive`; note that here `body` is compared with the snippet, not the full body); and in the cron (catch-up over the last 2 days, batches of 200). A rule does not pull a message out of `spam` if it already arrived as spam from headers.',
            'If the `Rule`/`RuleRun` tables do not exist, reads return `[]` and writes answer 503 (run `npm run db:ensure`).',
            'Managed in Settings → Rules.',
        ] },
        { t: 'code', lang: 'json', title: 'Example rule', code: ruleExEn },
        { t: 'h2', id: 'labels', text: 'Labels' },
        { t: 'ul', items: [
            'Full CRUD (`/api/labels`). Up to **500** per user; unique name per user (409 if repeated), max 50 characters, no commas or control characters. Colour `#RGB`/`#RRGGBB` (default `#6366f1`).',
            '`aliasSuffix` (`^[a-z0-9][a-z0-9._-]{0,39}$`, unique per user): automatically labels anything sent to `user+suffix@domain` (dots and the `+` part are ignored when comparing).',
            '`filterRegex`: if it matches the subject or body the label is added (same validations as rules).',
            'They are **flat**: there are no nested labels.',
            'The [Organizer](/docs/sealer#organizer) can propose or apply labels with AI.',
        ] },
        { t: 'h2', id: 'search', text: 'Search with operators' },
        { t: 'p', text: 'The search bar accepts operators and free text, all combined with AND. Max 300 characters and 30 terms; values accept quotes.' },
        { t: 'table', head: ['Operator', 'Meaning'], rows: [
            ['`label:x`', 'Label with that name (case-insensitive)'],
            ['`from:x`', 'The sender contains `x`'],
            ['`to:x`', 'Recipients (`to`) contain `x`'],
            ['`subject:x`', 'The subject contains `x`'],
            ['`has:attachment`', 'Has attachments (the only valid `has:` value)'],
            ['`is:unread`, `is:read`, `is:starred`', 'State. Asking for `unread` and `read` together cancels them'],
        ] },
        { t: 'code', lang: 'text', title: 'Example', code: searchEx },
        { t: 'ul', items: [
            'Free text uses **PostgreSQL full-text search** (`websearch_to_tsquery`, `simple` configuration) over subject, sender and **snippet** (not the full body); if it fails or finds nothing, it falls back to `ILIKE`.',
            'With a search, the scope is global (all folders except trash and spam). Results 20 at a time.',
            'The operators `before:`, `after:`, `in:`, `filename:`, `cc:` and `bcc:` **do not exist**. Any other `key:value` is treated as free text. Date ranges, sender and "with attachments" live in the UI\'s advanced filter (`since`, `until`, `from`, `hasAttachment`).',
        ] },
        { t: 'h2', id: 'compose', text: 'Composing and sending' },
        { t: 'ul', items: [
            '**Drafts**: autosave with a 2 s delay, saved on tab hide or close (`keepalive`), and only already-uploaded attachments are saved. "Saving… / Draft saved" indicator.',
            '**Send limits**: up to 100 recipients (To+Cc+Bcc), subject ≤ 998 characters, `MAX_SENDS_PER_HOUR` (200 by default) sends per hour per user (429). The `EMAIL_PRE_SEND` hook can block (422) or modify the content.',
            '**Attachments**: up to 25 per message; inline (base64) up to 35 MB in total (413); via prior upload (`/api/upload`) up to 200 MB per file. Dangerous extensions rejected and real type validated; optional antivirus ([Security](/docs/security#attachments)).',
            '**Reply/Reply-all/Forward**: reply-all includes original Cc (with correct parsing of names with commas and quotes) and forward copies attachments with server-side ownership checks.',
            '**Scheduled send**: `scheduledAt` is passed to Resend and the message sits in the "Scheduled" folder. No code moves it to "Sent" when the time comes (not verified). Cancelling a scheduled send exists only as an API (`POST /api/emails/[id]/cancel`) **without UI**.',
            '**Snooze**: only the API exists (`POST /api/emails/[id]/snooze`), **without UI**. Wake-up is lazy when listing mail.',
            '**Undo send** with a delay: **does not exist**.',
            '**Idempotency**: `POST /api/emails` accepts `Idempotency-Key` (8–128 characters): a retry returns `{duplicate:true}` and a concurrent request answers 425. The compose UI does not send it; the offline queue and Elixir do.',
            '**Sealed**: end-to-end encrypted sending, see [Sealer](/docs/sealer).',
        ] },
        { t: 'h2', id: 'contacts', text: 'Contacts' },
        { t: 'ul', items: [
            '`/contacts` page with server-side search, "load more" and edit/delete. Source `local` or `google` (Google sync brings contacts with `source=google`; local ones keep their data).',
            '`/api/contacts` API (limit 1000, `q` ≤ 100; `X-Total-Count` and `X-Has-More` headers). Creating an existing contact gives **409** `CONTACT_EXISTS`.',
            'Suggestions (`/api/contacts/suggestions?q=`, max 8): mixes contacts and addresses from the last 250 messages; used by the To/Cc/Bcc fields.',
            'Importing/exporting CSV or vCard **does not exist** in the UI.',
        ] },
        { t: 'h2', id: 'calendar', text: 'Calendar and appointments' },
        { t: 'ul', items: [
            '**Calendar** (`/calendar`): month, week and day views; default calendars (your own, "shared invites" and read-only holidays); events with attendees who receive an email invitation (`.ics`) and a cancellation `.ics` on delete. No recurrence (RRULE) when creating events.',
            '**RSVP** to received invitations (accept / tentative / decline) answers with `.ics`. Availability of colleagues from the **same mail domain** (`/api/calendar/domain-availability`).',
            'Push **reminders** for events starting within 15 min (cron, at most every 5 min; disable with `calendarNotificationsEnabled=false`).',
            '**Google**: `POST /api/google/sync` is **one-way** (Google → local): calendars, events (−30 to +180 days; cancelled ones are removed) and contacts, with page limits and one sync at a time (409 `SYNC_IN_PROGRESS`). Meet on events through the Meet API with the user\'s token.',
            '**Appointments** (`/appointments`, public booking `/book/<id>`): schedules with duration (15–120 min in the UI), time zone, weekly availability (default Mon–Fri 09:00–17:00) and Meet or Zoom video call. Slots respect the time zone and discard what is busy (events and bookings). Booking with limits (10/h per IP and 3/h per email), transactional anti-double-booking lock (409) and a confirmation email with `.ics`. Cancellation through a signed link that expires when the appointment starts.',
        ] },
        { t: 'h2', id: 'offline', text: 'Offline and PWA' },
        { t: 'ul', items: [
            '**Service worker** (`sw.js`): caches only static resources (`/_next/static/*`, icons and `/offline.html`; max 80 entries). It **never** caches `/api/*`, requests with `Authorization` or HTML pages. Offline, navigations show `/offline.html`.',
            '**Offline queue**: list batch actions (`/api/emails/batch` and `/api/drafts/batch`) are stored (max 200, up to 8 attempts with 2 s–5 min backoff) and resent with `Idempotency-Key` and the token of the account that originated them. **Sending an email offline is not queued.**',
            '**Read cache**: per-user IndexedDB. **Real time**: `/api/sse` (max 3 connections per user, 50 s lifetime with reconnect through `Last-Event-ID`).',
            '**PWA**: dynamic `manifest` with the domain\'s name, logo and colours (`display: standalone`); install and notification prompts shown only once.',
            '**Web push** (VAPID): with `NEXT_PUBLIC_VAPID_PUBLIC_KEY` and `VAPID_PRIVATE_KEY`, or pairs generated and stored in the `push_vapid_config` table. Notifies on incoming mail and reminders.',
        ] },
        { t: 'h2', id: 'shortcuts', text: 'Keyboard shortcuts' },
        { t: 'p', text: 'A single global listener, active in the mail list. It is ignored with Ctrl/Meta/Alt, when focus is in a text field, when a dialog is open or during IME composition.' },
        { t: 'table', head: ['Key', 'Action'], rows: [
            ['`c`', 'Compose'],
            ['`/`', 'Focus the search box (also in /docs)'],
            ['`j` / `k`', 'Next / previous'],
            ['`Enter` / `o`', 'Open the focused message'],
            ['`r`', 'Reply'],
            ['`x`', 'Toggle selection'],
            ['`e`', 'Archive'],
            ['`#`, `Delete`, `Backspace`', 'Move to trash'],
            ['`Escape`', 'Closes label picker, then clears selection, then closes the message, then removes focus'],
            ['`Ctrl/Cmd+Enter`', 'Send (in the compose editor)'],
        ] },
        { t: 'p', text: 'There are no `g i`-style sequences, no `u`, `s`, `l`, `?`, no shortcut help and no calendar or contacts shortcuts.' },
        { t: 'h2', id: 'i18n', text: 'Languages (i18n)' },
        { t: 'ul', items: [
            'Languages: Spanish (default) and English. Resolution: `bloomx-lang` cookie → `Accept-Language` header → Spanish. `<html lang>` updates without reload; users change language in Settings → Appearance (and in the /docs header).',
            'Client: `const { t } = useI18n()`. Server: `getServerTranslator()`. Keys `t("section.key", {param})`; if missing, Spanish is tried, then English and, finally, the key itself is shown.',
            '**Adding a key**: in `src/lib/i18n/messages/es.ts` (defines the type) and `en.ts` (typed: requires the same keys). A test checks the keys used in migrated screens.',
            '**Adding a language**: extend `LOCALES` and `LOCALE_LABELS` in `core.ts`, create `messages/<xx>.ts` and register it in `index.ts`; for the landing, also extend `LANDING_LOCALES` (identical mirror on the backend) and `landing-messages.ts`.',
            'Each company\'s landing has its own per-language texts ([Landing and login](/docs/landing#i18n)).',
        ] },
    ],
};

export default page;
