import type { DocPageContent } from '../types';

const ddl = `CREATE TABLE IF NOT EXISTS "MailTransferJob" (
  "id" TEXT NOT NULL, "userId" TEXT NOT NULL, "actorKind" TEXT NOT NULL DEFAULT 'user', "domain" TEXT NOT NULL DEFAULT '',
  "kind" TEXT NOT NULL, "scope" TEXT NOT NULL DEFAULT 'domain', "targetUserId" TEXT, "format" TEXT NOT NULL DEFAULT 'unknown',
  "status" TEXT NOT NULL DEFAULT 'created', "phase" TEXT NOT NULL DEFAULT '', "fileName" TEXT,
  "options" JSONB NOT NULL DEFAULT '{}', "summary" JSONB NOT NULL DEFAULT '{}', "cursor" JSONB NOT NULL DEFAULT '{}',
  "totalBytes" BIGINT NOT NULL DEFAULT 0, "uploadedBytes" BIGINT NOT NULL DEFAULT 0, "totalItems" INTEGER NOT NULL DEFAULT 0,
  "doneItems" INTEGER NOT NULL DEFAULT 0, "importedItems" INTEGER NOT NULL DEFAULT 0, "duplicateItems" INTEGER NOT NULL DEFAULT 0,
  "skippedItems" INTEGER NOT NULL DEFAULT 0, "errorItems" INTEGER NOT NULL DEFAULT 0, "bytesProcessed" BIGINT NOT NULL DEFAULT 0,
  "outputBytes" BIGINT NOT NULL DEFAULT 0, "outputSha256" TEXT, "lockedUntil" TIMESTAMPTZ, "lastError" TEXT,
  "cancelRequested" BOOLEAN NOT NULL DEFAULT FALSE, "downloadedAt" TIMESTAMPTZ, "expiresAt" TIMESTAMPTZ,
  "startedAt" TIMESTAMPTZ, "finishedAt" TIMESTAMPTZ, "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "MailTransferJob_pkey" PRIMARY KEY ("id")
);
CREATE TABLE IF NOT EXISTS "MailTransferItem" (
  "id" BIGSERIAL NOT NULL, "jobId" TEXT NOT NULL, "mailbox" TEXT NOT NULL DEFAULT '', "sourceKey" TEXT NOT NULL,
  "messageId" TEXT, "status" TEXT NOT NULL DEFAULT 'pending', "error" TEXT, "emailId" TEXT, "folder" TEXT,
  "bytes" BIGINT NOT NULL DEFAULT 0, "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "MailTransferItem_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "MailTransferItem_jobId_fkey" FOREIGN KEY ("jobId") REFERENCES "MailTransferJob"("id") ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "MailTransferItem_jobId_sourceKey_key" ON "MailTransferItem" ("jobId","sourceKey");
CREATE INDEX IF NOT EXISTS "MailTransferItem_jobId_status_idx" ON "MailTransferItem" ("jobId","status");
CREATE INDEX IF NOT EXISTS "MailTransferJob_userId_createdAt_idx" ON "MailTransferJob" ("userId","createdAt" DESC);
CREATE INDEX IF NOT EXISTS "MailTransferJob_domain_status_idx" ON "MailTransferJob" ("domain","status");
CREATE INDEX IF NOT EXISTS "MailTransferJob_status_updatedAt_idx" ON "MailTransferJob" ("status","updatedAt");`;

const page: DocPageContent = {
    es: [
        { t: 'p', text: 'La consola de administración (**Importar / Exportar**) y **Ajustes > Mi buzón** mueven correo entre BloomX y otros proveedores (Gmail, Titan, Outlook/Hotmail, Thunderbird, Apple Mail) con formatos estándar. Es la función que más contenido ajeno mueve de toda la aplicación, así que está muy acotada: ver [Salvaguardas](#safeguards).' },
        { t: 'h2', id: 'formats', text: 'Formatos' },
        { t: 'table', head: ['Formato', 'Importar', 'Exportar', 'Notas'], rows: [
            ['MBOX (mboxrd)', 'Sí', 'Sí', 'Google Takeout (`X-Gmail-Labels`), Thunderbird (`X-Mozilla-Status`, `X-Mozilla-Keys`), Apple Mail, Titan. Una línea `From ` solo separa mensajes si va tras una línea en blanco y antes de una cabecera; el resto se desescapa (`>From`). Al exportar: un `.mbox` por buzón y carpeta, en partes de hasta 32 MB.'],
            ['EML suelto / ZIP de EML', 'Sí', 'Sí', 'Estructura `buzón@dominio/Carpeta/…` o un buzón único elegido. La carpeta de usuario pasa a **archivo + etiqueta**.'],
            ['ZIP con `.mbox`, `.eml` o Maildir', 'Sí', 'Sí (ZIP)', 'Maildir: `cur/new/tmp` y banderas del nombre (`:2,RS`); Maildir++ (`.Sent`). También archivos sin extensión (Thunderbird) por contenido.'],
            ['GZ / TGZ / TAR', 'Sí', 'No', '`.mbox.gz`, Takeout `.tgz`. Se descomprime por trozos con tope.'],
            ['PST (Outlook/Hotmail)', 'Sí, hasta `MAIL_TRANSFER_PST_MAX_MB` (2048)', 'No', 'Con `pst-extractor` (JS puro, MIT), **leído por rangos** (caché LRU de trozos de 4 MiB; no se copia a /tmp). Carpetas, mensajes, adjuntos y mensajes incrustados (como `.eml`, 3 niveles); se convierten a mbox por lotes. Probado con 3 PST/OST reales y un PST generado por código (`pst-testkit`, sin CRC: válido para `pst-extractor`, no garantizado para Outlook); **no** con un PST real de varios GB.'],
            ['`.emlx` (Apple Mail)', 'Sí (suelto o en ZIP)', 'No', 'Longitud + mensaje RFC 822 + plist de banderas (leído, marcado, borrador...). El DOCTYPE estándar del plist se elimina; cualquier otro DOCTYPE/ENTITY se rechaza.'],
            ['`.msg` (Outlook)', 'Sí (suelto o en ZIP)', 'No', 'Con `@kenjiuno/msgreader` (Apache-2.0). Cabeceras de transporte (lista blanca), destinatarios, cuerpo texto/HTML/RTF, adjuntos y `.msg` incrustados (como `.eml`, 3 niveles).'],
            ['`.olm` (Outlook para Mac)', 'Sí', 'No', 'ZIP con un XML por mensaje (`com.microsoft.__Messages/…`), leído con un parser XML propio sin DTD/entidades. **Validado con `.olm` sintéticos según la estructura documentada; no hay un `.olm` real en las pruebas.**'],
            ['ZIP con contraseña', 'Sí (ZipCrypto y WinZip AES-128/192/256)', 'No', 'El asistente pide la contraseña; se comprueba y se guarda **cifrada** con la clave de la instancia solo hasta expandir las entradas cifradas, y se borra. Verificado contra 7-Zip e Info-ZIP. No se instaló `@zip.js/zip.js` (8,5 MB, duplica fflate y saltaría los límites anti zip-bomb).'],
            ['Borradores', 'Sí', 'Sí', 'Export: `Drafts.mbox` (o `Drafts/*.eml`) con `X-Bloomx-Draft: 1`. Import: la marca, la etiqueta `Drafts` de Gmail, una carpeta Borradores o la bandera `D` de Maildir crean filas en `Draft` del usuario (no correo).'],
            ['Contactos `.vcf`', 'Sí', 'Sí (`contacts.vcf`, vCard 4.0)', 'Dedupe por correo sin sobrescribir. El modelo solo guarda correo, nombre y notas: teléfonos, organización, direcciones… van a `notes` en líneas etiquetadas.'],
            ['Calendario `.ics`', 'Sí', 'Sí (`calendar.ics`)', 'Asistentes, zonas horarias (IANA, tabla de Windows, `VTIMEZONE`), excepciones. El modelo no tiene recurrencia: la `RRULE` se conserva como texto en `description` **y** se expanden las ocurrencias (hasta 500) como eventos.'],
            ['Filtros de Gmail `mailFilters.xml`', 'Sí', 'Sí (`mailFilters.xml`)', 'A reglas de `src/lib/rules`. Sin negación en el motor: `doesNotHaveTheWord`, tamaño, importancia, categorías, `forwardTo` y `shouldNeverSpam` van al informe como *filtro no convertible* (nunca se crea un reenvío automático).'],
            ['`manifest.json`', 'Se ignora', 'Sí', 'Buzones, carpetas, etiquetas, conteos, fechas, origen del MIME (`mimeSource`) y `sha256` de cada archivo.'],
        ] },
        { t: 'p', text: 'El formato se detecta **por contenido** (firmas `PK`, gzip, `!BDN`, OLE, `ustar`, línea de longitud de `.emlx`, `BEGIN:VCARD` / `BEGIN:VCALENDAR`, línea `From ` + cabecera, cabeceras RFC 822), no por la extensión.' },
        { t: 'callout', kind: 'warn', title: 'No se admite', text: 'PST cifrados o dañados (la librería no los lee), ZIP con cifrado fuerte por certificado, y ZIP cuyas entradas usan contraseñas distintas (el trabajo falla con `zip_wrong_password`). El paquete cifrado de BloomX (`BLMXENC1`) debe descifrarse antes de reimportarlo (`scripts/bloomx-decrypt.mjs`).' },
        { t: 'h2', id: 'extraction', text: 'Fase de extracción (ZIP y GZ grandes)' },
        { t: 'ul', items: [
            'Las entradas deflate de más de 16 MiB, las entradas cifradas y los `.gz`/`.tgz` se **expanden antes de importar** a trozos de 4 MiB (`x/<entrada>/NNNNNN`) con inflate en trozos de 16 KiB: nunca se carga una entrada entera en memoria. La importación lee luego esos trozos con un cursor por offset.',
            '**Reanudable**: al agotarse el presupuesto del tick (`MAIL_TRANSFER_BUDGET_MS`) se guarda la cola y el estado del escritor en el cursor. Deflate no se puede retomar a mitad de flujo, así que el siguiente tick **re-infla el prefijo ya escrito sin escribirlo** (solo CPU, cientos de MB/s) y sigue desde ahí; cada byte se escribe una sola vez y el tiempo de re-inflado no cuenta contra el presupuesto de escritura. Si el proceso muere entre escribir y guardar el cursor, se reanuda del último checkpoint y los trozos se reescriben de forma determinista.',
            '**Coste documentado**: reanudar una entrada de N bytes cuesta re-inflar N bytes (CPU). Con el tope por entrada de 1 GiB son unos segundos; un `.gz` único de decenas de GB repite hasta ese prefijo en cada tick (por eso avanza al menos un trozo de 4 MiB por tick y el latido de bloqueo se mantiene mientras se re-infla).',
        ] },
        { t: 'h2', id: 'mapping', text: 'Carpetas, etiquetas y banderas' },
        { t: 'ul', items: [
            'Prioridad: `X-Bloomx-Folder` (exportaciones propias) > `X-Gmail-Labels` > banderas (`X-Mozilla-Status` borrado, `junk`) > carpeta de la ruta > Recibidos.',
            'Gmail: `Inbox`/`Recibidos`, `Sent`/`Enviados`, `Trash`/`Papelera`, `Spam` pasan a carpetas propias; `Starred` = destacado; `Unread` = no leído; las demás etiquetas se crean como **Label del usuario** si no existen.',
            'Leído/destacado: `Status`/`X-Status` (`RO`, `F`), `X-Mozilla-Status`, `X-Bloomx-Flags`. Sin datos: se importa como leído.',
            'La fecha del correo es la **original** (cabecera `Date`, o la línea `From ` si falta); un futuro absurdo se acota a "ahora". Si la columna `Email.previousFolder` existe, papelera/spam la rellenan con `inbox`.',
            'Se guardan con el mismo esquema que la ingesta normal (`emails/<fecha>/<uuid>/…`), así que la retención y el borrado completo funcionan igual.',
            '**No** se ejecutan reglas ni hooks `EMAIL_RECEIVED`, no hay notificaciones push y no se envía ningún correo.',
        ] },
        { t: 'h2', id: 'missing', text: 'Buzones que no existen' },
        { t: 'p', text: 'En la vista previa se listan las direcciones detectadas (`X-Bloomx-Mailbox`, ruta del ZIP, `From` en enviados, `Delivered-To` / `X-Original-To`, `To`/`Cc`) con su estado: **existe**, **no existe** o **dominio ajeno**. Si faltan, un diálogo accesible pregunta «¿Desea crear los correos faltantes?»: cada dirección se crea (solo con dominio de la instancia: `TOP_DOMAIN`, host de `NEXT_PUBLIC_APP_URL` o `MAIL_TRANSFER_ALLOWED_DOMAINS`), se mapea a un buzón existente o se descarta. Contraseña **aleatoria única por usuario** (recomendada) o **genérica** (política de 12+ caracteres, con medidor) y «obligar a cambiar la contraseña en el primer inicio» (`mustChangePassword`, activada por defecto). Nada se crea hasta confirmar el resumen escribiendo el dominio. Se usa la misma función que el alta de usuarios de la consola (`createUserAccount`, hash bcrypt). Las credenciales generadas se devuelven **una sola vez** al navegador, que las descarga como CSV; nunca se guardan en claro ni se registran.' },
        { t: 'h2', id: 'jobs', text: 'Diseño de los trabajos' },
        { t: 'ul', items: [
            '**Subida por trozos reanudable**: 4 MiB por petición (cabe en el límite de 4,5 MB de Vercel), `PUT /jobs/:id/chunks/:n` con `x-chunk-sha256` verificado en el servidor; `GET …/chunks` dice qué trozos hay para reanudar; `POST …/complete` comprueba que están todos y guarda un digest del conjunto. Nunca se ensambla el archivo: se lee por rangos.',
            '**Segundo plano por lotes** (patrón del worker de Elixir): estados `created → uploading → analyzing → ready → queued → running → done|failed|canceled|expired`. Cada tick bloquea el trabajo (`lockedUntil`), avanza ~45 s y guarda un cursor (entrada + desplazamiento del mensaje). Se encadena con `after()` + `POST /api/cron/mail-transfer` (Bearer `CRON_SECRET` o clave interna), el cron diario de `vercel.json` y el **empuje desde el navegador** (`POST /jobs/:id/tick`) si el sondeo detecta que se atascó.',
            '**Idempotente**: cada mensaje tiene clave de origen (`entrada:offset`) y el `messageId` guardado es el esquema por usuario del webhook (`<Message-ID>-<userId>`, único). Reintentar, reanudar tras una caída o reimportar no duplica, ni siquiera con dos trabajos a la vez. Los contadores salen de contar `MailTransferItem`.',
            '**Exportación**: por buzón y carpeta, con paginación por clave (fecha, id), escribiendo el ZIP por trozos (entradas completas con CRC conocido, directorio central en objetos aparte, ZIP64 si hace falta). Las colas de los escritores están versionadas, así que una caída entre escribir y guardar el cursor se reanuda sin corromper el paquete.',
            'Descarga: enlace firmado (HMAC) ligado al trabajo **y** al administrador, 10 min de vida, más la sesión del mismo actor; «descargar una vez» reclama el archivo de forma atómica y una descarga interrumpida no lo consume. Caduca a las 24 h (`MAIL_TRANSFER_EXPORT_TTL_HOURS`) y la retención lo borra del storage.',
            'Informe CSV descargable: importados, duplicados omitidos y errores con motivo (sin contenido).',
        ] },
        { t: 'h2', id: 'encryption', text: 'Cifrado del paquete' },
        { t: 'p', text: 'Opcional: contenedor `BLMXENC1` = cabecera de 37 bytes (magic, versión, KDF scrypt N=2^15 r=8 p=1, sal de 16 B, prefijo de nonce, tamaño de registro) + registros AES-256-GCM de 1 MiB (nonce = prefijo ‖ contador, AAD = cabecera ‖ byte final) + un registro final vacío obligatorio (detecta truncado). La contraseña no se guarda; mientras dura el trabajo el servidor conserva solo la **clave derivada cifrada con la clave de datos** y la borra al terminar. Para abrirlo:' },
        { t: 'code', lang: 'bash', title: 'Descifrar', code: "node scripts/bloomx-decrypt.mjs paquete.zip.bmx paquete.zip\n# o BLOOMX_PACKAGE_PASSWORD='…' node scripts/bloomx-decrypt.mjs paquete.zip.bmx paquete.zip" },
        { t: 'h2', id: 'safeguards', text: 'Salvaguardas' },
        { t: 'ul', items: [
            'Solo `requireAdmin` (dueño del dominio o `ADMIN_EMAILS` con MFA). «Mi buzón» exige sesión y solo toca el buzón del propio usuario (ni crea usuarios ni ve trabajos ajenos).',
            '**Re-autenticación reciente** (10 min: contraseña o código MFA; vale también una sesión con MFA verificado hace menos de 10 min) para crear importaciones, confirmar, exportar y generar enlaces de descarga. Prueba en cookie httpOnly `SameSite=Strict` ligada al administrador. Un administrador sin MFA puede reingresar la contraseña; el diálogo le recomienda activar MFA.',
            '**Confirmación escribiendo el nombre del dominio**, `rateLimitAsync` por endpoint, tope de trabajos concurrentes por dominio (`MAIL_TRANSFER_MAX_CONCURRENT`, 2) y propiedad estricta: un trabajo solo lo ve quien lo creó y en su dominio (404 en otro caso).',
            'Auditoría (`admin.mail_transfer.*`): administrador, alcance, nº de buzones y mensajes, bytes, sha256 e IP. **Nunca** contenido, asuntos, contraseñas ni claves.',
            'Aviso opcional por correo a los usuarios afectados.',
            'Adjuntos validados con `file-type` (magic bytes) y el antivirus opcional (`av-hook`) como en la ingesta normal; ejecutables y HTML activo se bloquean o sanean. Cabeceras saneadas (sin CR/LF ni control) al leer y al generar.',
            '**ZIP**: nombres normalizados (sin `..`, rutas absolutas, unidad, NUL), enlaces simbólicos y entradas cifradas omitidos, tope de entradas, tamaño por entrada y total, razón de compresión, y **se cuentan los bytes realmente inflados** (una cabecera que miente aborta). Se infla en trozos de 16 KiB. No se escribe nada en el sistema de ficheros.',
            'Memoria acotada: mbox por streaming (mensajes de más de `MAIL_TRANSFER_MAX_MESSAGE_MB` = 50 se descartan sin acumular), PST mensaje a mensaje. Los archivos subidos se borran al terminar el trabajo (o a las 48 h si se abandona).',
            'Las rutas del storage no se exponen: solo ids de trabajo y enlaces firmados.',
        ] },
        { t: 'h2', id: 'env', text: 'Variables' },
        { t: 'table', head: ['Variable', 'Por defecto', 'Efecto'], rows: [
            ['`MAIL_TRANSFER_ALLOWED_DOMAINS`', '(vacía)', 'Dominios extra donde se pueden crear buzones. Sin `TOP_DOMAIN`, se usan los dominios de `ADMIN_EMAILS`.'],
            ['`MAIL_TRANSFER_MAX_UPLOAD_MB`', '16384', 'Tamaño máximo del archivo subido'],
            ['`MAIL_TRANSFER_MAX_MESSAGE_MB`', '50', 'Mensaje mayor: error `too_large`'],
            ['`MAIL_TRANSFER_MAX_ATTACHMENTS`', '100', 'Adjuntos por mensaje'],
            ['`MAIL_TRANSFER_MAX_CONCURRENT`', '2', 'Trabajos activos por dominio'],
            ['`MAIL_TRANSFER_BUDGET_MS`', '45000', 'Duración de cada tick'],
            ['`MAIL_TRANSFER_PST_MAX_MB`', '2048', 'Tope de PST (lectura por rangos, sin copiar a /tmp; medido hasta 640 MiB)'],
            ['`MAIL_TRANSFER_EXPORT_TTL_HOURS`', '24', 'Caducidad del paquete'],
            ['`RAW_MIME_MAX_MB`', '25', 'Tamaño máximo del MIME original guardado como `raw.eml`'],
            ['`MAIL_STORE_RAW_MIME`', '(activo)', '`false` desactiva el guardado de `raw.eml`'],
            ['`MAIL_TRANSFER_MAX_CONTACTS` / `_MAX_EVENTS`', '20000 / 50000', 'Contactos y eventos importados por buzón'],
            ['`MAIL_TRANSFER_MAX_EXPANDED_GB`', '40', 'Tope de descompresión (zip-bomb)'],
        ] },
        { t: 'h2', id: 'ddl', text: 'Tablas' },
        { t: 'p', text: 'Aditivas, creadas por `db:ensure` (también en `prisma/schema.prisma`). Sin ellas las rutas devuelven 503 `mail_transfer_tables_missing`.' },
        { t: 'code', lang: 'sql', title: 'DDL', code: ddl },
        { t: 'h2', id: 'rawmime', text: 'MIME original al exportar' },
        { t: 'ul', items: [
            '`process-attachments` ya descarga el MIME crudo de Resend: ahora lo guarda también como `raw.eml` junto a `raw.json` si `MAIL_STORE_RAW_MIME` no es `false` y pesa como máximo `RAW_MIME_MAX_MB` (25). `Email.rawKey` **sigue apuntando a `raw.json`** (otras rutas lo parsean como JSON); la clave de `raw.eml` se deriva de ella (`src/lib/raw-mime.ts`).',
            'La exportación prefiere `raw.eml` (cabeceras exactas: `Received`, `Authentication-Results`, `DKIM-Signature`…) y le antepone las cabeceras de carpeta, etiquetas y banderas. Para correos anteriores intenta `Email.rawMimeUrl` (solo https público, IP privada bloqueada, timeout 4 s, tope de tamaño; sin bloquear) y cae a la reconstrucción. Con «sin adjuntos» siempre se reconstruye. El `manifest.json` cuenta cuántos salieron de cada origen.',
            'Retención: el borrado completo y la política `raw` incluyen `raw.eml` (y no lo borran si otro destinatario del mismo mensaje aún lo usa). Coste: hasta 25 MB extra por mensaje; desactívalo con `MAIL_STORE_RAW_MIME=false`.',
        ] },
        { t: 'h2', id: 'limits', text: 'Límites conocidos' },
        { t: 'ul', items: [
            'Verificado con Postgres embebido, almacenamiento local y un servidor **compatible S3 local** (`scripts/fake-s3.mjs`: multipart, Range, ListObjectsV2 paginado, DeleteObjects por lotes de 1000, firma SigV4). **No** contra S3/B2 reales: la aceptación de checksums, firmas y límites del proveedor solo se confirma con él (se usa `WHEN_REQUIRED` para los checksums del SDK).',
            'Rendimiento medido con `scripts/bench-mail-transfer.mjs` (ver la cabecera del script); la importación está limitada por Postgres y por escribir 3–4 objetos por mensaje, no por memoria.',
            '`.olm`: no hay un archivo real en las pruebas (ver tabla).',
        ] },
    ],
    en: [
        { t: 'p', text: 'The admin console (**Import / Export**) and **Settings > My mailbox** move mail between BloomX and other providers (Gmail, Titan, Outlook/Hotmail, Thunderbird, Apple Mail) using standard formats. It moves more third-party content than any other feature, so it is tightly bounded: see [Safeguards](#safeguards).' },
        { t: 'h2', id: 'formats', text: 'Formats' },
        { t: 'table', head: ['Format', 'Import', 'Export', 'Notes'], rows: [
            ['MBOX (mboxrd)', 'Yes', 'Yes', 'Google Takeout (`X-Gmail-Labels`), Thunderbird (`X-Mozilla-Status`, `X-Mozilla-Keys`), Apple Mail, Titan. A `From ` line only splits messages after a blank line and before a header; the rest is unescaped (`>From`). Export: one `.mbox` per mailbox and folder, in parts of up to 32 MB.'],
            ['Loose EML / EML ZIP', 'Yes', 'Yes', '`mailbox@domain/Folder/…` layout or a single chosen mailbox. User folders become **archive + label**.'],
            ['ZIP with `.mbox`, `.eml` or Maildir', 'Yes', 'Yes (ZIP)', 'Maildir: `cur/new/tmp` and filename flags (`:2,RS`); Maildir++ (`.Sent`). Extension-less files (Thunderbird) are identified by content.'],
            ['GZ / TGZ / TAR', 'Yes', 'No', '`.mbox.gz`, Takeout `.tgz`. Decompressed in chunks with a cap.'],
            ['PST (Outlook/Hotmail)', 'Yes, up to `MAIL_TRANSFER_PST_MAX_MB` (2048)', 'No', 'With `pst-extractor` (pure JS, MIT), **read by ranges** (LRU cache of 4 MiB chunks; not copied to /tmp). Folders, messages, attachments and embedded messages (as `.eml`, 3 levels); converted to mbox in batches. Tested with 3 real PST/OST files and a code-generated PST (`pst-testkit`, no CRC: valid for `pst-extractor`, not guaranteed for Outlook); **not** with a real multi-GB PST.'],
            ['`.emlx` (Apple Mail)', 'Yes (loose or in ZIP)', 'No', 'Length line + RFC 822 message + flags plist. Only the standard plist DOCTYPE is stripped; any other DOCTYPE/ENTITY is rejected.'],
            ['`.msg` (Outlook)', 'Yes (loose or in ZIP)', 'No', 'With `@kenjiuno/msgreader` (Apache-2.0). Transport headers (allow-list), recipients, text/HTML/RTF body, attachments and embedded `.msg` (as `.eml`, 3 levels).'],
            ['`.olm` (Outlook for Mac)', 'Yes', 'No', 'ZIP with one XML per message, read by our own DTD-free/entity-free XML parser. **Validated with synthetic `.olm` files following the documented structure; there is no real `.olm` in the tests.**'],
            ['Password-protected ZIP', 'Yes (ZipCrypto and WinZip AES-128/192/256)', 'No', 'The wizard asks for the password; it is verified and stored **encrypted** with the instance key only until the encrypted entries are expanded, then deleted. Verified against 7-Zip and Info-ZIP. `@zip.js/zip.js` was evaluated (8.5 MB, duplicates fflate, would bypass the zip-bomb accounting) and not installed.'],
            ['Drafts', 'Yes', 'Yes', 'Export: `Drafts.mbox` (or `Drafts/*.eml`) with `X-Bloomx-Draft: 1`. Import: that header, Gmail\'s `Drafts` label, a Drafts folder or Maildir\'s `D` flag create `Draft` rows for the user (not mail).'],
            ['Contacts `.vcf`', 'Yes', 'Yes (`contacts.vcf`, vCard 4.0)', 'De-duplicated by email without overwriting. The model stores only email, name and notes: phones, organisation, addresses… go to `notes` as labelled lines.'],
            ['Calendar `.ics`', 'Yes', 'Yes (`calendar.ics`)', 'Attendees, time zones (IANA, Windows names, `VTIMEZONE`), exceptions. The model has no recurrence field: `RRULE` is kept as text in `description` **and** occurrences (up to 500) are expanded into events.'],
            ['Gmail filters `mailFilters.xml`', 'Yes', 'Yes (`mailFilters.xml`)', 'Into `src/lib/rules`. The engine has no negation: `doesNotHaveTheWord`, size, importance, categories, `forwardTo`, `shouldNeverSpam` are reported as *filter not convertible* (an automatic forward is never created).'],
            ['`manifest.json`', 'Ignored', 'Yes', 'Mailboxes, folders, labels, counts, dates and the `sha256` of every file.'],
        ] },
        { t: 'p', text: 'The format is detected **by content** (`PK`, gzip, `!BDN`, `ustar` signatures, `From ` line + header, RFC 822 headers), not by extension.' },
        { t: 'callout', kind: 'warn', title: 'Not supported', text: 'Encrypted or damaged PST (the library cannot read them), ZIPs with certificate-based strong encryption, and ZIPs whose entries use different passwords (the job fails with `zip_wrong_password`). BloomX\'s encrypted package (`BLMXENC1`) must be decrypted before re-importing (`scripts/bloomx-decrypt.mjs`).' },
        { t: 'h2', id: 'extraction', text: 'Extraction phase (large ZIP and GZ)' },
        { t: 'ul', items: [
            'Deflated entries above 16 MiB, encrypted entries and `.gz`/`.tgz` files are **expanded before importing** into 4 MiB chunks (`x/<entry>/NNNNNN`) inflating 16 KiB at a time: an entry is never loaded whole. Import then reads those chunks with an offset cursor.',
            '**Resumable**: when the tick budget (`MAIL_TRANSFER_BUDGET_MS`) runs out the tail and writer state are saved in the cursor. Deflate cannot resume mid-stream, so the next tick **re-inflates the already written prefix without writing it** (CPU only) and continues; every byte is written once. If the process dies between writing and saving the cursor, it resumes from the last checkpoint and chunks are rewritten deterministically.',
            '**Documented cost**: resuming an entry of N bytes costs re-inflating N bytes (CPU). With the 1 GiB per-entry cap that is seconds; a single multi-GB `.gz` repeats its prefix each tick (each tick still advances at least one 4 MiB chunk).',
        ] },
        { t: 'h2', id: 'mapping', text: 'Folders, labels and flags' },
        { t: 'ul', items: [
            'Priority: `X-Bloomx-Folder` (own exports) > `X-Gmail-Labels` > flags (`X-Mozilla-Status` deleted, `junk`) > folder from the path > Inbox.',
            'Gmail: `Inbox`, `Sent`, `Trash`, `Spam` (also Spanish names) become own folders; `Starred` = starred; `Unread` = unread; other labels are created as the user\'s **Label** when missing.',
            'Read/starred: `Status`/`X-Status` (`RO`, `F`), `X-Mozilla-Status`, `X-Bloomx-Flags`. With no data: imported as read.',
            'The message date is the **original** one (`Date` header, or the `From ` line if missing); an absurd future date is clamped to "now". If the `Email.previousFolder` column exists, trash/spam fill it with `inbox`.',
            'Stored with the same layout as normal ingestion (`emails/<date>/<uuid>/…`), so retention and full deletion work the same.',
            'Rules and `EMAIL_RECEIVED` hooks do **not** run, no push notifications and no email is sent.',
        ] },
        { t: 'h2', id: 'missing', text: 'Mailboxes that do not exist' },
        { t: 'p', text: 'The preview lists the detected addresses (`X-Bloomx-Mailbox`, ZIP path, `From` in sent mail, `Delivered-To` / `X-Original-To`, `To`/`Cc`) with their status: **exists**, **missing** or **foreign domain**. If any are missing an accessible dialog asks "Create the missing mailboxes?": each address is created (only on the instance domain: `TOP_DOMAIN`, the `NEXT_PUBLIC_APP_URL` host or `MAIL_TRANSFER_ALLOWED_DOMAINS`), mapped to an existing mailbox or discarded. Password: a **unique random one per user** (recommended) or a **generic** one (12+ character policy, with a meter), and "force a password change at first sign-in" (`mustChangePassword`, on by default). Nothing is created until the summary is confirmed by typing the domain. It uses the same function as the console\'s user creation (`createUserAccount`, bcrypt hash). Generated credentials are returned **once** to the browser, which downloads them as CSV; they are never stored in clear or logged.' },
        { t: 'h2', id: 'jobs', text: 'Job design' },
        { t: 'ul', items: [
            '**Resumable chunked upload**: 4 MiB per request (under Vercel\'s 4.5 MB limit), `PUT /jobs/:id/chunks/:n` with an `x-chunk-sha256` verified server side; `GET …/chunks` lists what is there so an upload can resume; `POST …/complete` checks everything arrived and stores a digest of the set. The file is never assembled: it is read by ranges.',
            '**Background batches** (Elixir worker pattern): statuses `created → uploading → analyzing → ready → queued → running → done|failed|canceled|expired`. Each tick locks the job (`lockedUntil`), runs ~45 s and stores a cursor (entry + message offset). Chained with `after()` + `POST /api/cron/mail-transfer` (Bearer `CRON_SECRET` or the internal key), the daily cron in `vercel.json` and a **push from the browser** (`POST /jobs/:id/tick`) when polling notices a stall.',
            '**Idempotent**: every message has a source key (`entry:offset`) and the stored `messageId` is the webhook\'s per-user scheme (`<Message-ID>-<userId>`, unique). Retrying, resuming after a crash or re-importing does not duplicate, even with two jobs at once. Counters come from counting `MailTransferItem`.',
            '**Export**: per mailbox and folder, keyset pagination (date, id), writing the ZIP in chunks (complete entries with known CRC, central directory in separate objects, ZIP64 when needed). Writer tails are versioned, so a crash between writing and saving the cursor resumes without corrupting the package.',
            'Download: HMAC-signed link bound to the job **and** the administrator, 10 min lifetime, plus the same actor\'s session; "download once" claims the file atomically and an interrupted download does not consume it. It expires after 24 h (`MAIL_TRANSFER_EXPORT_TTL_HOURS`) and retention deletes it from storage.',
            'Downloadable CSV report: imported, duplicates skipped and errors with reason (no content).',
        ] },
        { t: 'h2', id: 'encryption', text: 'Package encryption' },
        { t: 'p', text: 'Optional: `BLMXENC1` container = 37-byte header (magic, version, scrypt KDF N=2^15 r=8 p=1, 16 B salt, nonce prefix, record size) + 1 MiB AES-256-GCM records (nonce = prefix ‖ counter, AAD = header ‖ final byte) + a mandatory empty final record (detects truncation). The password is not stored; while the job runs the server keeps only the **derived key encrypted with the data key** and deletes it when done. To open it:' },
        { t: 'code', lang: 'bash', title: 'Decrypt', code: "node scripts/bloomx-decrypt.mjs package.zip.bmx package.zip\n# or BLOOMX_PACKAGE_PASSWORD='…' node scripts/bloomx-decrypt.mjs package.zip.bmx package.zip" },
        { t: 'h2', id: 'safeguards', text: 'Safeguards' },
        { t: 'ul', items: [
            'Only `requireAdmin` (domain owner or `ADMIN_EMAILS` with MFA). "My mailbox" needs a session and only touches the user\'s own mailbox (no user creation, no other people\'s jobs).',
            '**Recent re-authentication** (10 min: password or MFA code; a session with MFA verified less than 10 min ago also counts) to create imports, confirm, export and issue download links. The proof is an httpOnly `SameSite=Strict` cookie bound to the administrator. An administrator without MFA can re-enter the password; the dialog recommends enabling MFA.',
            '**Typing the domain name to confirm**, per-endpoint `rateLimitAsync`, a cap on concurrent jobs per domain (`MAIL_TRANSFER_MAX_CONCURRENT`, 2) and strict ownership: a job is visible only to its creator and in their domain (404 otherwise).',
            'Audit (`admin.mail_transfer.*`): administrator, scope, mailbox and message counts, bytes, sha256 and IP. **Never** content, subjects, passwords or keys.',
            'Optional email notice to affected users.',
            'Attachments are validated with `file-type` (magic bytes) and the optional antivirus (`av-hook`) as in normal ingestion; executables and active HTML are blocked or sanitised. Headers are sanitised (no CR/LF/control) on read and on build.',
            '**ZIP**: normalised names (no `..`, absolute paths, drive letters, NUL), symlinks and encrypted entries skipped, caps on entries, per-entry size, total size and compression ratio, and **the bytes actually inflated are counted** (a lying header aborts). Inflating is done in 16 KiB slices. Nothing is written to the file system.',
            'Bounded memory: streaming mbox (messages over `MAIL_TRANSFER_MAX_MESSAGE_MB` = 50 are dropped without buffering), PST message by message. Uploaded files are deleted when the job ends (or after 48 h if abandoned).',
            'Storage paths are never exposed: only job ids and signed links.',
        ] },
        { t: 'h2', id: 'env', text: 'Variables' },
        { t: 'table', head: ['Variable', 'Default', 'Effect'], rows: [
            ['`MAIL_TRANSFER_ALLOWED_DOMAINS`', '(empty)', 'Extra domains where mailboxes may be created. Without `TOP_DOMAIN`, the `ADMIN_EMAILS` domains are used.'],
            ['`MAIL_TRANSFER_MAX_UPLOAD_MB`', '16384', 'Maximum upload size'],
            ['`MAIL_TRANSFER_MAX_MESSAGE_MB`', '50', 'Larger message: `too_large` error'],
            ['`MAIL_TRANSFER_MAX_ATTACHMENTS`', '100', 'Attachments per message'],
            ['`MAIL_TRANSFER_MAX_CONCURRENT`', '2', 'Active jobs per domain'],
            ['`MAIL_TRANSFER_BUDGET_MS`', '45000', 'Duration of each tick'],
            ['`MAIL_TRANSFER_PST_MAX_MB`', '2048', 'PST cap (range reads, no copy to /tmp; measured up to 640 MiB)'],
            ['`MAIL_TRANSFER_EXPORT_TTL_HOURS`', '24', 'Package expiry'],
            ['`RAW_MIME_MAX_MB`', '25', 'Maximum original MIME size stored as `raw.eml`'],
            ['`MAIL_STORE_RAW_MIME`', '(on)', '`false` disables storing `raw.eml`'],
            ['`MAIL_TRANSFER_MAX_CONTACTS` / `_MAX_EVENTS`', '20000 / 50000', 'Contacts and events imported per mailbox'],
            ['`MAIL_TRANSFER_MAX_EXPANDED_GB`', '40', 'Decompression cap (zip bomb)'],
        ] },
        { t: 'h2', id: 'ddl', text: 'Tables' },
        { t: 'p', text: 'Additive, created by `db:ensure` (also in `prisma/schema.prisma`). Without them the routes return 503 `mail_transfer_tables_missing`.' },
        { t: 'code', lang: 'sql', title: 'DDL', code: ddl },
        { t: 'h2', id: 'rawmime', text: 'Original MIME on export' },
        { t: 'ul', items: [
            '`process-attachments` already downloads Resend\'s raw MIME: it now also stores it as `raw.eml` next to `raw.json` unless `MAIL_STORE_RAW_MIME=false`, up to `RAW_MIME_MAX_MB` (25). `Email.rawKey` **still points to `raw.json`** (other routes parse it as JSON); the `raw.eml` key is derived from it (`src/lib/raw-mime.ts`).',
            'Export prefers `raw.eml` (exact `Received`, `Authentication-Results`, `DKIM-Signature`…) and prepends folder/label/flag headers. For older mail it tries `Email.rawMimeUrl` (public https only, private IPs blocked, 4 s timeout, size cap; never blocking) and falls back to rebuilding. With "no attachments" it always rebuilds. `manifest.json` counts each source.',
            'Retention: complete deletion and the `raw` policy include `raw.eml` (and keep it while another recipient of the same message still uses it). Cost: up to 25 MB extra per message.',
        ] },
        { t: 'h2', id: 'limits', text: 'Known limits' },
        { t: 'ul', items: [
            'Verified with embedded Postgres, local storage and a **local S3-compatible server** (`scripts/fake-s3.mjs`: multipart, Range, paginated ListObjectsV2, DeleteObjects in batches of 1000, SigV4). **Not** against real S3/B2: the provider\'s acceptance of checksums, signatures and limits can only be confirmed with it (SDK checksums use `WHEN_REQUIRED`).',
            'Throughput is measured by `scripts/bench-mail-transfer.mjs`; import is bound by Postgres and by writing 3–4 objects per message, not by memory.',
            '`.olm`: there is no real file in the tests (see the table).',
        ] },
    ],
};

export default page;
