import type { DocPageContent } from '../types';

const csp = `default-src 'self';
script-src 'self' 'unsafe-inline' https://accounts.google.com https://apis.google.com;
style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
img-src 'self' data: blob: https:;
font-src 'self' data: https://fonts.gstatic.com;
connect-src 'self' https: wss:;
media-src 'self' data: blob: https:;
frame-src 'self' blob: data: about: https://accounts.google.com;
worker-src 'self' blob:;  manifest-src 'self';
object-src 'none';  base-uri 'self';  form-action 'self';  frame-ancestors 'self';`;

const page: DocPageContent = {
    es: [
        { t: 'p', text: 'Esta página describe lo que el código **hace hoy**, no lo que sería deseable. Cada dato (nombre de variable, valor por defecto, límite) se verificó contra el código. Los huecos conocidos están en [Límites conocidos](#limits) y el mapeo a normas en [CIS / NIST / ISO](/docs/compliance).' },
        { t: 'h2', id: 'threat-model', text: 'Modelo de amenazas (resumen)' },
        { t: 'table', head: ['Amenaza', 'Mitigación principal', 'Sección'], rows: [
            ['Robo o fijación de sesión', 'Cookie HttpOnly `__Host-`, JWT con `jti` y `tokenVersion`, tope absoluto de sesión', '[Sesiones](#sessions)'],
            ['Fuerza bruta y relleno de credenciales', 'Rate limit por IP y por cuenta, bloqueo, bcrypt coste 12, MFA TOTP', '[Rate limit](#rate-limit)'],
            ['XSS en correo entrante', 'DOMPurify + iframe con `sandbox` sin `allow-same-origin` + CSP interna', '[Contenido del correo](#mail-content)'],
            ['Fuga de secretos en BD/backups', 'AES-256-GCM (v3) con `keyId` y rotación; tokens OAuth cifrados', '[Cifrado](#encryption)'],
            ['Acceso a adjuntos ajenos (IDOR)', 'Propiedad verificada en servidor y URLs de assets firmadas con HMAC', '[Assets firmados](#assets)'],
            ['Malware en adjuntos', 'Magic-bytes, extensiones peligrosas y antivirus opcional', '[Adjuntos](#attachments)'],
            ['SSRF desde extensiones', '`safe-fetch`: solo https, IP privadas bloqueadas, validación en la conexión', '[Extensiones](#extensions)'],
            ['Suplantación entre frontend y backend', 'Firmas Ed25519 por dominio, sin secretos compartidos', '[Arquitectura](/docs/architecture#trust)'],
            ['CSRF', 'Comprobación de `Origin` en `/api/*` que cambian estado', '[Cabeceras y CSP](#headers)'],
        ] },
        { t: 'h2', id: 'sessions', text: 'Sesiones, JWT y revocación' },
        { t: 'ul', items: [
            'JWT HS256 firmado con `NEXTAUTH_SECRET` (propio de cada frontend). En producción, si falta, la operación falla; en desarrollo se usa un valor fijo solo para desarrollo.',
            'Claims: `sub`, `email`, `name`, `use:"session"`, `jti`, `tv` (tokenVersion), `at` (instante del login) y `mfa:true` si hubo segundo factor.',
            'Cookie `__Host-next-auth.session-token` en producción (HttpOnly, SameSite=Lax, Path=/, sin Domain, Secure). Se sigue **leyendo** la cookie antigua sin prefijo mientras `SESSION_COOKIE_LEGACY_READ` esté activo (por defecto sí); pon `SESSION_COOKIE_HOST_PREFIX=0` para desactivar el prefijo.',
            'Vigencia deslizante: `SESSION_TTL_SECONDS` (por defecto 86400 = 24 h de inactividad) y tope absoluto `SESSION_ABSOLUTE_MAX_SECONDS` (por defecto 1209600 = 14 días desde el login).',
            'Revocación: `User.tokenVersion` cierra todas las sesiones (cambio de contraseña, alta/baja de MFA); la tabla `RevokedSession(jti)` cierra una sola (logout). Cache de 5 s por instancia (`SESSION_REVOCATION_CACHE_MS`), así que en varias instancias una revocación puede tardar hasta ese tiempo.',
            'Tokens antiguos sin `jti`: se aceptan hasta `SESSION_TTL_SECONDS` desde su emisión; `SESSION_ALLOW_LEGACY_TOKENS=false` los rechaza ya.',
            'Contraseñas: mínimo 12 caracteres, máximo 72 bytes, lista de comunes, sin repeticiones ni el nombre del email; bcrypt coste 12 con comparación de tiempo constante.',
        ] },
        { t: 'callout', kind: 'warn', title: 'Si falta DDL', text: 'Sin la columna `tokenVersion` o la tabla `RevokedSession` el mecanismo correspondiente se omite con un aviso (falla abierto). Ejecuta `npm run db:ensure` antes de desplegar ([Operación](/docs/operations#migrations)).' },
        { t: 'h2', id: 'mfa', text: 'MFA TOTP' },
        { t: 'ul', items: [
            'TOTP estándar (RFC 6238: SHA1, 6 dígitos, 30 s, ventana ±1 paso) con anti-replay atómico. El secreto (160 bits) se guarda cifrado en `UserMfa.secretEnc`; el QR se genera en el enrolamiento.',
            'Diez códigos de recuperación (`XXXXX-XXXXX`), guardados como HMAC-SHA256 con `MFA_RECOVERY_PEPPER` (por defecto `NEXTAUTH_SECRET`; fíjalo si vas a rotar `NEXTAUTH_SECRET`). Un solo uso; se pueden regenerar.',
            '**Obligatorio** para los correos de `ADMIN_EMAILS` (se desactiva con `MFA_ENFORCE_ADMIN=false`) y para todos si `MFA_REQUIRED_ALL=true`. Opcional para el resto.',
            'Intentos: 6 cada 5 min por usuario y 40 cada 15 min por IP (429).',
            'Login: si MFA aplica, `POST /api/auth/login` devuelve `mfaRequired` o `mfaEnrollRequired` con un `mfaToken` de 5 min y **no** emite cookie; `POST /api/auth/mfa/verify` emite la sesión con `mfa:true`.',
            'Si la tabla `UserMfa` no existe y MFA es obligatorio para ese usuario, el login responde **503** (falla cerrado).',
            '`requireAdmin` exige email en `ADMIN_EMAILS` y sesión con `mfa:true` cuando MFA es obligatorio.',
        ] },
        { t: 'h2', id: 'encryption', text: 'Cifrado en reposo' },
        { t: 'table', head: ['Formato', 'Estructura', 'Algoritmo y clave'], rows: [
            ['v1 (legado)', '`iv:ct` en hex', 'AES-256-CBC sin autenticación. Solo se **lee**.'],
            ['v2', '`v2:iv:tag:ct`', 'AES-256-GCM, clave por HKDF-SHA256 (info `bloomx:data-encryption:v2`).'],
            ['v3 (por defecto)', '`v3:<keyId>:iv:tag:ct`', 'AES-256-GCM, HKDF con `keyId` en la info y en el AAD.'],
        ] },
        { t: 'ul', items: [
            'Clave vigente: `DATA_ENCRYPTION_KEY` con id `DATA_ENCRYPTION_KEY_ID` (por defecto `k1`). Claves anteriores para descifrar: `DATA_ENCRYPTION_KEYS_PREVIOUS="k0:secreto,k1:otro"`. `NEXTAUTH_SECRET` actúa como reserva (id `auth`); `ENCRYPTION_REQUIRE_DEDICATED_KEY=true` obliga a definir la clave dedicada en producción.',
            '`ENCRYPTION_WRITE_FORMAT` (por defecto `v3`; `v2` para hacer rollback).',
            '**Rotación**: define una clave nueva con id nuevo, pasa la anterior a `DATA_ENCRYPTION_KEYS_PREVIOUS`, deja que el re-cifrado perezoso migre lo que se lea y retira la antigua cuando ya nada la use.',
            'Qué se cifra: tokens OAuth de `Account` (con migración perezosa, `ACCOUNT_TOKENS_LAZY_MIGRATE`), secreto TOTP, ajustes de expansiones y mensajes sellados del servidor. Los cuerpos de correo y los adjuntos **no** se cifran a nivel de aplicación; `S3_SSE=AES256|aws:kms` activa el cifrado del lado del proveedor.',
            'Claves internas: la clave servidor-a-servidor de cada instancia se **deriva** de su `NEXTAUTH_SECRET` con HKDF-SHA256 (info `bloomx-internal-v1`); la clave de URLs de assets y la del token pendiente de MFA también se derivan. Por eso no hay secretos que compartir con el backend.',
            'El backend usa su propio formato `enc:v1:` (AES-256-GCM con `DATA_ENCRYPTION_KEY` del backend, sin `keyId`) para la clave de Resend del dominio y las credenciales de extensiones.',
            'Credenciales de extensiones (orden: dominio, heredadas, entorno del servidor): las variables de plataforma (base de datos, almacenamiento, cifrado, claves privadas, `EXTENSION_*`) están en una lista negra que ninguna extensión puede leer; el secreto solo existe dentro del sandbox y nunca se devuelve ni se registra. El modo legado (sin firma) sigue recibiendo credenciales, con rate limit, auditoría por ejecución y sin `services.mail`; `requireSignature` lo rechaza.',
        ] },
        { t: 'h2', id: 'assets', text: 'URLs de assets firmadas' },
        { t: 'p', text: 'Los adjuntos se sirven por `/api/assets/<clave>?exp=<epoch>&sig=<base64url>`, con `sig = HMAC-SHA256(clave_de_firma, "asset:v1\\n" + clave + "\\n" + exp)`. La clave de firma es `ASSET_SIGNING_KEY` o, si no existe, se deriva de `NEXTAUTH_SECRET`.' },
        { t: 'ul', items: [
            'TTL: `ASSET_URL_TTL_SECONDS` (3600) para adjuntos recibidos y `ASSET_UPLOAD_URL_TTL_SECONDS` (2592000 = 30 días) para subidas.',
            'Enlaces sin firma: `ASSET_UNSIGNED_INBOUND` (por defecto `owner`: exige sesión del propietario) y `ASSET_UNSIGNED_UPLOADS` (por defecto `allow`); valores `allow | owner | deny`. Cuando caduquen los enlaces antiguos, sube las subidas a `owner` o `deny`.',
            'El propietario autenticado siempre puede acceder aunque la firma haya caducado. Solo se sirven los prefijos `attachments/` y los adjuntos entrantes; se rechazan `..`, `\\`, `\\0` y claves de más de 1024 caracteres. Los rechazos devuelven 404 y se auditan.',
            'Respuesta con `nosniff`, `CSP: default-src \'none\'; sandbox`, `Content-Disposition: attachment` y los tipos activos como `application/octet-stream`.',
        ] },
        { t: 'h2', id: 'attachments', text: 'Adjuntos: magic-bytes y antivirus' },
        { t: 'ul', items: [
            'Siempre activo: detección por cabecera del archivo (ejecutables PE/ELF/Mach-O, scripts `#!`, JAR/APK, HTML/SVG/XML activos) y lista de extensiones peligrosas (se revisan todas las del nombre: `a.pdf.exe` se detecta). En subidas se rechaza; en entrantes se bloquea el ejecutable y se sanea lo raro (`INBOUND_BLOCK_DANGEROUS_EXT=false` para no bloquear por extensión). Límite de subida: 200 MB.',
            'Antivirus **opcional** (ClamAV REST o compatible): define `AV_SCAN_URL` (`AV_SCAN_TOKEN`, `AV_SCAN_FIELD`=`file`, `AV_SCAN_TIMEOUT_MS`=8000). Archivos mayores que `AV_SCAN_MAX_BYTES` (25 MB) se omiten. `AV_FAIL_MODE=open` (por defecto) acepta si el AV falla y lo audita; `closed` bloquea con 503 en subidas.',
        ] },
        { t: 'h2', id: 'retention', text: 'Retención y borrado' },
        { t: 'table', head: ['Variable', 'Por defecto', 'Efecto'], rows: [
            ['`RETENTION_SPAM_DAYS`', '30', 'Borra spam más antiguo (0 = desactivado)'],
            ['`RETENTION_TRASH_DAYS`', '0 (off)', 'Borra la papelera por antigüedad de creación'],
            ['`RETENTION_RAW_DAYS`', '0 (off)', 'Borra el `raw.json` del webhook'],
            ['`AUDIT_RETENTION_DAYS`', '365', 'Purga `AuditEvent` (0 = no purga)'],
            ['`SECURE_MESSAGE_TTL_DAYS`', '30', 'TTL máximo de mensajes sellados (+1 día de gracia)'],
            ['`RETENTION_BATCH`', '200', 'Lote por pasada (tope 1000)'],
        ] },
        { t: 'p', text: 'El borrado es completo: HTML, texto, `raw.json` y adjuntos con conteo de referencias (un objeto compartido no se borra hasta que nadie lo use). Se ejecuta con `GET/POST /api/admin/retention` con `Authorization: Bearer <CRON_SECRET>` o sesión admin; `?dryRun=1` solo cuenta.' },
        { t: 'h2', id: 'spam-filter', text: 'Filtro de spam y blocklist' },
        { t: 'p', text: 'El correo entrante pasa por la **lista de bloqueo** (remitente del sobre, `From` y dominio DKIM) **antes** de guardar nada: si acierta no se almacena cuerpo, adjuntos ni crudo, se responde `200` y no se genera rebote (sin *backscatter*). Después, el motor puntúa por señales de autenticación, suplantación de marca, enlaces, adjuntos y contenido. Los permitidos **no** eluden la suplantación ni el malware; no se pueden bloquear el dominio propio ni los administradores; las regex de las listas pasan por la defensa ReDoS de las reglas. El registro de decisiones no guarda contenido. Ver [Filtro de spam y remitentes](/docs/spam).' },
        { t: 'h2', id: 'mail-transfer', text: 'Importar y exportar correo' },
        { t: 'p', text: 'Mueve el contenido de los correos de todos los usuarios, así que solo `requireAdmin`, con **re-autenticación reciente** (10 min), confirmación escribiendo el dominio, límite de peticiones y de trabajos concurrentes, propiedad estricta de cada trabajo, auditoría sin contenido, enlaces de descarga firmados y de una sola vez, paquete cifrable (AES-256-GCM + scrypt), y defensas contra zip-slip, zip-bomb y enlaces simbólicos. Detalle en [Importar y exportar correo](/docs/mail-transfer#safeguards).' },
        { t: 'h2', id: 'admin-access', text: 'Acceso de administración: niveles y sesión privilegiada' },
        { t: 'ul', items: [
            '**Niveles de permisos** (`permission_level` 0-4: user, support, operator, admin, superadmin). Cada ruta y comando declara su nivel mínimo en un solo sitio (`lib/admin-levels.ts`) y se comprueba en `requireLevel(n)` aunque se llame a la API directamente (403). `ADMIN_EMAILS` es la semilla/rescate: nivel 4 fijado por entorno. Ver la [escala y las reglas](/docs/admin-cli#permission-levels).',
            '**Mínimo privilegio y separación**: solo se asigna un nivel menor al propio, nadie modifica a alguien de nivel igual o superior ni a sí mismo, y los cambios exigen step-up con MFA, se auditan (`admin.permissions.changed`) y avisan por correo; `ADMIN_EMAILS_LOCKED=true` desactiva la gestión por consola.',
            '**Una sola sesión privilegiada** por cuenta (consola web y CLI juntas): la nueva revoca la anterior en el acto (401 `superseded`), con aviso por correo y push; un reemplazo desde otra IP o dispositivo alerta además a los superadmins. Cierre por **inactividad** (15 min, 5-60 configurable) y tope **absoluto de 12 h** (401 `expired`). Tres reemplazos en 10 min **bloquean** el acceso privilegiado hasta que un superadmin lo desbloquee. Ver [sesión privilegiada](/docs/admin-cli#privileged-session).',
            '**Tokens de CLI**: hash SHA-256, caducidad (12 h por defecto, 30 d máx.), ámbitos, nivel acotado por la cuenta y revocación inmediata al bajar el nivel; los tokens «machine» de automatización son de solo lectura, ≤ 7 d, nunca nivel 4 y no ocupan el slot.',
            'Controles de referencia: NIST AC-6 (mínimo privilegio), AC-10 (sesiones concurrentes), AC-11/AC-12 (cierre por inactividad y terminación), IA-2(1) e IA-11 (MFA y reautenticación), AU-2/AU-3; ASVS V3 (sesiones) y V4 (control de acceso); CIS 5 y 6; ISO 27001 A.5.15, A.8.2, A.8.5 y A.8.15.',
        ] },
        { t: 'h2', id: 'audit', text: 'Auditoría' },
        { t: 'ul', items: [
            'Cada evento sale como línea JSON por stdout y se inserta en `AuditEvent` (asíncrono, nunca rompe la petición; 5 fallos seguidos pausan la persistencia 60 s; `AUDIT_DB=off` la desactiva).',
            'Redacción: se omiten claves con `pass|token|secret|authorization|cookie|key|otp|code|recovery`, los emails se enmascaran y las cadenas se recortan a 500 caracteres.',
            'Se registran, entre otros: `auth.login.*`, `auth.mfa.*`, `auth.logout`, `auth.password.changed`, `auth.register.*`, `admin.*`, `assets.denied`, `attachment.blocked`, `av.*`, `email.deleted`, `retention.*`.',
            'El backend audita a stdout (sin tabla). No hay integridad criptográfica del registro ni SIEM integrado.',
        ] },
        { t: 'h2', id: 'rate-limit', text: 'Rate limit' },
        { t: 'p', text: 'Sin Upstash el límite es por instancia (memoria, ventana fija). Con `UPSTASH_REDIS_REST_URL` y `UPSTASH_REDIS_REST_TOKEN` es global (claves hasheadas, sin emails ni IP en claro). Si Redis falla (timeout `RATE_LIMIT_REDIS_TIMEOUT_MS`=800; tres fallos abren el circuito 30 s), `RATE_LIMIT_ON_ERROR=memory` (defecto) cuenta en memoria y `open` deja pasar; nunca bloquea a todos. La IP sale de `x-forwarded-for`: solo es fiable tras un proxy que la sobrescriba.' },
        { t: 'table', head: ['Endpoint', 'Límite'], rows: [
            ['Login', '20 / 15 min por IP y 10 / 15 min por cuenta'],
            ['Registro', '5 / h por IP'],
            ['MFA', '6 / 5 min por usuario y 40 / 15 min por IP'],
            ['`set-cookie` / `refresh`', '60 / min y 120 / min'],
            ['Subidas', '120 / 10 min por usuario'],
            ['Mensaje sellado (crear / abrir / consumir)', '30 / h por email; 60 / min y 120 / h por IP y id; 120 / min y 240 / h'],
            ['Reserva de citas', '10 / h por IP y 3 / h por email'],
            ['Elixir', '1200 / h por usuario'],
            ['Baja (unsubscribe)', '30 / min'],
        ] },
        { t: 'h2', id: 'headers', text: 'Cabeceras, CSP y CSRF' },
        { t: 'ul', items: [
            '`Strict-Transport-Security: max-age=63072000; includeSubDomains; preload`, `X-Content-Type-Options: nosniff`, `X-Frame-Options: SAMEORIGIN`, `Referrer-Policy: strict-origin-when-cross-origin`, `Permissions-Policy` (cámara, micrófono, geolocalización, pagos y USB desactivados), `Cross-Origin-Opener-Policy: same-origin-allow-popups`.',
            '`/api/auth/*` con `Cache-Control: no-store`; `/secure/*` y `/api/secure-message/*` con `no-referrer`, `no-store` (y `noindex` en `/secure/*`).',
            'CSRF: en `/api/*` que cambian estado, si llega `Origin` su host debe coincidir con el `Host` (403 si no). Sin `Origin` (clientes no navegador) o con `Bearer` no se bloquea. Están exentos los webhooks, cron, `/api/config`, `/api/register`, reservas públicas de citas y parte de `/api/auth`.',
        ] },
        { t: 'code', lang: 'csp', title: 'CSP global (producción; en desarrollo se añade unsafe-eval)', code: csp },
        { t: 'callout', kind: 'note', text: 'La CSP permite `\'unsafe-inline\'` en scripts y estilos, e `img-src`/`connect-src` con `https:` genérico. Es una limitación real (ver [Límites](#limits)).' },
        { t: 'h2', id: 'mail-content', text: 'Contenido del correo entrante' },
        { t: 'ul', items: [
            'DOMPurify con perfil HTML (sin SVG/MathML; se prohíben script, iframe, object, embed, form, input, meta, link, base, audio/video y atributos `srcset`, `ping`, `formaction`, `data-*`); URIs limitadas a http, https, mailto, tel y cid; los enlaces reciben `target=_blank` y `rel="noopener noreferrer nofollow"`.',
            '`SafeIframe`: `srcDoc` re-saneado con `sandbox="allow-popups allow-popups-to-escape-sandbox allow-scripts"` (sin `allow-same-origin`: origen opaco) y una CSP propia por `<meta>` (`default-src \'none\'`, script solo con nonce del propio visor).',
            'Imágenes remotas bloqueadas por defecto (se permiten por correo o por remitente; la política vive en `localStorage`, clave `bloomx:remote-images:v1`).',
            'Aviso anti-phishing junto al enlace cuando el texto visible no coincide con el destino, hay punycode (`xn--`), IP como host, `user@` en la URL o un acortador conocido.',
            'Cabeceras de autenticación (SPF/DKIM/DMARC) del mensaje recibido se muestran como insignia.',
        ] },
        { t: 'h2', id: 'extensions', text: 'Extensiones: sandbox y SSRF' },
        { t: 'ul', items: [
            'Cada invocación corre en un `worker_threads` propio con `env` vacío y un contexto `node:vm`; toda E/S sale por mensajes al hilo principal. Límites: heap 128 MB, timeout duro 25 s, 20 fetch, 5 llamadas de IA, 500 mensajes y 200 logs por invocación, 8 workers simultáneos (`EXT_SANDBOX_MAX_WORKERS`).',
            '`safe-fetch`: solo https (`EXTENSION_ALLOW_HTTP=true` permite http), sin credenciales en la URL, bloquea localhost/.local/.internal, rangos privados, CGNAT, link-local (metadata 169.254.x.x) y equivalentes IPv6; valida la IP **en el momento de conectar** (sin ventana de DNS rebinding); máximo 3 redirecciones revalidadas; timeout 10 s; respuesta máx. 5 MB.',
            'Las extensiones solo leen variables declaradas con `ENV_READ`; los nombres reservados (`DATABASE_URL`, `B2_*`, `NEXTAUTH_*`, `DATA_ENCRYPTION_KEY`, `RESEND_*`…) están vetados.',
        ] },
        { t: 'callout', kind: 'warn', title: 'No es una frontera fuerte', text: 'Un escape del `vm` compartiría proceso, sistema de ficheros y red con el backend. Para código hostil hace falta contenedor o microVM. Ver [Extensiones](/docs/expansions#sandbox).' },
        { t: 'h2', id: 'extension-controls', text: 'Extensiones: validación, preferencias y obligatorias' },
        { t: 'ul', items: [
            '**Validación al publicar**: el backend compartido valida manifest **y UI** (espejo de `ui-schema.ts`, con límites de nodos, profundidad y tamaño) en todos los caminos de publicación e instalación. Un UI inválido no se guarda: 400 (estructura) o 422 (UI o límites) con la ruta del error. Los scripts `sync-extensions.mjs` y `scripts/sync-repository-extensions.mjs` fallan cerrados si no pueden ejecutar el validador.',
            '**Preferencias por usuario**: la lista `disabledExtensions` viaja dentro del cuerpo **firmado** (Ed25519) de `hooks`/`execute`, se lee en el servidor de los ajustes cifrados del usuario y se sanea en ambos lados (ids válidos, sin duplicados, máx. 200). Una lista manipulada solo puede apagar extensiones **para ese mismo usuario**.',
            '**Obligatorias**: `mandatory: true` en el manifest o política del dominio (`settings.meta.mandatory`, solo el manager dueño del dominio con `POST /api/manager/extensions/mandatory`; auditado). El backend las ejecuta siempre, sin depender de lo que envíe el navegador; la interfaz no permite desactivarlas. DLP se publica como obligatoria.',
            'Dominios **legados** sin firma: no reciben ni se les aplica la lista; se ejecuta todo como antes (compatibilidad).',
        ] },
        { t: 'h2', id: 'limits', text: 'Límites conocidos' },
        { t: 'callout', kind: 'warn', title: 'Acceso de administrador y backend compartido', text: '`requireAdmin` (`src/lib/admin-auth.ts`) solo concede acceso a `api/admin/*` a (a) un "manager" del backend que sea **propietario** del dominio de esta instancia, o (b) un usuario con email en `ADMIN_EMAILS` y sesión con `mfa:true`. Para (a), el frontend consulta al backend con la cookie `auth_session` del propio manager (`/api/auth/me` y `GET /api/manager/domains`, que solo devuelve sus dominios) y exige que uno sea el dominio activo de la instancia (`TOP_DOMAIN` / host de `NEXT_PUBLIC_APP_URL`, nunca cabeceras del cliente). Aunque el registro de managers es abierto, un manager ajeno recibe **403** en `api/admin/*` y `POST /api/admin/login` no le reenvía la sesión. El resultado se cachea 45 s por sesión y falla cerrado: si el backend no responde o no hay dominio configurado, no se concede acceso por esta vía. El propietario no necesita MFA por esta vía (la sesión de manager es la del backend); la vía (b) sí lo exige. El backend vuelve a comprobar la propiedad (`Domain.managerId`) en cada ruta de manager que recibe un dominio (`extensions/install|uninstall`, `extension/settings`, `domain-key`).' },
        { t: 'ul', items: [
            '`AccountManager` (multicuenta) guarda un JWT por cuenta en `localStorage` (`bloomx_accounts`): legible por cualquier XSS. Mitigado por TTL, tope absoluto y revocación por `jti`.',
            'El callback de Google no exige TOTP a un usuario que activó MFA voluntariamente (sí lo bloquea si MFA es obligatorio). El login con credenciales de NextAuth sí lo bloquea.',
            'El anti-replay por nonce del protocolo de firma vive **en memoria de cada instancia**: en varias instancias un replay dentro de la ventana de 120 s contra otra instancia podría pasar.',
            'Sin `WEBHOOK_SECRET` / `RESEND_WEBHOOK_SECRET` los webhooks de Resend se aceptan sin firma (decisión de cada organizador; solo hay un aviso en consola).',
            'Sin KMS/HSM: las claves viven en variables de entorno. Los correos y adjuntos no se cifran a nivel de aplicación.',
            'El rate limit del backend es siempre en memoria (sin Redis).',
            'El antivirus es opcional y falla abierto por defecto; archivos > 25 MB no se escanean.',
            'La política de contraseñas del backend (mínimo 8, Scrypt) es más débil que la del frontend; el backend no tiene MFA.',
            'Sealer: la clave viaja en el enlace del correo (ver [Sealer](/docs/sealer#limits)).',
        ] },
    ],
    en: [
        { t: 'p', text: 'This page describes what the code **does today**, not what would be desirable. Every fact (variable names, defaults, limits) was verified against the code. Known gaps are in [Known limits](#limits) and the standards mapping is in [CIS / NIST / ISO](/docs/compliance).' },
        { t: 'h2', id: 'threat-model', text: 'Threat model (summary)' },
        { t: 'table', head: ['Threat', 'Main mitigation', 'Section'], rows: [
            ['Session theft or fixation', 'HttpOnly `__Host-` cookie, JWT with `jti` and `tokenVersion`, absolute session cap', '[Sessions](#sessions)'],
            ['Brute force and credential stuffing', 'Per-IP and per-account rate limit, lockout, bcrypt cost 12, TOTP MFA', '[Rate limit](#rate-limit)'],
            ['XSS in inbound mail', 'DOMPurify + sandboxed iframe without `allow-same-origin` + inner CSP', '[Mail content](#mail-content)'],
            ['Secrets leaking from DB/backups', 'AES-256-GCM (v3) with `keyId` and rotation; encrypted OAuth tokens', '[Encryption](#encryption)'],
            ['Access to other users\' attachments (IDOR)', 'Server-side ownership checks and HMAC-signed asset URLs', '[Signed assets](#assets)'],
            ['Malware in attachments', 'Magic-bytes, dangerous extensions and optional antivirus', '[Attachments](#attachments)'],
            ['SSRF from extensions', '`safe-fetch`: https only, private IPs blocked, validated at connect time', '[Extensions](#extensions)'],
            ['Impersonation between frontend and backend', 'Per-domain Ed25519 signatures, no shared secrets', '[Architecture](/docs/architecture#trust)'],
            ['CSRF', '`Origin` check on state-changing `/api/*` calls', '[Headers and CSP](#headers)'],
        ] },
        { t: 'h2', id: 'sessions', text: 'Sessions, JWT and revocation' },
        { t: 'ul', items: [
            'HS256 JWT signed with `NEXTAUTH_SECRET` (each frontend has its own). In production, if it is missing the operation fails; in development a fixed development-only value is used.',
            'Claims: `sub`, `email`, `name`, `use:"session"`, `jti`, `tv` (tokenVersion), `at` (login time) and `mfa:true` when a second factor was used.',
            'Cookie `__Host-next-auth.session-token` in production (HttpOnly, SameSite=Lax, Path=/, no Domain, Secure). The old unprefixed cookie is still **read** while `SESSION_COOKIE_LEGACY_READ` is on (default yes); set `SESSION_COOKIE_HOST_PREFIX=0` to disable the prefix.',
            'Sliding lifetime: `SESSION_TTL_SECONDS` (default 86400 = 24 h of inactivity) and absolute cap `SESSION_ABSOLUTE_MAX_SECONDS` (default 1209600 = 14 days from login).',
            'Revocation: `User.tokenVersion` ends all sessions (password change, MFA on/off); the `RevokedSession(jti)` table ends a single one (logout). 5 s per-instance cache (`SESSION_REVOCATION_CACHE_MS`), so across several instances a revocation can take up to that long.',
            'Old tokens without `jti`: accepted up to `SESSION_TTL_SECONDS` after issue; `SESSION_ALLOW_LEGACY_TOKENS=false` rejects them immediately.',
            'Passwords: minimum 12 characters, maximum 72 bytes, common-password list, no repeats or the email name; bcrypt cost 12 with constant-time comparison.',
        ] },
        { t: 'callout', kind: 'warn', title: 'If DDL is missing', text: 'Without the `tokenVersion` column or the `RevokedSession` table the matching mechanism is skipped with a warning (fails open). Run `npm run db:ensure` before deploying ([Operations](/docs/operations#migrations)).' },
        { t: 'h2', id: 'mfa', text: 'TOTP MFA' },
        { t: 'ul', items: [
            'Standard TOTP (RFC 6238: SHA1, 6 digits, 30 s, ±1 step window) with atomic anti-replay. The 160-bit secret is stored encrypted in `UserMfa.secretEnc`; the QR is generated at enrolment.',
            'Ten recovery codes (`XXXXX-XXXXX`) stored as HMAC-SHA256 with `MFA_RECOVERY_PEPPER` (default `NEXTAUTH_SECRET`; pin it if you will rotate `NEXTAUTH_SECRET`). Single use; can be regenerated.',
            '**Mandatory** for the emails in `ADMIN_EMAILS` (turn off with `MFA_ENFORCE_ADMIN=false`) and for everyone when `MFA_REQUIRED_ALL=true`. Optional otherwise.',
            'Attempts: 6 per 5 min per user and 40 per 15 min per IP (429).',
            'Login: if MFA applies, `POST /api/auth/login` returns `mfaRequired` or `mfaEnrollRequired` with a 5-minute `mfaToken` and issues **no** cookie; `POST /api/auth/mfa/verify` issues the session with `mfa:true`.',
            'If the `UserMfa` table is missing and MFA is mandatory for that user, login returns **503** (fails closed).',
            '`requireAdmin` needs an email in `ADMIN_EMAILS` and a session with `mfa:true` when MFA is mandatory.',
        ] },
        { t: 'h2', id: 'encryption', text: 'Encryption at rest' },
        { t: 'table', head: ['Format', 'Layout', 'Algorithm and key'], rows: [
            ['v1 (legacy)', '`iv:ct` in hex', 'AES-256-CBC without authentication. **Read-only**.'],
            ['v2', '`v2:iv:tag:ct`', 'AES-256-GCM, key via HKDF-SHA256 (info `bloomx:data-encryption:v2`).'],
            ['v3 (default)', '`v3:<keyId>:iv:tag:ct`', 'AES-256-GCM, HKDF with `keyId` in the info and in the AAD.'],
        ] },
        { t: 'ul', items: [
            'Current key: `DATA_ENCRYPTION_KEY` with id `DATA_ENCRYPTION_KEY_ID` (default `k1`). Previous keys for decryption: `DATA_ENCRYPTION_KEYS_PREVIOUS="k0:secret,k1:other"`. `NEXTAUTH_SECRET` is a fallback (id `auth`); `ENCRYPTION_REQUIRE_DEDICATED_KEY=true` forces a dedicated key in production.',
            '`ENCRYPTION_WRITE_FORMAT` (default `v3`; use `v2` to roll back).',
            '**Rotation**: define a new key with a new id, move the old one to `DATA_ENCRYPTION_KEYS_PREVIOUS`, let lazy re-encryption migrate what is read, and remove the old key once nothing uses it.',
            'What is encrypted: OAuth tokens in `Account` (lazy migration, `ACCOUNT_TOKENS_LAZY_MIGRATE`), the TOTP secret, expansion settings and server-side sealed messages. Mail bodies and attachments are **not** encrypted at application level; `S3_SSE=AES256|aws:kms` enables provider-side encryption.',
            'Internal keys: each instance\'s server-to-server key is **derived** from its own `NEXTAUTH_SECRET` with HKDF-SHA256 (info `bloomx-internal-v1`); the asset-URL key and the pending-MFA token key are derived as well. That is why there are no secrets to share with the backend.',
            'The backend uses its own `enc:v1:` format (AES-256-GCM with the backend `DATA_ENCRYPTION_KEY`, no `keyId`) for the domain Resend key and extension credentials.',
            'Extension credentials (order: domain, legacy, server environment): platform variables (database, storage, encryption, private keys, `EXTENSION_*`) are on a blocklist no extension can read; the secret only exists inside the sandbox and is never returned or logged. Legacy mode (no signature) still receives credentials, with rate limiting, per-run auditing and no `services.mail`; `requireSignature` rejects it.',
        ] },
        { t: 'h2', id: 'assets', text: 'Signed asset URLs' },
        { t: 'p', text: 'Attachments are served at `/api/assets/<key>?exp=<epoch>&sig=<base64url>`, with `sig = HMAC-SHA256(signing_key, "asset:v1\\n" + key + "\\n" + exp)`. The signing key is `ASSET_SIGNING_KEY` or, if unset, derived from `NEXTAUTH_SECRET`.' },
        { t: 'ul', items: [
            'TTL: `ASSET_URL_TTL_SECONDS` (3600) for received attachments and `ASSET_UPLOAD_URL_TTL_SECONDS` (2592000 = 30 days) for uploads.',
            'Unsigned links: `ASSET_UNSIGNED_INBOUND` (default `owner`: requires the owner\'s session) and `ASSET_UNSIGNED_UPLOADS` (default `allow`); values `allow | owner | deny`. Once old links expire, raise uploads to `owner` or `deny`.',
            'The signed-in owner can always access even with an expired signature. Only `attachments/` and inbound attachment prefixes are served; `..`, `\\`, `\\0` and keys over 1024 characters are rejected. Rejections return 404 and are audited.',
            'Responses carry `nosniff`, `CSP: default-src \'none\'; sandbox`, `Content-Disposition: attachment`, and active types are served as `application/octet-stream`.',
        ] },
        { t: 'h2', id: 'attachments', text: 'Attachments: magic-bytes and antivirus' },
        { t: 'ul', items: [
            'Always on: file-header detection (PE/ELF/Mach-O executables, `#!` scripts, JAR/APK, active HTML/SVG/XML) and a dangerous-extension list (every extension in the name is checked: `a.pdf.exe` is caught). Uploads are rejected; inbound executables are blocked and odd content is sanitised (`INBOUND_BLOCK_DANGEROUS_EXT=false` to skip the extension block). Upload limit: 200 MB.',
            '**Optional** antivirus (ClamAV REST or compatible): set `AV_SCAN_URL` (`AV_SCAN_TOKEN`, `AV_SCAN_FIELD`=`file`, `AV_SCAN_TIMEOUT_MS`=8000). Files above `AV_SCAN_MAX_BYTES` (25 MB) are skipped. `AV_FAIL_MODE=open` (default) accepts when the AV fails and audits it; `closed` blocks uploads with 503.',
        ] },
        { t: 'h2', id: 'retention', text: 'Retention and deletion' },
        { t: 'table', head: ['Variable', 'Default', 'Effect'], rows: [
            ['`RETENTION_SPAM_DAYS`', '30', 'Deletes older spam (0 = off)'],
            ['`RETENTION_TRASH_DAYS`', '0 (off)', 'Deletes trash by creation age'],
            ['`RETENTION_RAW_DAYS`', '0 (off)', 'Deletes the webhook `raw.json`'],
            ['`AUDIT_RETENTION_DAYS`', '365', 'Purges `AuditEvent` (0 = never)'],
            ['`SECURE_MESSAGE_TTL_DAYS`', '30', 'Maximum TTL for sealed messages (+1 day grace)'],
            ['`RETENTION_BATCH`', '200', 'Batch per pass (cap 1000)'],
        ] },
        { t: 'p', text: 'Deletion is complete: HTML, text, `raw.json` and attachments with reference counting (a shared object is kept until nobody uses it). It runs through `GET/POST /api/admin/retention` with `Authorization: Bearer <CRON_SECRET>` or an admin session; `?dryRun=1` only counts.' },
        { t: 'h2', id: 'spam-filter', text: 'Spam filter and blocklist' },
        { t: 'p', text: 'Incoming mail goes through the **blocklist** (envelope sender, `From` and DKIM domain) **before** anything is stored: on a hit no body, attachments or raw copy are stored, `200` is returned and no bounce is generated (no *backscatter*). Then the engine scores authentication, brand impersonation, links, attachments and content signals. Allowed senders do **not** bypass spoofing or malware checks; your own domain and the administrators cannot be blocked; list regexes go through the same ReDoS defense as rules. The decision log stores no content. See [Spam filter and senders](/docs/spam).' },
        { t: 'h2', id: 'mail-transfer', text: 'Import and export mail' },
        { t: 'p', text: 'It moves every user\'s mail content, so it is `requireAdmin` only, with **recent re-authentication** (10 min), confirmation by typing the domain, rate and concurrent-job limits, strict job ownership, content-free auditing, signed one-time download links, an encryptable package (AES-256-GCM + scrypt), and defences against zip-slip, zip-bombs and symlinks. Details in [Import and export mail](/docs/mail-transfer#safeguards).' },
        { t: 'h2', id: 'admin-access', text: 'Administration access: levels and privileged session' },
        { t: 'ul', items: [
            '**Permission levels** (`permission_level` 0-4: user, support, operator, admin, superadmin). Every route and command declares its minimum level in one place (`lib/admin-levels.ts`) and it is checked in `requireLevel(n)` even when the API is called directly (403). `ADMIN_EMAILS` is the seed/rescue: level 4 fixed by environment. See the [scale and rules](/docs/admin-cli#permission-levels).',
            '**Least privilege and separation**: you can only assign a level lower than your own, nobody modifies an account at or above their level nor themselves, and changes require an MFA step-up, are audited (`admin.permissions.changed`) and notified by email; `ADMIN_EMAILS_LOCKED=true` disables console management.',
            '**A single privileged session** per account (web console and CLI together): the new one revokes the previous one immediately (401 `superseded`), with email and push notices; a replacement from another IP or device also alerts the super admins. Closed on **inactivity** (15 min, 5-60 configurable) and an **absolute 12 h** cap (401 `expired`). Three replacements within 10 min **lock** privileged access until a super admin unlocks it. See [privileged session](/docs/admin-cli#privileged-session).',
            '**CLI tokens**: SHA-256 hash, expiry (12 h default, 30 d max), scopes, level capped by the account and immediate revocation when the level drops; automation "machine" tokens are read-only, ≤ 7 d, never level 4 and do not take the slot.',
            'Reference controls: NIST AC-6 (least privilege), AC-10 (concurrent sessions), AC-11/AC-12 (inactivity and termination), IA-2(1) and IA-11 (MFA and re-authentication), AU-2/AU-3; ASVS V3 (sessions) and V4 (access control); CIS 5 and 6; ISO 27001 A.5.15, A.8.2, A.8.5 and A.8.15.',
        ] },
        { t: 'h2', id: 'audit', text: 'Audit' },
        { t: 'ul', items: [
            'Each event is written as a JSON line to stdout and inserted into `AuditEvent` (asynchronous, never breaks the request; 5 consecutive failures pause persistence for 60 s; `AUDIT_DB=off` disables it).',
            'Redaction: keys matching `pass|token|secret|authorization|cookie|key|otp|code|recovery` are omitted, emails are masked and strings are cut at 500 characters.',
            'Recorded events include `auth.login.*`, `auth.mfa.*`, `auth.logout`, `auth.password.changed`, `auth.register.*`, `admin.*`, `assets.denied`, `attachment.blocked`, `av.*`, `email.deleted`, `retention.*`.',
            'The backend audits to stdout only (no table). There is no cryptographic integrity of the log and no built-in SIEM.',
        ] },
        { t: 'h2', id: 'rate-limit', text: 'Rate limit' },
        { t: 'p', text: 'Without Upstash the limit is per instance (memory, fixed window). With `UPSTASH_REDIS_REST_URL` and `UPSTASH_REDIS_REST_TOKEN` it is global (hashed keys, no emails or IPs in clear). If Redis fails (timeout `RATE_LIMIT_REDIS_TIMEOUT_MS`=800; three failures open the circuit for 30 s), `RATE_LIMIT_ON_ERROR=memory` (default) counts in memory and `open` lets requests through; it never blocks everyone. The IP comes from `x-forwarded-for`: only reliable behind a proxy that overwrites it.' },
        { t: 'table', head: ['Endpoint', 'Limit'], rows: [
            ['Login', '20 / 15 min per IP and 10 / 15 min per account'],
            ['Sign-up', '5 / h per IP'],
            ['MFA', '6 / 5 min per user and 40 / 15 min per IP'],
            ['`set-cookie` / `refresh`', '60 / min and 120 / min'],
            ['Uploads', '120 / 10 min per user'],
            ['Sealed message (create / open / consume)', '30 / h per email; 60 / min and 120 / h per IP and id; 120 / min and 240 / h'],
            ['Appointment booking', '10 / h per IP and 3 / h per email'],
            ['Elixir', '1200 / h per user'],
            ['Unsubscribe', '30 / min'],
        ] },
        { t: 'h2', id: 'headers', text: 'Headers, CSP and CSRF' },
        { t: 'ul', items: [
            '`Strict-Transport-Security: max-age=63072000; includeSubDomains; preload`, `X-Content-Type-Options: nosniff`, `X-Frame-Options: SAMEORIGIN`, `Referrer-Policy: strict-origin-when-cross-origin`, `Permissions-Policy` (camera, microphone, geolocation, payment and USB disabled), `Cross-Origin-Opener-Policy: same-origin-allow-popups`.',
            '`/api/auth/*` with `Cache-Control: no-store`; `/secure/*` and `/api/secure-message/*` with `no-referrer`, `no-store` (and `noindex` on `/secure/*`).',
            'CSRF: on state-changing `/api/*` calls, if `Origin` is sent its host must match `Host` (403 otherwise). Without `Origin` (non-browser clients) or with a `Bearer` token nothing is blocked. Webhooks, cron, `/api/config`, `/api/register`, public appointment booking and part of `/api/auth` are exempt.',
        ] },
        { t: 'code', lang: 'csp', title: 'Global CSP (production; development adds unsafe-eval)', code: csp },
        { t: 'callout', kind: 'note', text: 'The CSP allows `\'unsafe-inline\'` in scripts and styles, and generic `https:` in `img-src`/`connect-src`. This is a real limitation (see [Limits](#limits)).' },
        { t: 'h2', id: 'mail-content', text: 'Inbound mail content' },
        { t: 'ul', items: [
            'DOMPurify with an HTML profile (no SVG/MathML; script, iframe, object, embed, form, input, meta, link, base, audio/video and the `srcset`, `ping`, `formaction`, `data-*` attributes are forbidden); URIs limited to http, https, mailto, tel and cid; links get `target=_blank` and `rel="noopener noreferrer nofollow"`.',
            '`SafeIframe`: re-sanitised `srcDoc` with `sandbox="allow-popups allow-popups-to-escape-sandbox allow-scripts"` (no `allow-same-origin`: opaque origin) and its own CSP via `<meta>` (`default-src \'none\'`, scripts only with the viewer\'s own nonce).',
            'Remote images are blocked by default (allow per message or per sender; the policy lives in `localStorage`, key `bloomx:remote-images:v1`).',
            'Anti-phishing warning next to a link when the visible text does not match the destination, or it has punycode (`xn--`), an IP host, `user@` in the URL or a known shortener.',
            'The received message\'s authentication results (SPF/DKIM/DMARC) are shown as a badge.',
        ] },
        { t: 'h2', id: 'extensions', text: 'Extensions: sandbox and SSRF' },
        { t: 'ul', items: [
            'Each invocation runs in its own `worker_threads` worker with an empty `env` and a `node:vm` context; all I/O goes through messages to the main thread. Limits: 128 MB heap, 25 s hard timeout, 20 fetches, 5 AI calls, 500 messages and 200 log lines per invocation, 8 concurrent workers (`EXT_SANDBOX_MAX_WORKERS`).',
            '`safe-fetch`: https only (`EXTENSION_ALLOW_HTTP=true` allows http), no credentials in the URL, blocks localhost/.local/.internal, private ranges, CGNAT, link-local (metadata 169.254.x.x) and IPv6 equivalents; validates the IP **at connect time** (no DNS-rebinding window); at most 3 revalidated redirects; 10 s timeout; 5 MB response cap.',
            'Extensions only read variables declared with `ENV_READ`; reserved names (`DATABASE_URL`, `B2_*`, `NEXTAUTH_*`, `DATA_ENCRYPTION_KEY`, `RESEND_*`…) are forbidden.',
        ] },
        { t: 'callout', kind: 'warn', title: 'Not a strong boundary', text: 'A `vm` escape would share process, file system and network with the backend. Hostile code needs a container or microVM. See [Extensions](/docs/expansions#sandbox).' },
        { t: 'h2', id: 'extension-controls', text: 'Extensions: validation, preferences and mandatory' },
        { t: 'ul', items: [
            '**Validation on publish**: the shared backend validates the manifest **and the UI** (mirror of `ui-schema.ts`, with node, depth and size limits) on every publish and install path. An invalid UI is not stored: 400 (structure) or 422 (UI or limits) with the error path. The `sync-extensions.mjs` and `scripts/sync-repository-extensions.mjs` scripts fail closed if they cannot run the validator.',
            '**Per-user preferences**: the `disabledExtensions` list travels inside the **signed** (Ed25519) body of `hooks`/`execute`, is read on the server from the user\'s encrypted settings and is sanitized on both sides (valid ids, no duplicates, max 200). A tampered list can only turn extensions off **for that same user**.',
            '**Mandatory**: `mandatory: true` in the manifest or a domain policy (`settings.meta.mandatory`, only the domain-owning manager through `POST /api/manager/extensions/mandatory`; audited). The backend always runs them regardless of what the browser sends; the UI does not let users turn them off. DLP ships as mandatory.',
            '**Legacy** unsigned domains: they neither receive nor are subject to the list; everything runs as before (compatibility).',
        ] },
        { t: 'h2', id: 'limits', text: 'Known limits' },
        { t: 'callout', kind: 'warn', title: 'Admin access and the shared backend', text: '`requireAdmin` (`src/lib/admin-auth.ts`) only grants access to `api/admin/*` to (a) a backend "manager" who **owns** this instance\'s domain, or (b) a user whose email is in `ADMIN_EMAILS` with a session carrying `mfa:true`. For (a), the frontend asks the backend with the manager\'s own `auth_session` cookie (`/api/auth/me` and `GET /api/manager/domains`, which only returns that manager\'s domains) and requires one of them to be the instance\'s active domain (`TOP_DOMAIN` / host of `NEXT_PUBLIC_APP_URL`, never client headers). Even though manager registration is open, a foreign manager gets **403** on `api/admin/*` and `POST /api/admin/login` does not forward the session to them. The result is cached for 45 s per session and fails closed: if the backend does not answer or no domain is configured, this path grants nothing. The owner does not need MFA on this path (the manager session belongs to the backend); path (b) does require it. The backend re-checks ownership (`Domain.managerId`) on every manager route that takes a domain (`extensions/install|uninstall`, `extension/settings`, `domain-key`).' },
        { t: 'ul', items: [
            '`AccountManager` (multi-account) stores one JWT per account in `localStorage` (`bloomx_accounts`): readable by any XSS. Mitigated by TTL, absolute cap and `jti` revocation.',
            'The Google callback does not require TOTP from a user who enabled MFA voluntarily (it does block when MFA is mandatory). NextAuth credentials login does block it.',
            'The signing protocol\'s nonce anti-replay lives **in each instance\'s memory**: with several instances a replay inside the 120 s window against another instance could pass.',
            'Without `WEBHOOK_SECRET` / `RESEND_WEBHOOK_SECRET` Resend webhooks are accepted unsigned (each organiser\'s decision; only a console warning).',
            'No KMS/HSM: keys live in environment variables. Mail and attachments are not encrypted at application level.',
            'The backend rate limit is always in-memory (no Redis).',
            'The antivirus is optional and fails open by default; files over 25 MB are not scanned.',
            'The backend password policy (minimum 8, Scrypt) is weaker than the frontend\'s; the backend has no MFA.',
            'Sealer: the key travels in the mail link (see [Sealer](/docs/sealer#limits)).',
        ] },
    ],
};

export default page;
